/* Generated by Yosys 0.9+3710 (git sha1 2116c585, x86_64-conda_cos6-linux-gnu-gcc 1.23.0.449-a04d0 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/tmp/really-long-path/conda/conda-bld/yosys_1606966417886/work=/usr/local/src/conda/yosys-0.9_5007_g2116c585 -fdebug-prefix-map=/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base=/usr/local/src/conda-prefix -fPIC -Os -fno-merge-constants) */

(* dynports =  1  *)
(* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:1.1-18.10" *)
(* top =  1  *)
module top(clk, led, sw);
  (* unused_bits = "0" *)
  wire \$abc$3422$aiger3421$19 ;
  (* unused_bits = "0" *)
  wire \$abc$3422$aiger3421$23 ;
  (* unused_bits = "0" *)
  wire \$abc$3422$aiger3421$24 ;
  (* unused_bits = "0" *)
  wire \$abc$3422$aiger3421$25 ;
  wire \$abc$3422$aiger3421$26 ;
  wire \$abc$3422$aiger3421$27 ;
  (* unused_bits = "0" *)
  wire \$abc$3422$aiger3421$32 ;
  (* unused_bits = "0" *)
  wire \$abc$3422$aiger3421$33 ;
  (* unused_bits = "0" *)
  wire \$abc$3422$aiger3421$34 ;
  (* unused_bits = "0" *)
  wire \$abc$3422$aiger3421$35 ;
  (* force_downto = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.17-14.28|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:166.23-166.24" *)
  wire [7:0] \$auto$alumacc.cc:485:replace_alu$1385.O ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:36.6-36.12" *)
  wire \$techmap3649$auto$simplemap.cc:420:simplemap_dff$1471.CE_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:37.6-37.12" *)
  wire \$techmap3649$auto$simplemap.cc:420:simplemap_dff$1471.SR_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:36.6-36.12" *)
  wire \$techmap3650$auto$simplemap.cc:420:simplemap_dff$1477.CE_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:37.6-37.12" *)
  wire \$techmap3650$auto$simplemap.cc:420:simplemap_dff$1477.SR_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:36.6-36.12" *)
  wire \$techmap3651$auto$simplemap.cc:420:simplemap_dff$1476.CE_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:37.6-37.12" *)
  wire \$techmap3651$auto$simplemap.cc:420:simplemap_dff$1476.SR_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:36.6-36.12" *)
  wire \$techmap3652$auto$simplemap.cc:420:simplemap_dff$1475.CE_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:37.6-37.12" *)
  wire \$techmap3652$auto$simplemap.cc:420:simplemap_dff$1475.SR_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:36.6-36.12" *)
  wire \$techmap3654$auto$simplemap.cc:420:simplemap_dff$1478.CE_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:37.6-37.12" *)
  wire \$techmap3654$auto$simplemap.cc:420:simplemap_dff$1478.SR_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:36.6-36.12" *)
  wire \$techmap3655$auto$simplemap.cc:420:simplemap_dff$1473.CE_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:37.6-37.12" *)
  wire \$techmap3655$auto$simplemap.cc:420:simplemap_dff$1473.SR_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:36.6-36.12" *)
  wire \$techmap3656$auto$simplemap.cc:420:simplemap_dff$1474.CE_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:37.6-37.12" *)
  wire \$techmap3656$auto$simplemap.cc:420:simplemap_dff$1474.SR_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:36.6-36.12" *)
  wire \$techmap3658$auto$simplemap.cc:420:simplemap_dff$1472.CE_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:37.6-37.12" *)
  wire \$techmap3658$auto$simplemap.cc:420:simplemap_dff$1472.SR_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:2.17-2.20" *)
  input clk;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:11.30-11.37" *)
  wire [7:0] counter;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:5.23-5.26" *)
  output [7:0] led;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:4.23-4.25" *)
  input [7:0] sw;
  assign \$auto$alumacc.cc:485:replace_alu$1385.O [0] = 2'h1 >> (* module_not_derived = 32'd1 *) (* src = "/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:4425.24-4425.57|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:190.5-193.4" *) led[0];
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.17-14.28|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:174.11-182.5|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:84.7-101.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8297.7-8314.6" *)
  CARRY4_VPR #(
    .CYINIT_AX(1'h0),
    .CYINIT_C0(1'h1),
    .CYINIT_C1(1'h0)
  ) \$auto$alumacc.cc:485:replace_alu$1385.slice[0].carry4  (
    .CO0(\$abc$3422$aiger3421$23 ),
    .CO1(\$abc$3422$aiger3421$24 ),
    .CO2(\$abc$3422$aiger3421$25 ),
    .CO3(\$abc$3422$aiger3421$26 ),
    .DI0(1'h1),
    .DI1(1'h0),
    .DI2(1'h0),
    .DI3(1'h0),
    .O0(\$abc$3422$aiger3421$19 ),
    .O1(\$auto$alumacc.cc:485:replace_alu$1385.O [1]),
    .O2(\$auto$alumacc.cc:485:replace_alu$1385.O [2]),
    .O3(\$auto$alumacc.cc:485:replace_alu$1385.O [3]),
    .S0(\$auto$alumacc.cc:485:replace_alu$1385.O [0]),
    .S1(led[1]),
    .S2(led[2]),
    .S3(led[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.17-14.28|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6" *)
  CARRY4_VPR #(
    .CYINIT_AX(1'h0),
    .CYINIT_C0(1'h0),
    .CYINIT_C1(1'h0)
  ) \$auto$alumacc.cc:485:replace_alu$1385.slice[1].carry4  (
    .CIN(\$abc$3422$aiger3421$27 ),
    .CO0(\$abc$3422$aiger3421$32 ),
    .CO1(\$abc$3422$aiger3421$33 ),
    .CO2(\$abc$3422$aiger3421$34 ),
    .CO3(\$abc$3422$aiger3421$35 ),
    .DI0(1'h0),
    .DI1(1'h0),
    .DI2(1'h0),
    .DI3(1'h0),
    .O0(\$auto$alumacc.cc:485:replace_alu$1385.O [4]),
    .O1(\$auto$alumacc.cc:485:replace_alu$1385.O [5]),
    .O2(\$auto$alumacc.cc:485:replace_alu$1385.O [6]),
    .O3(\$auto$alumacc.cc:485:replace_alu$1385.O [7]),
    .S0(led[4]),
    .S1(led[5]),
    .S2(led[6]),
    .S3(led[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:420:simplemap_dff$1471  (
    .C(clk),
    .CE(\$techmap3649$auto$simplemap.cc:420:simplemap_dff$1471.CE_SIG ),
    .D(\$auto$alumacc.cc:485:replace_alu$1385.O [0]),
    .Q(led[0]),
    .R(\$techmap3649$auto$simplemap.cc:420:simplemap_dff$1471.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:420:simplemap_dff$1472  (
    .C(clk),
    .CE(\$techmap3658$auto$simplemap.cc:420:simplemap_dff$1472.CE_SIG ),
    .D(\$auto$alumacc.cc:485:replace_alu$1385.O [1]),
    .Q(led[1]),
    .R(\$techmap3658$auto$simplemap.cc:420:simplemap_dff$1472.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:420:simplemap_dff$1473  (
    .C(clk),
    .CE(\$techmap3655$auto$simplemap.cc:420:simplemap_dff$1473.CE_SIG ),
    .D(\$auto$alumacc.cc:485:replace_alu$1385.O [2]),
    .Q(led[2]),
    .R(\$techmap3655$auto$simplemap.cc:420:simplemap_dff$1473.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:420:simplemap_dff$1474  (
    .C(clk),
    .CE(\$techmap3656$auto$simplemap.cc:420:simplemap_dff$1474.CE_SIG ),
    .D(\$auto$alumacc.cc:485:replace_alu$1385.O [3]),
    .Q(led[3]),
    .R(\$techmap3656$auto$simplemap.cc:420:simplemap_dff$1474.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:420:simplemap_dff$1475  (
    .C(clk),
    .CE(\$techmap3652$auto$simplemap.cc:420:simplemap_dff$1475.CE_SIG ),
    .D(\$auto$alumacc.cc:485:replace_alu$1385.O [4]),
    .Q(led[4]),
    .R(\$techmap3652$auto$simplemap.cc:420:simplemap_dff$1475.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:420:simplemap_dff$1476  (
    .C(clk),
    .CE(\$techmap3651$auto$simplemap.cc:420:simplemap_dff$1476.CE_SIG ),
    .D(\$auto$alumacc.cc:485:replace_alu$1385.O [5]),
    .Q(led[5]),
    .R(\$techmap3651$auto$simplemap.cc:420:simplemap_dff$1476.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:420:simplemap_dff$1477  (
    .C(clk),
    .CE(\$techmap3650$auto$simplemap.cc:420:simplemap_dff$1477.CE_SIG ),
    .D(\$auto$alumacc.cc:485:replace_alu$1385.O [6]),
    .Q(led[6]),
    .R(\$techmap3650$auto$simplemap.cc:420:simplemap_dff$1477.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:420:simplemap_dff$1478  (
    .C(clk),
    .CE(\$techmap3654$auto$simplemap.cc:420:simplemap_dff$1478.CE_SIG ),
    .D(\$auto$alumacc.cc:485:replace_alu$1385.O [7]),
    .Q(led[7]),
    .R(\$techmap3654$auto$simplemap.cc:420:simplemap_dff$1478.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.17-14.28|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:104.21-107.6" *)
  CARRY_COUT_PLUG \$techmap1993$auto$alumacc.cc:485:replace_alu$1385.slice[1].carry4.cin_plug  (
    .CIN(\$abc$3422$aiger3421$26 ),
    .COUT(\$abc$3422$aiger3421$27 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:17.12-19.6" *)
  CE_VCC \$techmap3649$auto$simplemap.cc:420:simplemap_dff$1471.cesr_mux.ce  (
    .VCC(\$techmap3649$auto$simplemap.cc:420:simplemap_dff$1471.CE_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:25.12-27.6" *)
  SR_GND \$techmap3649$auto$simplemap.cc:420:simplemap_dff$1471.cesr_mux.sr  (
    .GND(\$techmap3649$auto$simplemap.cc:420:simplemap_dff$1471.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:17.12-19.6" *)
  CE_VCC \$techmap3650$auto$simplemap.cc:420:simplemap_dff$1477.cesr_mux.ce  (
    .VCC(\$techmap3650$auto$simplemap.cc:420:simplemap_dff$1477.CE_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:25.12-27.6" *)
  SR_GND \$techmap3650$auto$simplemap.cc:420:simplemap_dff$1477.cesr_mux.sr  (
    .GND(\$techmap3650$auto$simplemap.cc:420:simplemap_dff$1477.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:17.12-19.6" *)
  CE_VCC \$techmap3651$auto$simplemap.cc:420:simplemap_dff$1476.cesr_mux.ce  (
    .VCC(\$techmap3651$auto$simplemap.cc:420:simplemap_dff$1476.CE_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:25.12-27.6" *)
  SR_GND \$techmap3651$auto$simplemap.cc:420:simplemap_dff$1476.cesr_mux.sr  (
    .GND(\$techmap3651$auto$simplemap.cc:420:simplemap_dff$1476.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:17.12-19.6" *)
  CE_VCC \$techmap3652$auto$simplemap.cc:420:simplemap_dff$1475.cesr_mux.ce  (
    .VCC(\$techmap3652$auto$simplemap.cc:420:simplemap_dff$1475.CE_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:25.12-27.6" *)
  SR_GND \$techmap3652$auto$simplemap.cc:420:simplemap_dff$1475.cesr_mux.sr  (
    .GND(\$techmap3652$auto$simplemap.cc:420:simplemap_dff$1475.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:17.12-19.6" *)
  CE_VCC \$techmap3654$auto$simplemap.cc:420:simplemap_dff$1478.cesr_mux.ce  (
    .VCC(\$techmap3654$auto$simplemap.cc:420:simplemap_dff$1478.CE_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:25.12-27.6" *)
  SR_GND \$techmap3654$auto$simplemap.cc:420:simplemap_dff$1478.cesr_mux.sr  (
    .GND(\$techmap3654$auto$simplemap.cc:420:simplemap_dff$1478.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:17.12-19.6" *)
  CE_VCC \$techmap3655$auto$simplemap.cc:420:simplemap_dff$1473.cesr_mux.ce  (
    .VCC(\$techmap3655$auto$simplemap.cc:420:simplemap_dff$1473.CE_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:25.12-27.6" *)
  SR_GND \$techmap3655$auto$simplemap.cc:420:simplemap_dff$1473.cesr_mux.sr  (
    .GND(\$techmap3655$auto$simplemap.cc:420:simplemap_dff$1473.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:17.12-19.6" *)
  CE_VCC \$techmap3656$auto$simplemap.cc:420:simplemap_dff$1474.cesr_mux.ce  (
    .VCC(\$techmap3656$auto$simplemap.cc:420:simplemap_dff$1474.CE_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:25.12-27.6" *)
  SR_GND \$techmap3656$auto$simplemap.cc:420:simplemap_dff$1474.cesr_mux.sr  (
    .GND(\$techmap3656$auto$simplemap.cc:420:simplemap_dff$1474.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:17.12-19.6" *)
  CE_VCC \$techmap3658$auto$simplemap.cc:420:simplemap_dff$1472.cesr_mux.ce  (
    .VCC(\$techmap3658$auto$simplemap.cc:420:simplemap_dff$1472.CE_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:25.12-27.6" *)
  SR_GND \$techmap3658$auto$simplemap.cc:420:simplemap_dff$1472.cesr_mux.sr  (
    .GND(\$techmap3658$auto$simplemap.cc:420:simplemap_dff$1472.SR_SIG )
  );
  assign counter = led;
endmodule
