/* Generated by Yosys 0.9+3885 (git sha1 afcc31ce, clang 11.0.1 -fPIC -Os) */

(* top =  1  *)
(* src = "top_bit.v:1.1-898.10" *)
module top(clk, \sw[0] , \sw[1] , \sw[2] , \sw[3] , \sw[4] , \sw[5] , \sw[6] , \sw[7] , \led[0] , \led[1] , \led[2] , \led[3] , \led[4] , \led[5] , \led[6] , \led[7] );
  (* src = "top_bit.v:377.5-386.4|../../techmap/lut_simplif.v:4.8-4.16" *)
  wire _0_;
  (* src = "top_bit.v:362.5-371.4|../../techmap/lut_simplif.v:4.18-4.26" *)
  wire _1_;
  (* src = "top_bit.v:2.9-2.12" *)
  input clk;
  (* src = "top_bit.v:4.16-4.19" *)
  output \led[0] ;
  (* src = "top_bit.v:4.16-4.19" *)
  output \led[1] ;
  (* src = "top_bit.v:4.16-4.19" *)
  output \led[2] ;
  (* src = "top_bit.v:4.16-4.19" *)
  output \led[3] ;
  (* src = "top_bit.v:4.16-4.19" *)
  output \led[4] ;
  (* src = "top_bit.v:4.16-4.19" *)
  output \led[5] ;
  (* src = "top_bit.v:4.16-4.19" *)
  output \led[6] ;
  (* src = "top_bit.v:4.16-4.19" *)
  output \led[7] ;
  (* src = "top_bit.v:3.15-3.17" *)
  input \sw[0] ;
  (* src = "top_bit.v:3.15-3.17" *)
  input \sw[1] ;
  (* src = "top_bit.v:3.15-3.17" *)
  input \sw[2] ;
  (* src = "top_bit.v:3.15-3.17" *)
  input \sw[3] ;
  (* src = "top_bit.v:3.15-3.17" *)
  input \sw[4] ;
  (* src = "top_bit.v:3.15-3.17" *)
  input \sw[5] ;
  (* src = "top_bit.v:3.15-3.17" *)
  input \sw[6] ;
  (* src = "top_bit.v:3.15-3.17" *)
  input \sw[7] ;
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:377.5-386.4|../../techmap/lut_simplif.v:30.9-30.66" *)
  MUXF6 \CLBLL_L_X2Y120_SLICE_X1Y120_ALUT.fpga_mux_0  (
    .I0(_0_),
    .I1(\sw[7] ),
    .O(\led[7] ),
    .S(_1_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:377.5-386.4|../../techmap/lut_simplif.v:19.5-26.4" *)
  LUT5 #(
    .INIT(32'd2139160320)
  ) \CLBLL_L_X2Y120_SLICE_X1Y120_ALUT.lut5_1  (
    .I0(\sw[6] ),
    .I1(\sw[5] ),
    .I2(\sw[3] ),
    .I3(\sw[7] ),
    .I4(\sw[4] ),
    .O(_0_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:362.5-371.4|../../techmap/lut_simplif.v:8.5-15.4" *)
  LUT2 #(
    .INIT(4'h1)
  ) \CLBLL_L_X2Y120_SLICE_X1Y120_BLUT.lut5_0  (
    .I0(\sw[2] ),
    .I1(\sw[1] ),
    .O(_1_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:362.5-371.4|../../techmap/lut_simplif.v:19.5-26.4" *)
  LUT2 #(
    .INIT(4'h9)
  ) \CLBLL_L_X2Y120_SLICE_X1Y120_BLUT.lut5_1  (
    .I0(_1_),
    .I1(\sw[3] ),
    .O(\led[3] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:347.5-356.4|../../techmap/lut_simplif.v:8.5-15.4" *)
  LUT3 #(
    .INIT(8'h9c)
  ) \CLBLL_L_X2Y120_SLICE_X1Y120_CLUT.lut5_0  (
    .I0(_1_),
    .I1(\sw[4] ),
    .I2(\sw[3] ),
    .O(\led[4] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:347.5-356.4|../../techmap/lut_simplif.v:19.5-26.4" *)
  LUT4 #(
    .INIT(16'hbf40)
  ) \CLBLL_L_X2Y120_SLICE_X1Y120_CLUT.lut5_1  (
    .I0(_1_),
    .I1(\sw[4] ),
    .I2(\sw[3] ),
    .I3(\sw[5] ),
    .O(\led[5] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:332.5-341.4|../../techmap/lut_simplif.v:8.5-15.4" *)
  LUT5 #(
    .INIT(32'd3429682380)
  ) \CLBLL_L_X2Y120_SLICE_X1Y120_DLUT.lut5_0  (
    .I0(\sw[3] ),
    .I1(\sw[6] ),
    .I2(\sw[5] ),
    .I3(_1_),
    .I4(\sw[4] ),
    .O(\led[6] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:437.5-446.4|../../techmap/lut_simplif.v:8.5-15.4|../../techmap/lut1_simplif.v:6.11-6.43" *)
  INV \CLBLL_R_X13Y120_SLICE_X18Y120_ALUT.lut5_0  (
    .I(\sw[1] ),
    .O(\led[1] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:437.5-446.4|../../techmap/lut_simplif.v:19.5-26.4" *)
  LUT2 #(
    .INIT(4'h9)
  ) \CLBLL_R_X13Y120_SLICE_X18Y120_ALUT.lut5_1  (
    .I0(\sw[2] ),
    .I1(\sw[1] ),
    .O(\led[2] )
  );
  assign \led[0]  = \sw[0] ;
endmodule
