/* Generated by Yosys 0.9+3885 (git sha1 afcc31ce, clang 11.0.1 -fPIC -Os) */

(* top =  1  *)
module top(\led[2] , \led[1] , \led[0] , \sw[7] , \sw[6] , \sw[5] , \sw[4] , \sw[3] , \sw[2] , \sw[1] , \sw[0] , clk, \led[3] , \led[4] , \led[5] , \led[6] , \led[7] );
  wire \$abc$1841$lut\led[7].T0 ;
  wire \$techmap1848$abc$1841$lut\led[7].A[5] ;
  input clk;
  output \led[0] ;
  output \led[1] ;
  output \led[2] ;
  output \led[3] ;
  output \led[4] ;
  output \led[5] ;
  output \led[6] ;
  output \led[7] ;
  input \sw[0] ;
  input \sw[1] ;
  input \sw[2] ;
  input \sw[3] ;
  input \sw[4] ;
  input \sw[5] ;
  input \sw[6] ;
  input \sw[7] ;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:61.26-63.41|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:257.9-257.53" *)
  MUXF6 \$abc$1841$lut\led[7].fpga_mux_0  (
    .I0(\$abc$1841$lut\led[7].T0 ),
    .I1(\sw[7] ),
    .O(\led[7] ),
    .S(\$techmap1848$abc$1841$lut\led[7].A[5] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h1)
  ) \$auto$blifparse.cc:498:parse_blif$432  (
    .I0(\sw[1] ),
    .I1(\sw[2] ),
    .O(\$techmap1848$abc$1841$lut\led[7].A[5] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48" *)
  INV \$auto$blifparse.cc:498:parse_blif$433  (
    .I(\sw[1] ),
    .O(\led[1] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h9)
  ) \$auto$blifparse.cc:498:parse_blif$434  (
    .I0(\sw[1] ),
    .I1(\sw[2] ),
    .O(\led[2] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h9)
  ) \$auto$blifparse.cc:498:parse_blif$435  (
    .I0(\$techmap1848$abc$1841$lut\led[7].A[5] ),
    .I1(\sw[3] ),
    .O(\led[3] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'hb4)
  ) \$auto$blifparse.cc:498:parse_blif$436  (
    .I0(\$techmap1848$abc$1841$lut\led[7].A[5] ),
    .I1(\sw[3] ),
    .I2(\sw[4] ),
    .O(\led[4] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19" *)
  LUT4 #(
    .INIT(16'hbf40)
  ) \$auto$blifparse.cc:498:parse_blif$437  (
    .I0(\$techmap1848$abc$1841$lut\led[7].A[5] ),
    .I1(\sw[3] ),
    .I2(\sw[4] ),
    .I3(\sw[5] ),
    .O(\led[5] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd3221176320)
  ) \$auto$blifparse.cc:498:parse_blif$438  (
    .I0(\$techmap1848$abc$1841$lut\led[7].A[5] ),
    .I1(\sw[3] ),
    .I2(\sw[4] ),
    .I3(\sw[5] ),
    .I4(\sw[6] ),
    .O(\led[6] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd2147450880)
  ) \$auto$blifparse.cc:498:parse_blif$439  (
    .I0(\sw[3] ),
    .I1(\sw[4] ),
    .I2(\sw[5] ),
    .I3(\sw[6] ),
    .I4(\sw[7] ),
    .O(\$abc$1841$lut\led[7].T0 )
  );
  assign \led[0]  = \sw[0] ;
endmodule
