/* Generated by Yosys 0.9+3710 (git sha1 2116c585, x86_64-conda_cos6-linux-gnu-gcc 1.23.0.449-a04d0 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/tmp/really-long-path/conda/conda-bld/yosys_1606966417886/work=/usr/local/src/conda/yosys-0.9_5007_g2116c585 -fdebug-prefix-map=/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base=/usr/local/src/conda-prefix -fPIC -Os -fno-merge-constants) */

(* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:1.1-12.10" *)
(* top =  1  *)
module top(clk, led, sw);
  wire \$abc$1856$aiger1855$3b ;
  (* unused_bits = "0" *)
  wire \$abc$3388$aiger3387$12 ;
  (* unused_bits = "0" *)
  wire \$abc$3388$aiger3387$16 ;
  (* unused_bits = "0" *)
  wire \$abc$3388$aiger3387$17 ;
  (* unused_bits = "0" *)
  wire \$abc$3388$aiger3387$18 ;
  wire \$abc$3388$aiger3387$19 ;
  wire \$abc$3388$aiger3387$20 ;
  (* unused_bits = "0" *)
  wire \$abc$3388$aiger3387$25 ;
  (* unused_bits = "0" *)
  wire \$abc$3388$aiger3387$26 ;
  (* unused_bits = "0" *)
  wire \$abc$3388$aiger3387$27 ;
  (* unused_bits = "0" *)
  wire \$abc$3388$aiger3387$28 ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:2.17-2.20" *)
  input clk;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:5.23-5.26" *)
  output [7:0] led;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:4.23-4.25" *)
  input [7:0] sw;
  assign led[0] = 2'h1 >> (* module_not_derived = 32'd1 *) (* src = "/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:4425.24-4425.57|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:190.5-193.4" *) sw[0];
  assign \$abc$1856$aiger1855$3b  = 2'h1 >> (* module_not_derived = 32'd1 *) (* src = "/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:4425.24-4425.57|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:190.5-193.4" *) sw[1];
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:11.18-11.24|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:174.11-182.5|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:84.7-101.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8297.7-8314.6" *)
  CARRY4_VPR #(
    .CYINIT_AX(1'h0),
    .CYINIT_C0(1'h1),
    .CYINIT_C1(1'h0)
  ) \$auto$alumacc.cc:485:replace_alu$1381.slice[0].carry4  (
    .CO0(\$abc$3388$aiger3387$16 ),
    .CO1(\$abc$3388$aiger3387$17 ),
    .CO2(\$abc$3388$aiger3387$18 ),
    .CO3(\$abc$3388$aiger3387$19 ),
    .DI0(1'h1),
    .DI1(1'h1),
    .DI2(1'h0),
    .DI3(1'h0),
    .O0(\$abc$3388$aiger3387$12 ),
    .O1(led[1]),
    .O2(led[2]),
    .O3(led[3]),
    .S0(led[0]),
    .S1(\$abc$1856$aiger1855$3b ),
    .S2(sw[2]),
    .S3(sw[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:11.18-11.24|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6" *)
  CARRY4_VPR #(
    .CYINIT_AX(1'h0),
    .CYINIT_C0(1'h0),
    .CYINIT_C1(1'h0)
  ) \$auto$alumacc.cc:485:replace_alu$1381.slice[1].carry4  (
    .CIN(\$abc$3388$aiger3387$20 ),
    .CO0(\$abc$3388$aiger3387$25 ),
    .CO1(\$abc$3388$aiger3387$26 ),
    .CO2(\$abc$3388$aiger3387$27 ),
    .CO3(\$abc$3388$aiger3387$28 ),
    .DI0(1'h0),
    .DI1(1'h0),
    .DI2(1'h0),
    .DI3(1'h0),
    .O0(led[4]),
    .O1(led[5]),
    .O2(led[6]),
    .O3(led[7]),
    .S0(sw[4]),
    .S1(sw[5]),
    .S2(sw[6]),
    .S3(sw[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:11.18-11.24|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:104.21-107.6" *)
  CARRY_COUT_PLUG \$techmap1958$auto$alumacc.cc:485:replace_alu$1381.slice[1].carry4.cin_plug  (
    .CIN(\$abc$3388$aiger3387$19 ),
    .COUT(\$abc$3388$aiger3387$20 )
  );
endmodule
