/* Generated by Yosys 0.9+3885 (git sha1 afcc31ce, clang 11.0.1 -fPIC -Os) */

(* top =  1  *)
(* src = "top_bit.v:1.1-1796.10" *)
module top(clk, \sw[0] , \sw[1] , \sw[2] , \sw[3] , \sw[4] , \sw[5] , \sw[6] , \sw[7] , \led[0] , \led[1] , \led[2] , \led[3] , \led[4] , \led[5] , \led[6] , \led[7] );
  (* hdlname = "$auto$simplemap.cc:420:simplemap_dff$1471CLBLL_R_X17Y118_SLICE_X27Y118_D_FDRE D" *)
  (* src = "top_bit.v:604.5-610.4|../../techmap/cells_map.v:32.41-32.42" *)
  wire \$auto$simplemap.cc:420:simplemap_dff$1471CLBLL_R_X17Y118_SLICE_X27Y118_D_FDRE.D ;
  (* hdlname = "$auto$simplemap.cc:420:simplemap_dff$1471CLBLL_R_X17Y118_SLICE_X27Y118_D_FDRE _TECHMAP_REPLACE_ Q" *)
  (* src = "top_bit.v:604.5-610.4|../../techmap/cells_sim.v:12.30-12.31|../../techmap/cells_map.v:48.3-48.67" *)
  reg \$auto$simplemap.cc:420:simplemap_dff$1471CLBLL_R_X17Y118_SLICE_X27Y118_D_FDRE._TECHMAP_REPLACE_.Q  = 1'h0;
  (* hdlname = "$auto$simplemap.cc:420:simplemap_dff$1472CLBLL_R_X17Y118_SLICE_X27Y118_C_FDRE D" *)
  (* src = "top_bit.v:591.5-597.4|../../techmap/cells_map.v:32.41-32.42" *)
  wire \$auto$simplemap.cc:420:simplemap_dff$1472CLBLL_R_X17Y118_SLICE_X27Y118_C_FDRE.D ;
  (* hdlname = "$auto$simplemap.cc:420:simplemap_dff$1472CLBLL_R_X17Y118_SLICE_X27Y118_C_FDRE _TECHMAP_REPLACE_ Q" *)
  (* src = "top_bit.v:591.5-597.4|../../techmap/cells_sim.v:12.30-12.31|../../techmap/cells_map.v:48.3-48.67" *)
  reg \$auto$simplemap.cc:420:simplemap_dff$1472CLBLL_R_X17Y118_SLICE_X27Y118_C_FDRE._TECHMAP_REPLACE_.Q  = 1'h0;
  (* hdlname = "$auto$simplemap.cc:420:simplemap_dff$1473CLBLL_R_X17Y118_SLICE_X27Y118_A_FDRE D" *)
  (* src = "top_bit.v:565.5-571.4|../../techmap/cells_map.v:32.41-32.42" *)
  wire \$auto$simplemap.cc:420:simplemap_dff$1473CLBLL_R_X17Y118_SLICE_X27Y118_A_FDRE.D ;
  (* hdlname = "$auto$simplemap.cc:420:simplemap_dff$1473CLBLL_R_X17Y118_SLICE_X27Y118_A_FDRE _TECHMAP_REPLACE_ Q" *)
  (* src = "top_bit.v:565.5-571.4|../../techmap/cells_sim.v:12.30-12.31|../../techmap/cells_map.v:48.3-48.67" *)
  reg \$auto$simplemap.cc:420:simplemap_dff$1473CLBLL_R_X17Y118_SLICE_X27Y118_A_FDRE._TECHMAP_REPLACE_.Q  = 1'h0;
  (* hdlname = "$auto$simplemap.cc:420:simplemap_dff$1474CLBLL_R_X17Y118_SLICE_X27Y118_B_FDRE D" *)
  (* src = "top_bit.v:578.5-584.4|../../techmap/cells_map.v:32.41-32.42" *)
  wire \$auto$simplemap.cc:420:simplemap_dff$1474CLBLL_R_X17Y118_SLICE_X27Y118_B_FDRE.D ;
  (* hdlname = "$auto$simplemap.cc:420:simplemap_dff$1474CLBLL_R_X17Y118_SLICE_X27Y118_B_FDRE _TECHMAP_REPLACE_ Q" *)
  (* src = "top_bit.v:578.5-584.4|../../techmap/cells_sim.v:12.30-12.31|../../techmap/cells_map.v:48.3-48.67" *)
  reg \$auto$simplemap.cc:420:simplemap_dff$1474CLBLL_R_X17Y118_SLICE_X27Y118_B_FDRE._TECHMAP_REPLACE_.Q  = 1'h0;
  (* hdlname = "$auto$simplemap.cc:420:simplemap_dff$1475CLBLL_R_X17Y119_SLICE_X27Y119_C_FDRE D" *)
  (* src = "top_bit.v:775.5-781.4|../../techmap/cells_map.v:32.41-32.42" *)
  wire \$auto$simplemap.cc:420:simplemap_dff$1475CLBLL_R_X17Y119_SLICE_X27Y119_C_FDRE.D ;
  (* hdlname = "$auto$simplemap.cc:420:simplemap_dff$1475CLBLL_R_X17Y119_SLICE_X27Y119_C_FDRE _TECHMAP_REPLACE_ Q" *)
  (* src = "top_bit.v:775.5-781.4|../../techmap/cells_sim.v:12.30-12.31|../../techmap/cells_map.v:48.3-48.67" *)
  reg \$auto$simplemap.cc:420:simplemap_dff$1475CLBLL_R_X17Y119_SLICE_X27Y119_C_FDRE._TECHMAP_REPLACE_.Q  = 1'h0;
  (* hdlname = "$auto$simplemap.cc:420:simplemap_dff$1476CLBLL_R_X17Y119_SLICE_X27Y119_D_FDRE D" *)
  (* src = "top_bit.v:788.5-794.4|../../techmap/cells_map.v:32.41-32.42" *)
  wire \$auto$simplemap.cc:420:simplemap_dff$1476CLBLL_R_X17Y119_SLICE_X27Y119_D_FDRE.D ;
  (* hdlname = "$auto$simplemap.cc:420:simplemap_dff$1476CLBLL_R_X17Y119_SLICE_X27Y119_D_FDRE _TECHMAP_REPLACE_ Q" *)
  (* src = "top_bit.v:788.5-794.4|../../techmap/cells_sim.v:12.30-12.31|../../techmap/cells_map.v:48.3-48.67" *)
  reg \$auto$simplemap.cc:420:simplemap_dff$1476CLBLL_R_X17Y119_SLICE_X27Y119_D_FDRE._TECHMAP_REPLACE_.Q  = 1'h0;
  (* hdlname = "$auto$simplemap.cc:420:simplemap_dff$1477CLBLL_R_X17Y119_SLICE_X27Y119_A_FDRE D" *)
  (* src = "top_bit.v:749.5-755.4|../../techmap/cells_map.v:32.41-32.42" *)
  wire \$auto$simplemap.cc:420:simplemap_dff$1477CLBLL_R_X17Y119_SLICE_X27Y119_A_FDRE.D ;
  (* hdlname = "$auto$simplemap.cc:420:simplemap_dff$1477CLBLL_R_X17Y119_SLICE_X27Y119_A_FDRE _TECHMAP_REPLACE_ Q" *)
  (* src = "top_bit.v:749.5-755.4|../../techmap/cells_sim.v:12.30-12.31|../../techmap/cells_map.v:48.3-48.67" *)
  reg \$auto$simplemap.cc:420:simplemap_dff$1477CLBLL_R_X17Y119_SLICE_X27Y119_A_FDRE._TECHMAP_REPLACE_.Q  = 1'h0;
  (* hdlname = "$auto$simplemap.cc:420:simplemap_dff$1478CLBLL_R_X17Y119_SLICE_X27Y119_B_FDRE D" *)
  (* src = "top_bit.v:762.5-768.4|../../techmap/cells_map.v:32.41-32.42" *)
  wire \$auto$simplemap.cc:420:simplemap_dff$1478CLBLL_R_X17Y119_SLICE_X27Y119_B_FDRE.D ;
  (* hdlname = "$auto$simplemap.cc:420:simplemap_dff$1478CLBLL_R_X17Y119_SLICE_X27Y119_B_FDRE _TECHMAP_REPLACE_ Q" *)
  (* src = "top_bit.v:762.5-768.4|../../techmap/cells_sim.v:12.30-12.31|../../techmap/cells_map.v:48.3-48.67" *)
  reg \$auto$simplemap.cc:420:simplemap_dff$1478CLBLL_R_X17Y119_SLICE_X27Y119_B_FDRE._TECHMAP_REPLACE_.Q  = 1'h0;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_ALUT I4" *)
  (* src = "top_bit.v:673.5-682.4|../../techmap/cells_formal.v:9.13-9.15" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.I4 ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_ALUT O6" *)
  (* src = "top_bit.v:673.5-682.4|../../techmap/cells_formal.v:12.14-12.16" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.O6 ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_ALUT lower_s1" *)
  (* src = "top_bit.v:673.5-682.4|../../techmap/cells_formal.v:27.15-27.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s1[0] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_ALUT lower_s2" *)
  (* src = "top_bit.v:673.5-682.4|../../techmap/cells_formal.v:26.15-26.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s2[0] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_ALUT lower_s2" *)
  (* src = "top_bit.v:673.5-682.4|../../techmap/cells_formal.v:26.15-26.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s2[1] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_ALUT lower_s3" *)
  (* src = "top_bit.v:673.5-682.4|../../techmap/cells_formal.v:25.15-25.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s3[0] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_ALUT lower_s3" *)
  (* src = "top_bit.v:673.5-682.4|../../techmap/cells_formal.v:25.15-25.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s3[1] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_ALUT lower_s3" *)
  (* src = "top_bit.v:673.5-682.4|../../techmap/cells_formal.v:25.15-25.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s3[2] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_ALUT lower_s3" *)
  (* src = "top_bit.v:673.5-682.4|../../techmap/cells_formal.v:25.15-25.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s3[3] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_ALUT lower_s4" *)
  (* src = "top_bit.v:673.5-682.4|../../techmap/cells_formal.v:24.15-24.23" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[0] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_ALUT lower_s4" *)
  (* src = "top_bit.v:673.5-682.4|../../techmap/cells_formal.v:24.15-24.23" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[10] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_ALUT lower_s4" *)
  (* src = "top_bit.v:673.5-682.4|../../techmap/cells_formal.v:24.15-24.23" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[11] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_ALUT lower_s4" *)
  (* src = "top_bit.v:673.5-682.4|../../techmap/cells_formal.v:24.15-24.23" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[12] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_ALUT lower_s4" *)
  (* src = "top_bit.v:673.5-682.4|../../techmap/cells_formal.v:24.15-24.23" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[13] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_ALUT lower_s4" *)
  (* src = "top_bit.v:673.5-682.4|../../techmap/cells_formal.v:24.15-24.23" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[14] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_ALUT lower_s4" *)
  (* src = "top_bit.v:673.5-682.4|../../techmap/cells_formal.v:24.15-24.23" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[15] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_ALUT lower_s4" *)
  (* src = "top_bit.v:673.5-682.4|../../techmap/cells_formal.v:24.15-24.23" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[1] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_ALUT lower_s4" *)
  (* src = "top_bit.v:673.5-682.4|../../techmap/cells_formal.v:24.15-24.23" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[2] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_ALUT lower_s4" *)
  (* src = "top_bit.v:673.5-682.4|../../techmap/cells_formal.v:24.15-24.23" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[3] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_ALUT lower_s4" *)
  (* src = "top_bit.v:673.5-682.4|../../techmap/cells_formal.v:24.15-24.23" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[4] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_ALUT lower_s4" *)
  (* src = "top_bit.v:673.5-682.4|../../techmap/cells_formal.v:24.15-24.23" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[5] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_ALUT lower_s4" *)
  (* src = "top_bit.v:673.5-682.4|../../techmap/cells_formal.v:24.15-24.23" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[6] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_ALUT lower_s4" *)
  (* src = "top_bit.v:673.5-682.4|../../techmap/cells_formal.v:24.15-24.23" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[7] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_ALUT lower_s4" *)
  (* src = "top_bit.v:673.5-682.4|../../techmap/cells_formal.v:24.15-24.23" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[8] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_ALUT lower_s4" *)
  (* src = "top_bit.v:673.5-682.4|../../techmap/cells_formal.v:24.15-24.23" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[9] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_ALUT upper_s1" *)
  (* src = "top_bit.v:673.5-682.4|../../techmap/cells_formal.v:20.15-20.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.upper_s1[0] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_ALUT upper_s2" *)
  (* src = "top_bit.v:673.5-682.4|../../techmap/cells_formal.v:19.15-19.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.upper_s2[0] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_ALUT upper_s2" *)
  (* src = "top_bit.v:673.5-682.4|../../techmap/cells_formal.v:19.15-19.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.upper_s2[1] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_ALUT upper_s3" *)
  (* src = "top_bit.v:673.5-682.4|../../techmap/cells_formal.v:18.15-18.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.upper_s3[0] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_ALUT upper_s3" *)
  (* src = "top_bit.v:673.5-682.4|../../techmap/cells_formal.v:18.15-18.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.upper_s3[1] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_ALUT upper_s3" *)
  (* src = "top_bit.v:673.5-682.4|../../techmap/cells_formal.v:18.15-18.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.upper_s3[2] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_ALUT upper_s3" *)
  (* src = "top_bit.v:673.5-682.4|../../techmap/cells_formal.v:18.15-18.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.upper_s3[3] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_BLUT I4" *)
  (* src = "top_bit.v:658.5-667.4|../../techmap/cells_formal.v:9.13-9.15" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.I4 ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_BLUT O6" *)
  (* src = "top_bit.v:658.5-667.4|../../techmap/cells_formal.v:12.14-12.16" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.O6 ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_BLUT lower_s1" *)
  (* src = "top_bit.v:658.5-667.4|../../techmap/cells_formal.v:27.15-27.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.lower_s1[0] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_BLUT lower_s2" *)
  (* src = "top_bit.v:658.5-667.4|../../techmap/cells_formal.v:26.15-26.23" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.lower_s2[0] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_BLUT lower_s2" *)
  (* src = "top_bit.v:658.5-667.4|../../techmap/cells_formal.v:26.15-26.23" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.lower_s2[1] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_BLUT lower_s2" *)
  (* src = "top_bit.v:658.5-667.4|../../techmap/cells_formal.v:26.15-26.23" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.lower_s2[2] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_BLUT lower_s2" *)
  (* src = "top_bit.v:658.5-667.4|../../techmap/cells_formal.v:26.15-26.23" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.lower_s2[3] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_BLUT lower_s3" *)
  (* src = "top_bit.v:658.5-667.4|../../techmap/cells_formal.v:25.15-25.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.lower_s3[0] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_BLUT lower_s3" *)
  (* src = "top_bit.v:658.5-667.4|../../techmap/cells_formal.v:25.15-25.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.lower_s3[1] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_BLUT lower_s3" *)
  (* src = "top_bit.v:658.5-667.4|../../techmap/cells_formal.v:25.15-25.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.lower_s3[2] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_BLUT lower_s3" *)
  (* src = "top_bit.v:658.5-667.4|../../techmap/cells_formal.v:25.15-25.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.lower_s3[3] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_BLUT lower_s4" *)
  (* src = "top_bit.v:658.5-667.4|../../techmap/cells_formal.v:24.15-24.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.lower_s4[0] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_BLUT lower_s4" *)
  (* src = "top_bit.v:658.5-667.4|../../techmap/cells_formal.v:24.15-24.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.lower_s4[1] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_BLUT lower_s4" *)
  (* src = "top_bit.v:658.5-667.4|../../techmap/cells_formal.v:24.15-24.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.lower_s4[2] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_BLUT lower_s4" *)
  (* src = "top_bit.v:658.5-667.4|../../techmap/cells_formal.v:24.15-24.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.lower_s4[3] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_BLUT lower_s4" *)
  (* src = "top_bit.v:658.5-667.4|../../techmap/cells_formal.v:24.15-24.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.lower_s4[4] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_BLUT lower_s4" *)
  (* src = "top_bit.v:658.5-667.4|../../techmap/cells_formal.v:24.15-24.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.lower_s4[5] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_BLUT lower_s4" *)
  (* src = "top_bit.v:658.5-667.4|../../techmap/cells_formal.v:24.15-24.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.lower_s4[6] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_BLUT lower_s4" *)
  (* src = "top_bit.v:658.5-667.4|../../techmap/cells_formal.v:24.15-24.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.lower_s4[7] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_BLUT upper_s1" *)
  (* src = "top_bit.v:658.5-667.4|../../techmap/cells_formal.v:20.15-20.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.upper_s1[0] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_CARRY4 CO" *)
  (* src = "top_bit.v:615.5-622.4|../../techmap/cells_formal.v:55.16-55.18" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_CARRY4.CO[0] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_CARRY4 CO" *)
  (* src = "top_bit.v:615.5-622.4|../../techmap/cells_formal.v:55.16-55.18" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_CARRY4.CO[1] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_CARRY4 CO" *)
  (* src = "top_bit.v:615.5-622.4|../../techmap/cells_formal.v:55.16-55.18" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_CARRY4.CO[2] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_CARRY4 O" *)
  (* src = "top_bit.v:615.5-622.4|../../techmap/cells_formal.v:56.16-56.17" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_CARRY4.O[0] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_CARRY4 O" *)
  (* src = "top_bit.v:615.5-622.4|../../techmap/cells_formal.v:56.16-56.17" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_CARRY4.O[1] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_CARRY4 S" *)
  (* src = "top_bit.v:615.5-622.4|../../techmap/cells_formal.v:60.20-60.21" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_CARRY4.S[2] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_CARRY4 S" *)
  (* src = "top_bit.v:615.5-622.4|../../techmap/cells_formal.v:60.20-60.21" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_CARRY4.S[3] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_CLUT lower_s1" *)
  (* src = "top_bit.v:643.5-652.4|../../techmap/cells_formal.v:27.15-27.23" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_CLUT.lower_s1[0] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_CLUT lower_s1" *)
  (* src = "top_bit.v:643.5-652.4|../../techmap/cells_formal.v:27.15-27.23" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_CLUT.lower_s1[1] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_DLUT upper_s1" *)
  (* src = "top_bit.v:628.5-637.4|../../techmap/cells_formal.v:20.15-20.23" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_DLUT.upper_s1[0] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_DLUT upper_s1" *)
  (* src = "top_bit.v:628.5-637.4|../../techmap/cells_formal.v:20.15-20.23" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_DLUT.upper_s1[1] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_DLUT upper_s2" *)
  (* src = "top_bit.v:628.5-637.4|../../techmap/cells_formal.v:19.15-19.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_DLUT.upper_s2[0] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_DLUT upper_s2" *)
  (* src = "top_bit.v:628.5-637.4|../../techmap/cells_formal.v:19.15-19.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_DLUT.upper_s2[1] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_DLUT upper_s3" *)
  (* src = "top_bit.v:628.5-637.4|../../techmap/cells_formal.v:18.15-18.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_DLUT.upper_s3[0] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_DLUT upper_s3" *)
  (* src = "top_bit.v:628.5-637.4|../../techmap/cells_formal.v:18.15-18.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_DLUT.upper_s3[1] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_DLUT upper_s3" *)
  (* src = "top_bit.v:628.5-637.4|../../techmap/cells_formal.v:18.15-18.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_DLUT.upper_s3[2] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_DLUT upper_s3" *)
  (* src = "top_bit.v:628.5-637.4|../../techmap/cells_formal.v:18.15-18.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_DLUT.upper_s3[3] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_DLUT upper_s4" *)
  (* src = "top_bit.v:628.5-637.4|../../techmap/cells_formal.v:17.15-17.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_DLUT.upper_s4[0] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_DLUT upper_s4" *)
  (* src = "top_bit.v:628.5-637.4|../../techmap/cells_formal.v:17.15-17.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_DLUT.upper_s4[1] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_DLUT upper_s4" *)
  (* src = "top_bit.v:628.5-637.4|../../techmap/cells_formal.v:17.15-17.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_DLUT.upper_s4[2] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_DLUT upper_s4" *)
  (* src = "top_bit.v:628.5-637.4|../../techmap/cells_formal.v:17.15-17.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_DLUT.upper_s4[3] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_DLUT upper_s4" *)
  (* src = "top_bit.v:628.5-637.4|../../techmap/cells_formal.v:17.15-17.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_DLUT.upper_s4[4] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_DLUT upper_s4" *)
  (* src = "top_bit.v:628.5-637.4|../../techmap/cells_formal.v:17.15-17.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_DLUT.upper_s4[5] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_DLUT upper_s4" *)
  (* src = "top_bit.v:628.5-637.4|../../techmap/cells_formal.v:17.15-17.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_DLUT.upper_s4[6] ;
  (* hdlname = "CLBLL_R_X17Y118_SLICE_X27Y118_DLUT upper_s4" *)
  (* src = "top_bit.v:628.5-637.4|../../techmap/cells_formal.v:17.15-17.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y118_SLICE_X27Y118_DLUT.upper_s4[7] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_ALUT I4" *)
  (* src = "top_bit.v:857.5-866.4|../../techmap/cells_formal.v:9.13-9.15" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.I4 ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_ALUT O6" *)
  (* src = "top_bit.v:857.5-866.4|../../techmap/cells_formal.v:12.14-12.16" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.O6 ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_ALUT lower_s1" *)
  (* src = "top_bit.v:857.5-866.4|../../techmap/cells_formal.v:27.15-27.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.lower_s1[0] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_ALUT lower_s2" *)
  (* src = "top_bit.v:857.5-866.4|../../techmap/cells_formal.v:26.15-26.23" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.lower_s2[0] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_ALUT lower_s2" *)
  (* src = "top_bit.v:857.5-866.4|../../techmap/cells_formal.v:26.15-26.23" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.lower_s2[1] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_ALUT lower_s2" *)
  (* src = "top_bit.v:857.5-866.4|../../techmap/cells_formal.v:26.15-26.23" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.lower_s2[2] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_ALUT lower_s2" *)
  (* src = "top_bit.v:857.5-866.4|../../techmap/cells_formal.v:26.15-26.23" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.lower_s2[3] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_ALUT lower_s3" *)
  (* src = "top_bit.v:857.5-866.4|../../techmap/cells_formal.v:25.15-25.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.lower_s3[0] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_ALUT lower_s3" *)
  (* src = "top_bit.v:857.5-866.4|../../techmap/cells_formal.v:25.15-25.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.lower_s3[1] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_ALUT lower_s3" *)
  (* src = "top_bit.v:857.5-866.4|../../techmap/cells_formal.v:25.15-25.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.lower_s3[2] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_ALUT lower_s3" *)
  (* src = "top_bit.v:857.5-866.4|../../techmap/cells_formal.v:25.15-25.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.lower_s3[3] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_ALUT lower_s4" *)
  (* src = "top_bit.v:857.5-866.4|../../techmap/cells_formal.v:24.15-24.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.lower_s4[0] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_ALUT lower_s4" *)
  (* src = "top_bit.v:857.5-866.4|../../techmap/cells_formal.v:24.15-24.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.lower_s4[1] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_ALUT lower_s4" *)
  (* src = "top_bit.v:857.5-866.4|../../techmap/cells_formal.v:24.15-24.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.lower_s4[2] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_ALUT lower_s4" *)
  (* src = "top_bit.v:857.5-866.4|../../techmap/cells_formal.v:24.15-24.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.lower_s4[3] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_ALUT lower_s4" *)
  (* src = "top_bit.v:857.5-866.4|../../techmap/cells_formal.v:24.15-24.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.lower_s4[4] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_ALUT lower_s4" *)
  (* src = "top_bit.v:857.5-866.4|../../techmap/cells_formal.v:24.15-24.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.lower_s4[5] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_ALUT lower_s4" *)
  (* src = "top_bit.v:857.5-866.4|../../techmap/cells_formal.v:24.15-24.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.lower_s4[6] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_ALUT lower_s4" *)
  (* src = "top_bit.v:857.5-866.4|../../techmap/cells_formal.v:24.15-24.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.lower_s4[7] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_ALUT upper_s1" *)
  (* src = "top_bit.v:857.5-866.4|../../techmap/cells_formal.v:20.15-20.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.upper_s1[0] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_BLUT I4" *)
  (* src = "top_bit.v:842.5-851.4|../../techmap/cells_formal.v:9.13-9.15" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.I4 ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_BLUT O6" *)
  (* src = "top_bit.v:842.5-851.4|../../techmap/cells_formal.v:12.14-12.16" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.O6 ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_BLUT lower_s1" *)
  (* src = "top_bit.v:842.5-851.4|../../techmap/cells_formal.v:27.15-27.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.lower_s1[0] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_BLUT lower_s2" *)
  (* src = "top_bit.v:842.5-851.4|../../techmap/cells_formal.v:26.15-26.23" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.lower_s2[0] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_BLUT lower_s2" *)
  (* src = "top_bit.v:842.5-851.4|../../techmap/cells_formal.v:26.15-26.23" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.lower_s2[1] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_BLUT lower_s2" *)
  (* src = "top_bit.v:842.5-851.4|../../techmap/cells_formal.v:26.15-26.23" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.lower_s2[2] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_BLUT lower_s2" *)
  (* src = "top_bit.v:842.5-851.4|../../techmap/cells_formal.v:26.15-26.23" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.lower_s2[3] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_BLUT lower_s3" *)
  (* src = "top_bit.v:842.5-851.4|../../techmap/cells_formal.v:25.15-25.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.lower_s3[0] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_BLUT lower_s3" *)
  (* src = "top_bit.v:842.5-851.4|../../techmap/cells_formal.v:25.15-25.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.lower_s3[1] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_BLUT lower_s3" *)
  (* src = "top_bit.v:842.5-851.4|../../techmap/cells_formal.v:25.15-25.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.lower_s3[2] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_BLUT lower_s3" *)
  (* src = "top_bit.v:842.5-851.4|../../techmap/cells_formal.v:25.15-25.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.lower_s3[3] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_BLUT lower_s4" *)
  (* src = "top_bit.v:842.5-851.4|../../techmap/cells_formal.v:24.15-24.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.lower_s4[0] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_BLUT lower_s4" *)
  (* src = "top_bit.v:842.5-851.4|../../techmap/cells_formal.v:24.15-24.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.lower_s4[1] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_BLUT lower_s4" *)
  (* src = "top_bit.v:842.5-851.4|../../techmap/cells_formal.v:24.15-24.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.lower_s4[2] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_BLUT lower_s4" *)
  (* src = "top_bit.v:842.5-851.4|../../techmap/cells_formal.v:24.15-24.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.lower_s4[3] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_BLUT lower_s4" *)
  (* src = "top_bit.v:842.5-851.4|../../techmap/cells_formal.v:24.15-24.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.lower_s4[4] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_BLUT lower_s4" *)
  (* src = "top_bit.v:842.5-851.4|../../techmap/cells_formal.v:24.15-24.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.lower_s4[5] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_BLUT lower_s4" *)
  (* src = "top_bit.v:842.5-851.4|../../techmap/cells_formal.v:24.15-24.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.lower_s4[6] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_BLUT lower_s4" *)
  (* src = "top_bit.v:842.5-851.4|../../techmap/cells_formal.v:24.15-24.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.lower_s4[7] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_BLUT upper_s1" *)
  (* src = "top_bit.v:842.5-851.4|../../techmap/cells_formal.v:20.15-20.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.upper_s1[0] ;
  (* abc9_carry = 32'd1 *)
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_CARRY4 CI" *)
  (* src = "top_bit.v:799.5-806.4|../../techmap/cells_formal.v:58.16-58.18" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_CARRY4.CI ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_CARRY4 CO" *)
  (* src = "top_bit.v:799.5-806.4|../../techmap/cells_formal.v:55.16-55.18" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_CARRY4.CO[0] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_CARRY4 CO" *)
  (* src = "top_bit.v:799.5-806.4|../../techmap/cells_formal.v:55.16-55.18" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_CARRY4.CO[1] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_CARRY4 CO" *)
  (* src = "top_bit.v:799.5-806.4|../../techmap/cells_formal.v:55.16-55.18" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_CARRY4.CO[2] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_CARRY4 O" *)
  (* src = "top_bit.v:799.5-806.4|../../techmap/cells_formal.v:56.16-56.17" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_CARRY4.O[0] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_CARRY4 O" *)
  (* src = "top_bit.v:799.5-806.4|../../techmap/cells_formal.v:56.16-56.17" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_CARRY4.O[1] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_CARRY4 S" *)
  (* src = "top_bit.v:799.5-806.4|../../techmap/cells_formal.v:60.20-60.21" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_CARRY4.S[2] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_CARRY4 S" *)
  (* src = "top_bit.v:799.5-806.4|../../techmap/cells_formal.v:60.20-60.21" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_CARRY4.S[3] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_CLUT lower_s1" *)
  (* src = "top_bit.v:827.5-836.4|../../techmap/cells_formal.v:27.15-27.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_CLUT.lower_s1[0] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_CLUT upper_s1" *)
  (* src = "top_bit.v:827.5-836.4|../../techmap/cells_formal.v:20.15-20.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_CLUT.upper_s1[0] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_CLUT upper_s2" *)
  (* src = "top_bit.v:827.5-836.4|../../techmap/cells_formal.v:19.15-19.23" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_CLUT.upper_s2[0] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_CLUT upper_s2" *)
  (* src = "top_bit.v:827.5-836.4|../../techmap/cells_formal.v:19.15-19.23" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_CLUT.upper_s2[1] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_CLUT upper_s2" *)
  (* src = "top_bit.v:827.5-836.4|../../techmap/cells_formal.v:19.15-19.23" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_CLUT.upper_s2[2] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_CLUT upper_s2" *)
  (* src = "top_bit.v:827.5-836.4|../../techmap/cells_formal.v:19.15-19.23" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_CLUT.upper_s2[3] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_DLUT upper_s1" *)
  (* src = "top_bit.v:812.5-821.4|../../techmap/cells_formal.v:20.15-20.23" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_DLUT.upper_s1[0] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_DLUT upper_s1" *)
  (* src = "top_bit.v:812.5-821.4|../../techmap/cells_formal.v:20.15-20.23" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_DLUT.upper_s1[1] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_DLUT upper_s2" *)
  (* src = "top_bit.v:812.5-821.4|../../techmap/cells_formal.v:19.15-19.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_DLUT.upper_s2[0] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_DLUT upper_s2" *)
  (* src = "top_bit.v:812.5-821.4|../../techmap/cells_formal.v:19.15-19.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_DLUT.upper_s2[1] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_DLUT upper_s3" *)
  (* src = "top_bit.v:812.5-821.4|../../techmap/cells_formal.v:18.15-18.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_DLUT.upper_s3[0] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_DLUT upper_s3" *)
  (* src = "top_bit.v:812.5-821.4|../../techmap/cells_formal.v:18.15-18.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_DLUT.upper_s3[1] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_DLUT upper_s3" *)
  (* src = "top_bit.v:812.5-821.4|../../techmap/cells_formal.v:18.15-18.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_DLUT.upper_s3[2] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_DLUT upper_s3" *)
  (* src = "top_bit.v:812.5-821.4|../../techmap/cells_formal.v:18.15-18.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_DLUT.upper_s3[3] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_DLUT upper_s4" *)
  (* src = "top_bit.v:812.5-821.4|../../techmap/cells_formal.v:17.15-17.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_DLUT.upper_s4[0] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_DLUT upper_s4" *)
  (* src = "top_bit.v:812.5-821.4|../../techmap/cells_formal.v:17.15-17.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_DLUT.upper_s4[1] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_DLUT upper_s4" *)
  (* src = "top_bit.v:812.5-821.4|../../techmap/cells_formal.v:17.15-17.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_DLUT.upper_s4[2] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_DLUT upper_s4" *)
  (* src = "top_bit.v:812.5-821.4|../../techmap/cells_formal.v:17.15-17.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_DLUT.upper_s4[3] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_DLUT upper_s4" *)
  (* src = "top_bit.v:812.5-821.4|../../techmap/cells_formal.v:17.15-17.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_DLUT.upper_s4[4] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_DLUT upper_s4" *)
  (* src = "top_bit.v:812.5-821.4|../../techmap/cells_formal.v:17.15-17.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_DLUT.upper_s4[5] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_DLUT upper_s4" *)
  (* src = "top_bit.v:812.5-821.4|../../techmap/cells_formal.v:17.15-17.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_DLUT.upper_s4[6] ;
  (* hdlname = "CLBLL_R_X17Y119_SLICE_X27Y119_DLUT upper_s4" *)
  (* src = "top_bit.v:812.5-821.4|../../techmap/cells_formal.v:17.15-17.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y119_SLICE_X27Y119_DLUT.upper_s4[7] ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_ALUT O6" *)
  (* src = "top_bit.v:1041.5-1050.4|../../techmap/cells_formal.v:12.14-12.16" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_ALUT.O6 ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_ALUT upper_s1" *)
  (* src = "top_bit.v:1041.5-1050.4|../../techmap/cells_formal.v:20.15-20.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_ALUT.upper_s1[0] ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_A_FDRE D" *)
  (* src = "top_bit.v:933.5-939.4|../../techmap/cells_map.v:32.41-32.42" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_A_FDRE.D ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_A_FDRE _TECHMAP_REPLACE_ Q" *)
  (* init = 1'h0 *)
  (* src = "top_bit.v:933.5-939.4|../../techmap/cells_sim.v:12.30-12.31|../../techmap/cells_map.v:48.3-48.67" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_A_FDRE._TECHMAP_REPLACE_.Q ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_BLUT I3" *)
  (* src = "top_bit.v:1026.5-1035.4|../../techmap/cells_formal.v:8.13-8.15" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_BLUT.I3 ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_BLUT O5" *)
  (* src = "top_bit.v:1026.5-1035.4|../../techmap/cells_formal.v:13.14-13.16" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_BLUT.O5 ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_BLUT O6" *)
  (* src = "top_bit.v:1026.5-1035.4|../../techmap/cells_formal.v:12.14-12.16" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_BLUT.O6 ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_BLUT lower_s1" *)
  (* src = "top_bit.v:1026.5-1035.4|../../techmap/cells_formal.v:27.15-27.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_BLUT.lower_s1[0] ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_BLUT lower_s2" *)
  (* src = "top_bit.v:1026.5-1035.4|../../techmap/cells_formal.v:26.15-26.23" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_BLUT.lower_s2[0] ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_BLUT lower_s2" *)
  (* src = "top_bit.v:1026.5-1035.4|../../techmap/cells_formal.v:26.15-26.23" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_BLUT.lower_s2[1] ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_BLUT lower_s2" *)
  (* src = "top_bit.v:1026.5-1035.4|../../techmap/cells_formal.v:26.15-26.23" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_BLUT.lower_s2[2] ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_BLUT lower_s2" *)
  (* src = "top_bit.v:1026.5-1035.4|../../techmap/cells_formal.v:26.15-26.23" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_BLUT.lower_s2[3] ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_BLUT lower_s3" *)
  (* src = "top_bit.v:1026.5-1035.4|../../techmap/cells_formal.v:25.15-25.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_BLUT.lower_s3[0] ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_BLUT lower_s3" *)
  (* src = "top_bit.v:1026.5-1035.4|../../techmap/cells_formal.v:25.15-25.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_BLUT.lower_s3[1] ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_BLUT lower_s3" *)
  (* src = "top_bit.v:1026.5-1035.4|../../techmap/cells_formal.v:25.15-25.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_BLUT.lower_s3[2] ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_BLUT lower_s3" *)
  (* src = "top_bit.v:1026.5-1035.4|../../techmap/cells_formal.v:25.15-25.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_BLUT.lower_s3[3] ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_BLUT upper_s1" *)
  (* src = "top_bit.v:1026.5-1035.4|../../techmap/cells_formal.v:20.15-20.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_BLUT.upper_s1[0] ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_B_FDRE _TECHMAP_REPLACE_ Q" *)
  (* init = 1'h0 *)
  (* src = "top_bit.v:946.5-952.4|../../techmap/cells_sim.v:12.30-12.31|../../techmap/cells_map.v:48.3-48.67" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_B_FDRE._TECHMAP_REPLACE_.Q ;
  (* abc9_carry = 32'd1 *)
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_CARRY4 CI" *)
  (* src = "top_bit.v:983.5-990.4|../../techmap/cells_formal.v:58.16-58.18" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_CARRY4.CI ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_CARRY4 CO" *)
  (* src = "top_bit.v:983.5-990.4|../../techmap/cells_formal.v:55.16-55.18" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_CARRY4.CO[0] ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_CARRY4 CO" *)
  (* src = "top_bit.v:983.5-990.4|../../techmap/cells_formal.v:55.16-55.18" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_CARRY4.CO[1] ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_CARRY4 CO" *)
  (* src = "top_bit.v:983.5-990.4|../../techmap/cells_formal.v:55.16-55.18" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_CARRY4.CO[2] ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_CARRY4 O" *)
  (* src = "top_bit.v:983.5-990.4|../../techmap/cells_formal.v:56.16-56.17" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_CARRY4.O[1] ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_CARRY4 O" *)
  (* src = "top_bit.v:983.5-990.4|../../techmap/cells_formal.v:56.16-56.17" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_CARRY4.O[3] ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_CARRY4 S" *)
  (* src = "top_bit.v:983.5-990.4|../../techmap/cells_formal.v:60.20-60.21" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_CARRY4.S[2] ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_CARRY4 S" *)
  (* src = "top_bit.v:983.5-990.4|../../techmap/cells_formal.v:60.20-60.21" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_CARRY4.S[3] ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_CLUT O5" *)
  (* src = "top_bit.v:1011.5-1020.4|../../techmap/cells_formal.v:13.14-13.16" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_CLUT.O5 ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_CLUT upper_s1" *)
  (* src = "top_bit.v:1011.5-1020.4|../../techmap/cells_formal.v:20.15-20.23" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_CLUT.upper_s1[0] ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_CLUT upper_s1" *)
  (* src = "top_bit.v:1011.5-1020.4|../../techmap/cells_formal.v:20.15-20.23" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_CLUT.upper_s1[1] ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_C_FDRE _TECHMAP_REPLACE_ Q" *)
  (* init = 1'h0 *)
  (* src = "top_bit.v:959.5-965.4|../../techmap/cells_sim.v:12.30-12.31|../../techmap/cells_map.v:48.3-48.67" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_C_FDRE._TECHMAP_REPLACE_.Q ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_DLUT O5" *)
  (* src = "top_bit.v:996.5-1005.4|../../techmap/cells_formal.v:13.14-13.16" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_DLUT.O5 ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_DLUT lower_s1" *)
  (* src = "top_bit.v:996.5-1005.4|../../techmap/cells_formal.v:27.15-27.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_DLUT.lower_s1[0] ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_DLUT lower_s2" *)
  (* src = "top_bit.v:996.5-1005.4|../../techmap/cells_formal.v:26.15-26.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_DLUT.lower_s2[0] ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_DLUT lower_s2" *)
  (* src = "top_bit.v:996.5-1005.4|../../techmap/cells_formal.v:26.15-26.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_DLUT.lower_s2[1] ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_DLUT lower_s3" *)
  (* src = "top_bit.v:996.5-1005.4|../../techmap/cells_formal.v:25.15-25.23" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_DLUT.lower_s3[0] ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_DLUT lower_s3" *)
  (* src = "top_bit.v:996.5-1005.4|../../techmap/cells_formal.v:25.15-25.23" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_DLUT.lower_s3[1] ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_DLUT lower_s3" *)
  (* src = "top_bit.v:996.5-1005.4|../../techmap/cells_formal.v:25.15-25.23" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_DLUT.lower_s3[2] ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_DLUT lower_s3" *)
  (* src = "top_bit.v:996.5-1005.4|../../techmap/cells_formal.v:25.15-25.23" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_DLUT.lower_s3[3] ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_DLUT lower_s3" *)
  (* src = "top_bit.v:996.5-1005.4|../../techmap/cells_formal.v:25.15-25.23" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_DLUT.lower_s3[4] ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_DLUT lower_s3" *)
  (* src = "top_bit.v:996.5-1005.4|../../techmap/cells_formal.v:25.15-25.23" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_DLUT.lower_s3[5] ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_DLUT lower_s3" *)
  (* src = "top_bit.v:996.5-1005.4|../../techmap/cells_formal.v:25.15-25.23" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_DLUT.lower_s3[6] ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_DLUT lower_s3" *)
  (* src = "top_bit.v:996.5-1005.4|../../techmap/cells_formal.v:25.15-25.23" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_DLUT.lower_s3[7] ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_DLUT upper_s1" *)
  (* src = "top_bit.v:996.5-1005.4|../../techmap/cells_formal.v:20.15-20.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_DLUT.upper_s1[0] ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_DLUT upper_s2" *)
  (* src = "top_bit.v:996.5-1005.4|../../techmap/cells_formal.v:19.15-19.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_DLUT.upper_s2[0] ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_DLUT upper_s2" *)
  (* src = "top_bit.v:996.5-1005.4|../../techmap/cells_formal.v:19.15-19.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_DLUT.upper_s2[1] ;
  (* hdlname = "CLBLL_R_X17Y120_SLICE_X27Y120_D_FDRE _TECHMAP_REPLACE_ Q" *)
  (* init = 1'h0 *)
  (* src = "top_bit.v:972.5-978.4|../../techmap/cells_sim.v:12.30-12.31|../../techmap/cells_map.v:48.3-48.67" *)
  wire \CLBLL_R_X17Y120_SLICE_X27Y120_D_FDRE._TECHMAP_REPLACE_.Q ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_ALUT O6" *)
  (* src = "top_bit.v:1225.5-1234.4|../../techmap/cells_formal.v:12.14-12.16" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_ALUT.O6 ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_ALUT upper_s1" *)
  (* src = "top_bit.v:1225.5-1234.4|../../techmap/cells_formal.v:20.15-20.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_ALUT.upper_s1[0] ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_A_FDRE D" *)
  (* src = "top_bit.v:1117.5-1123.4|../../techmap/cells_map.v:32.41-32.42" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_A_FDRE.D ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_A_FDRE _TECHMAP_REPLACE_ Q" *)
  (* init = 1'h0 *)
  (* src = "top_bit.v:1117.5-1123.4|../../techmap/cells_sim.v:12.30-12.31|../../techmap/cells_map.v:48.3-48.67" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_A_FDRE._TECHMAP_REPLACE_.Q ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_BLUT I3" *)
  (* src = "top_bit.v:1210.5-1219.4|../../techmap/cells_formal.v:8.13-8.15" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_BLUT.I3 ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_BLUT O5" *)
  (* src = "top_bit.v:1210.5-1219.4|../../techmap/cells_formal.v:13.14-13.16" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_BLUT.O5 ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_BLUT O6" *)
  (* src = "top_bit.v:1210.5-1219.4|../../techmap/cells_formal.v:12.14-12.16" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_BLUT.O6 ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_BLUT lower_s1" *)
  (* src = "top_bit.v:1210.5-1219.4|../../techmap/cells_formal.v:27.15-27.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_BLUT.lower_s1[0] ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_BLUT lower_s2" *)
  (* src = "top_bit.v:1210.5-1219.4|../../techmap/cells_formal.v:26.15-26.23" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_BLUT.lower_s2[0] ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_BLUT lower_s2" *)
  (* src = "top_bit.v:1210.5-1219.4|../../techmap/cells_formal.v:26.15-26.23" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_BLUT.lower_s2[1] ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_BLUT lower_s2" *)
  (* src = "top_bit.v:1210.5-1219.4|../../techmap/cells_formal.v:26.15-26.23" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_BLUT.lower_s2[2] ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_BLUT lower_s2" *)
  (* src = "top_bit.v:1210.5-1219.4|../../techmap/cells_formal.v:26.15-26.23" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_BLUT.lower_s2[3] ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_BLUT lower_s3" *)
  (* src = "top_bit.v:1210.5-1219.4|../../techmap/cells_formal.v:25.15-25.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_BLUT.lower_s3[0] ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_BLUT lower_s3" *)
  (* src = "top_bit.v:1210.5-1219.4|../../techmap/cells_formal.v:25.15-25.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_BLUT.lower_s3[1] ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_BLUT lower_s3" *)
  (* src = "top_bit.v:1210.5-1219.4|../../techmap/cells_formal.v:25.15-25.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_BLUT.lower_s3[2] ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_BLUT lower_s3" *)
  (* src = "top_bit.v:1210.5-1219.4|../../techmap/cells_formal.v:25.15-25.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_BLUT.lower_s3[3] ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_BLUT upper_s1" *)
  (* src = "top_bit.v:1210.5-1219.4|../../techmap/cells_formal.v:20.15-20.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_BLUT.upper_s1[0] ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_B_FDRE _TECHMAP_REPLACE_ Q" *)
  (* init = 1'h0 *)
  (* src = "top_bit.v:1130.5-1136.4|../../techmap/cells_sim.v:12.30-12.31|../../techmap/cells_map.v:48.3-48.67" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_B_FDRE._TECHMAP_REPLACE_.Q ;
  (* abc9_carry = 32'd1 *)
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_CARRY4 CI" *)
  (* src = "top_bit.v:1167.5-1174.4|../../techmap/cells_formal.v:58.16-58.18" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_CARRY4.CI ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_CARRY4 CO" *)
  (* src = "top_bit.v:1167.5-1174.4|../../techmap/cells_formal.v:55.16-55.18" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_CARRY4.CO[0] ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_CARRY4 CO" *)
  (* src = "top_bit.v:1167.5-1174.4|../../techmap/cells_formal.v:55.16-55.18" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_CARRY4.CO[1] ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_CARRY4 CO" *)
  (* src = "top_bit.v:1167.5-1174.4|../../techmap/cells_formal.v:55.16-55.18" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_CARRY4.CO[2] ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_CARRY4 O" *)
  (* src = "top_bit.v:1167.5-1174.4|../../techmap/cells_formal.v:56.16-56.17" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_CARRY4.O[1] ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_CARRY4 O" *)
  (* src = "top_bit.v:1167.5-1174.4|../../techmap/cells_formal.v:56.16-56.17" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_CARRY4.O[3] ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_CARRY4 S" *)
  (* src = "top_bit.v:1167.5-1174.4|../../techmap/cells_formal.v:60.20-60.21" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_CARRY4.S[2] ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_CARRY4 S" *)
  (* src = "top_bit.v:1167.5-1174.4|../../techmap/cells_formal.v:60.20-60.21" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_CARRY4.S[3] ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_CLUT O5" *)
  (* src = "top_bit.v:1195.5-1204.4|../../techmap/cells_formal.v:13.14-13.16" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_CLUT.O5 ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_CLUT upper_s1" *)
  (* src = "top_bit.v:1195.5-1204.4|../../techmap/cells_formal.v:20.15-20.23" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_CLUT.upper_s1[0] ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_CLUT upper_s1" *)
  (* src = "top_bit.v:1195.5-1204.4|../../techmap/cells_formal.v:20.15-20.23" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_CLUT.upper_s1[1] ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_C_FDRE _TECHMAP_REPLACE_ Q" *)
  (* init = 1'h0 *)
  (* src = "top_bit.v:1143.5-1149.4|../../techmap/cells_sim.v:12.30-12.31|../../techmap/cells_map.v:48.3-48.67" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_C_FDRE._TECHMAP_REPLACE_.Q ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_DLUT O5" *)
  (* src = "top_bit.v:1180.5-1189.4|../../techmap/cells_formal.v:13.14-13.16" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_DLUT.O5 ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_DLUT lower_s1" *)
  (* src = "top_bit.v:1180.5-1189.4|../../techmap/cells_formal.v:27.15-27.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_DLUT.lower_s1[0] ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_DLUT lower_s2" *)
  (* src = "top_bit.v:1180.5-1189.4|../../techmap/cells_formal.v:26.15-26.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_DLUT.lower_s2[0] ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_DLUT lower_s2" *)
  (* src = "top_bit.v:1180.5-1189.4|../../techmap/cells_formal.v:26.15-26.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_DLUT.lower_s2[1] ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_DLUT lower_s3" *)
  (* src = "top_bit.v:1180.5-1189.4|../../techmap/cells_formal.v:25.15-25.23" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_DLUT.lower_s3[0] ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_DLUT lower_s3" *)
  (* src = "top_bit.v:1180.5-1189.4|../../techmap/cells_formal.v:25.15-25.23" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_DLUT.lower_s3[1] ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_DLUT lower_s3" *)
  (* src = "top_bit.v:1180.5-1189.4|../../techmap/cells_formal.v:25.15-25.23" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_DLUT.lower_s3[2] ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_DLUT lower_s3" *)
  (* src = "top_bit.v:1180.5-1189.4|../../techmap/cells_formal.v:25.15-25.23" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_DLUT.lower_s3[3] ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_DLUT lower_s3" *)
  (* src = "top_bit.v:1180.5-1189.4|../../techmap/cells_formal.v:25.15-25.23" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_DLUT.lower_s3[4] ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_DLUT lower_s3" *)
  (* src = "top_bit.v:1180.5-1189.4|../../techmap/cells_formal.v:25.15-25.23" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_DLUT.lower_s3[5] ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_DLUT lower_s3" *)
  (* src = "top_bit.v:1180.5-1189.4|../../techmap/cells_formal.v:25.15-25.23" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_DLUT.lower_s3[6] ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_DLUT lower_s3" *)
  (* src = "top_bit.v:1180.5-1189.4|../../techmap/cells_formal.v:25.15-25.23" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_DLUT.lower_s3[7] ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_DLUT upper_s1" *)
  (* src = "top_bit.v:1180.5-1189.4|../../techmap/cells_formal.v:20.15-20.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_DLUT.upper_s1[0] ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_DLUT upper_s2" *)
  (* src = "top_bit.v:1180.5-1189.4|../../techmap/cells_formal.v:19.15-19.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_DLUT.upper_s2[0] ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_DLUT upper_s2" *)
  (* src = "top_bit.v:1180.5-1189.4|../../techmap/cells_formal.v:19.15-19.23" *)
  (* unused_bits = "0" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_DLUT.upper_s2[1] ;
  (* hdlname = "CLBLL_R_X17Y121_SLICE_X27Y121_D_FDRE _TECHMAP_REPLACE_ Q" *)
  (* init = 1'h0 *)
  (* src = "top_bit.v:1156.5-1162.4|../../techmap/cells_sim.v:12.30-12.31|../../techmap/cells_map.v:48.3-48.67" *)
  wire \CLBLL_R_X17Y121_SLICE_X27Y121_D_FDRE._TECHMAP_REPLACE_.Q ;
  (* src = "top_bit.v:2.9-2.12" *)
  input clk;
  (* src = "top_bit.v:4.16-4.19" *)
  output \led[0] ;
  reg \led[0] ;
  (* src = "top_bit.v:4.16-4.19" *)
  output \led[1] ;
  reg \led[1] ;
  (* src = "top_bit.v:4.16-4.19" *)
  output \led[2] ;
  reg \led[2] ;
  (* src = "top_bit.v:4.16-4.19" *)
  output \led[3] ;
  reg \led[3] ;
  (* src = "top_bit.v:4.16-4.19" *)
  output \led[4] ;
  reg \led[4] ;
  (* src = "top_bit.v:4.16-4.19" *)
  output \led[5] ;
  reg \led[5] ;
  (* src = "top_bit.v:4.16-4.19" *)
  output \led[6] ;
  reg \led[6] ;
  (* src = "top_bit.v:4.16-4.19" *)
  output \led[7] ;
  reg \led[7] ;
  (* src = "top_bit.v:3.15-3.17" *)
  input \sw[0] ;
  (* src = "top_bit.v:3.15-3.17" *)
  input \sw[1] ;
  (* src = "top_bit.v:3.15-3.17" *)
  input \sw[2] ;
  (* src = "top_bit.v:3.15-3.17" *)
  input \sw[3] ;
  (* src = "top_bit.v:3.15-3.17" *)
  input \sw[4] ;
  (* src = "top_bit.v:3.15-3.17" *)
  input \sw[5] ;
  (* src = "top_bit.v:3.15-3.17" *)
  input \sw[6] ;
  (* src = "top_bit.v:3.15-3.17" *)
  input \sw[7] ;
  (* src = "top_bit.v:604.5-610.4|../../techmap/cells_sim.v:17.11-17.69|../../techmap/cells_map.v:48.3-48.67" *)
  always @(posedge clk)
    \$auto$simplemap.cc:420:simplemap_dff$1471CLBLL_R_X17Y118_SLICE_X27Y118_D_FDRE._TECHMAP_REPLACE_.Q  <= \$auto$simplemap.cc:420:simplemap_dff$1471CLBLL_R_X17Y118_SLICE_X27Y118_D_FDRE.D ;
  (* src = "top_bit.v:591.5-597.4|../../techmap/cells_sim.v:17.11-17.69|../../techmap/cells_map.v:48.3-48.67" *)
  always @(posedge clk)
    \$auto$simplemap.cc:420:simplemap_dff$1472CLBLL_R_X17Y118_SLICE_X27Y118_C_FDRE._TECHMAP_REPLACE_.Q  <= \$auto$simplemap.cc:420:simplemap_dff$1472CLBLL_R_X17Y118_SLICE_X27Y118_C_FDRE.D ;
  (* src = "top_bit.v:565.5-571.4|../../techmap/cells_sim.v:17.11-17.69|../../techmap/cells_map.v:48.3-48.67" *)
  always @(posedge clk)
    \$auto$simplemap.cc:420:simplemap_dff$1473CLBLL_R_X17Y118_SLICE_X27Y118_A_FDRE._TECHMAP_REPLACE_.Q  <= \$auto$simplemap.cc:420:simplemap_dff$1473CLBLL_R_X17Y118_SLICE_X27Y118_A_FDRE.D ;
  (* src = "top_bit.v:578.5-584.4|../../techmap/cells_sim.v:17.11-17.69|../../techmap/cells_map.v:48.3-48.67" *)
  always @(posedge clk)
    \$auto$simplemap.cc:420:simplemap_dff$1474CLBLL_R_X17Y118_SLICE_X27Y118_B_FDRE._TECHMAP_REPLACE_.Q  <= \$auto$simplemap.cc:420:simplemap_dff$1474CLBLL_R_X17Y118_SLICE_X27Y118_B_FDRE.D ;
  (* src = "top_bit.v:775.5-781.4|../../techmap/cells_sim.v:17.11-17.69|../../techmap/cells_map.v:48.3-48.67" *)
  always @(posedge clk)
    \$auto$simplemap.cc:420:simplemap_dff$1475CLBLL_R_X17Y119_SLICE_X27Y119_C_FDRE._TECHMAP_REPLACE_.Q  <= \$auto$simplemap.cc:420:simplemap_dff$1475CLBLL_R_X17Y119_SLICE_X27Y119_C_FDRE.D ;
  (* src = "top_bit.v:788.5-794.4|../../techmap/cells_sim.v:17.11-17.69|../../techmap/cells_map.v:48.3-48.67" *)
  always @(posedge clk)
    \$auto$simplemap.cc:420:simplemap_dff$1476CLBLL_R_X17Y119_SLICE_X27Y119_D_FDRE._TECHMAP_REPLACE_.Q  <= \$auto$simplemap.cc:420:simplemap_dff$1476CLBLL_R_X17Y119_SLICE_X27Y119_D_FDRE.D ;
  (* src = "top_bit.v:749.5-755.4|../../techmap/cells_sim.v:17.11-17.69|../../techmap/cells_map.v:48.3-48.67" *)
  always @(posedge clk)
    \$auto$simplemap.cc:420:simplemap_dff$1477CLBLL_R_X17Y119_SLICE_X27Y119_A_FDRE._TECHMAP_REPLACE_.Q  <= \$auto$simplemap.cc:420:simplemap_dff$1477CLBLL_R_X17Y119_SLICE_X27Y119_A_FDRE.D ;
  (* src = "top_bit.v:762.5-768.4|../../techmap/cells_sim.v:17.11-17.69|../../techmap/cells_map.v:48.3-48.67" *)
  always @(posedge clk)
    \$auto$simplemap.cc:420:simplemap_dff$1478CLBLL_R_X17Y119_SLICE_X27Y119_B_FDRE._TECHMAP_REPLACE_.Q  <= \$auto$simplemap.cc:420:simplemap_dff$1478CLBLL_R_X17Y119_SLICE_X27Y119_B_FDRE.D ;
  assign { \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.O6 , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.upper_s1[0] , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.upper_s2[1] , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.upper_s2[0] , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.upper_s3[3] , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.upper_s3[2] , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.upper_s3[1] , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.upper_s3[0]  } = \$auto$simplemap.cc:420:simplemap_dff$1471CLBLL_R_X17Y118_SLICE_X27Y118_D_FDRE._TECHMAP_REPLACE_.Q  ? (* src = "top_bit.v:673.5-682.4|../../techmap/cells_formal.v:18.26-18.66" *) 8'h00 : 8'hff;
  assign { \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[15] , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[14] , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[13] , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[12] , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[11] , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[10] , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[9] , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[8] , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[7] , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[6] , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[5] , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[4] , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[3] , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[2] , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[1] , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[0]  } = \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.I4  ? (* src = "top_bit.v:673.5-682.4|../../techmap/cells_formal.v:24.26-24.66" *) 16'hffff : 16'h0000;
  assign { \$auto$simplemap.cc:420:simplemap_dff$1473CLBLL_R_X17Y118_SLICE_X27Y118_A_FDRE.D , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s1[0] , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s2[1] , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s2[0] , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s3[3] , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s3[2] , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s3[1] , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s3[0]  } = \$auto$simplemap.cc:420:simplemap_dff$1471CLBLL_R_X17Y118_SLICE_X27Y118_D_FDRE._TECHMAP_REPLACE_.Q  ? (* src = "top_bit.v:673.5-682.4|../../techmap/cells_formal.v:25.26-25.66" *) { \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[15] , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[14] , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[13] , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[12] , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[11] , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[10] , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[9] , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[8]  } : { \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[7] , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[6] , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[5] , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[4] , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[3] , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[2] , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[1] , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.lower_s4[0]  };
  assign { \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.O6 , \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.upper_s1[0]  } = \$auto$simplemap.cc:420:simplemap_dff$1472CLBLL_R_X17Y118_SLICE_X27Y118_C_FDRE._TECHMAP_REPLACE_.Q  ? (* src = "top_bit.v:658.5-667.4|../../techmap/cells_formal.v:20.26-20.66" *) 2'h3 : 2'h0;
  assign { \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.lower_s2[3] , \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.lower_s2[2] , \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.lower_s2[1] , \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.lower_s2[0] , \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.lower_s3[3] , \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.lower_s3[2] , \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.lower_s3[1] , \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.lower_s3[0] , \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.lower_s4[7] , \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.lower_s4[6] , \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.lower_s4[5] , \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.lower_s4[4] , \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.lower_s4[3] , \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.lower_s4[2] , \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.lower_s4[1] , \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.lower_s4[0]  } = \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.I4  ? (* src = "top_bit.v:658.5-667.4|../../techmap/cells_formal.v:24.26-24.66" *) 16'hffff : 16'h0000;
  assign { \$auto$simplemap.cc:420:simplemap_dff$1474CLBLL_R_X17Y118_SLICE_X27Y118_B_FDRE.D , \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.lower_s1[0]  } = \$auto$simplemap.cc:420:simplemap_dff$1472CLBLL_R_X17Y118_SLICE_X27Y118_C_FDRE._TECHMAP_REPLACE_.Q  ? (* src = "top_bit.v:658.5-667.4|../../techmap/cells_formal.v:27.26-27.66" *) { \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.lower_s2[3] , \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.lower_s2[2]  } : { \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.lower_s2[1] , \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.lower_s2[0]  };
  assign \CLBLL_R_X17Y118_SLICE_X27Y118_CARRY4.CO[0]  = \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.O6  ? (* src = "top_bit.v:615.5-622.4|../../techmap/cells_formal.v:63.18-63.44" *) 1'h0 : 1'h1;
  assign \CLBLL_R_X17Y118_SLICE_X27Y118_CARRY4.CO[1]  = \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.O6  ? (* src = "top_bit.v:615.5-622.4|../../techmap/cells_formal.v:64.18-64.38" *) \CLBLL_R_X17Y118_SLICE_X27Y118_CARRY4.CO[0]  : 1'h0;
  assign \CLBLL_R_X17Y118_SLICE_X27Y118_CARRY4.CO[2]  = \CLBLL_R_X17Y118_SLICE_X27Y118_CARRY4.S[2]  ? (* src = "top_bit.v:615.5-622.4|../../techmap/cells_formal.v:65.18-65.38" *) \CLBLL_R_X17Y118_SLICE_X27Y118_CARRY4.CO[1]  : 1'h0;
  assign \CLBLL_R_X17Y119_SLICE_X27Y119_CARRY4.CI  = \CLBLL_R_X17Y118_SLICE_X27Y118_CARRY4.S[3]  ? (* src = "top_bit.v:615.5-622.4|../../techmap/cells_formal.v:66.18-66.38" *) \CLBLL_R_X17Y118_SLICE_X27Y118_CARRY4.CO[2]  : 1'h0;
  assign { \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.I4 , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.I4 , \CLBLL_R_X17Y118_SLICE_X27Y118_CARRY4.O[1] , \CLBLL_R_X17Y118_SLICE_X27Y118_CARRY4.O[0]  } = { \CLBLL_R_X17Y118_SLICE_X27Y118_CARRY4.S[3] , \CLBLL_R_X17Y118_SLICE_X27Y118_CARRY4.S[2] , \CLBLL_R_X17Y118_SLICE_X27Y118_BLUT.O6 , \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.O6  } ^ (* src = "top_bit.v:615.5-622.4|../../techmap/cells_formal.v:62.14-62.40" *) { \CLBLL_R_X17Y118_SLICE_X27Y118_CARRY4.CO[2] , \CLBLL_R_X17Y118_SLICE_X27Y118_CARRY4.CO[1] , \CLBLL_R_X17Y118_SLICE_X27Y118_CARRY4.CO[0] , 1'h0 };
  assign \CLBLL_R_X17Y118_SLICE_X27Y118_CARRY4.S[2]  = \$auto$simplemap.cc:420:simplemap_dff$1473CLBLL_R_X17Y118_SLICE_X27Y118_A_FDRE._TECHMAP_REPLACE_.Q  ? (* src = "top_bit.v:643.5-652.4|../../techmap/cells_formal.v:21.26-21.66" *) 1'h1 : 1'h0;
  assign { \CLBLL_R_X17Y118_SLICE_X27Y118_CLUT.lower_s1[1] , \CLBLL_R_X17Y118_SLICE_X27Y118_CLUT.lower_s1[0]  } = \CLBLL_R_X17Y118_SLICE_X27Y118_CARRY4.O[1]  ? (* src = "top_bit.v:643.5-652.4|../../techmap/cells_formal.v:27.26-27.66" *) 2'h3 : 2'h0;
  assign \$auto$simplemap.cc:420:simplemap_dff$1472CLBLL_R_X17Y118_SLICE_X27Y118_C_FDRE.D  = \$auto$simplemap.cc:420:simplemap_dff$1473CLBLL_R_X17Y118_SLICE_X27Y118_A_FDRE._TECHMAP_REPLACE_.Q  ? (* src = "top_bit.v:643.5-652.4|../../techmap/cells_formal.v:28.26-28.66" *) \CLBLL_R_X17Y118_SLICE_X27Y118_CLUT.lower_s1[1]  : \CLBLL_R_X17Y118_SLICE_X27Y118_CLUT.lower_s1[0] ;
  assign { \CLBLL_R_X17Y118_SLICE_X27Y118_DLUT.upper_s1[1] , \CLBLL_R_X17Y118_SLICE_X27Y118_DLUT.upper_s1[0] , \CLBLL_R_X17Y118_SLICE_X27Y118_DLUT.upper_s2[1] , \CLBLL_R_X17Y118_SLICE_X27Y118_DLUT.upper_s2[0] , \CLBLL_R_X17Y118_SLICE_X27Y118_DLUT.upper_s3[3] , \CLBLL_R_X17Y118_SLICE_X27Y118_DLUT.upper_s3[2] , \CLBLL_R_X17Y118_SLICE_X27Y118_DLUT.upper_s3[1] , \CLBLL_R_X17Y118_SLICE_X27Y118_DLUT.upper_s3[0] , \CLBLL_R_X17Y118_SLICE_X27Y118_DLUT.upper_s4[7] , \CLBLL_R_X17Y118_SLICE_X27Y118_DLUT.upper_s4[6] , \CLBLL_R_X17Y118_SLICE_X27Y118_DLUT.upper_s4[5] , \CLBLL_R_X17Y118_SLICE_X27Y118_DLUT.upper_s4[4] , \CLBLL_R_X17Y118_SLICE_X27Y118_DLUT.upper_s4[3] , \CLBLL_R_X17Y118_SLICE_X27Y118_DLUT.upper_s4[2] , \CLBLL_R_X17Y118_SLICE_X27Y118_DLUT.upper_s4[1] , \CLBLL_R_X17Y118_SLICE_X27Y118_DLUT.upper_s4[0]  } = \$auto$simplemap.cc:420:simplemap_dff$1474CLBLL_R_X17Y118_SLICE_X27Y118_B_FDRE._TECHMAP_REPLACE_.Q  ? (* src = "top_bit.v:628.5-637.4|../../techmap/cells_formal.v:17.26-17.66" *) 16'hffff : 16'h0000;
  assign \CLBLL_R_X17Y118_SLICE_X27Y118_CARRY4.S[3]  = \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.O6  ? (* src = "top_bit.v:628.5-637.4|../../techmap/cells_formal.v:21.26-21.66" *) \CLBLL_R_X17Y118_SLICE_X27Y118_DLUT.upper_s1[1]  : \CLBLL_R_X17Y118_SLICE_X27Y118_DLUT.upper_s1[0] ;
  assign \$auto$simplemap.cc:420:simplemap_dff$1471CLBLL_R_X17Y118_SLICE_X27Y118_D_FDRE.D  = \CLBLL_R_X17Y118_SLICE_X27Y118_ALUT.O6  ? (* src = "top_bit.v:628.5-637.4|../../techmap/cells_formal.v:28.26-28.66" *) 1'h1 : 1'h0;
  assign { \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.O6 , \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.upper_s1[0]  } = \$auto$simplemap.cc:420:simplemap_dff$1475CLBLL_R_X17Y119_SLICE_X27Y119_C_FDRE._TECHMAP_REPLACE_.Q  ? (* src = "top_bit.v:857.5-866.4|../../techmap/cells_formal.v:20.26-20.66" *) 2'h3 : 2'h0;
  assign { \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.lower_s2[3] , \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.lower_s2[2] , \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.lower_s2[1] , \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.lower_s2[0] , \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.lower_s3[3] , \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.lower_s3[2] , \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.lower_s3[1] , \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.lower_s3[0] , \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.lower_s4[7] , \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.lower_s4[6] , \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.lower_s4[5] , \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.lower_s4[4] , \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.lower_s4[3] , \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.lower_s4[2] , \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.lower_s4[1] , \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.lower_s4[0]  } = \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.I4  ? (* src = "top_bit.v:857.5-866.4|../../techmap/cells_formal.v:24.26-24.66" *) 16'hffff : 16'h0000;
  assign { \$auto$simplemap.cc:420:simplemap_dff$1477CLBLL_R_X17Y119_SLICE_X27Y119_A_FDRE.D , \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.lower_s1[0]  } = \$auto$simplemap.cc:420:simplemap_dff$1475CLBLL_R_X17Y119_SLICE_X27Y119_C_FDRE._TECHMAP_REPLACE_.Q  ? (* src = "top_bit.v:857.5-866.4|../../techmap/cells_formal.v:27.26-27.66" *) { \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.lower_s2[3] , \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.lower_s2[2]  } : { \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.lower_s2[1] , \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.lower_s2[0]  };
  assign { \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.O6 , \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.upper_s1[0]  } = \$auto$simplemap.cc:420:simplemap_dff$1476CLBLL_R_X17Y119_SLICE_X27Y119_D_FDRE._TECHMAP_REPLACE_.Q  ? (* src = "top_bit.v:842.5-851.4|../../techmap/cells_formal.v:20.26-20.66" *) 2'h3 : 2'h0;
  assign { \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.lower_s2[3] , \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.lower_s2[2] , \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.lower_s2[1] , \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.lower_s2[0] , \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.lower_s3[3] , \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.lower_s3[2] , \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.lower_s3[1] , \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.lower_s3[0] , \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.lower_s4[7] , \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.lower_s4[6] , \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.lower_s4[5] , \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.lower_s4[4] , \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.lower_s4[3] , \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.lower_s4[2] , \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.lower_s4[1] , \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.lower_s4[0]  } = \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.I4  ? (* src = "top_bit.v:842.5-851.4|../../techmap/cells_formal.v:24.26-24.66" *) 16'hffff : 16'h0000;
  assign { \$auto$simplemap.cc:420:simplemap_dff$1478CLBLL_R_X17Y119_SLICE_X27Y119_B_FDRE.D , \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.lower_s1[0]  } = \$auto$simplemap.cc:420:simplemap_dff$1476CLBLL_R_X17Y119_SLICE_X27Y119_D_FDRE._TECHMAP_REPLACE_.Q  ? (* src = "top_bit.v:842.5-851.4|../../techmap/cells_formal.v:27.26-27.66" *) { \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.lower_s2[3] , \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.lower_s2[2]  } : { \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.lower_s2[1] , \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.lower_s2[0]  };
  assign \CLBLL_R_X17Y119_SLICE_X27Y119_CARRY4.CO[0]  = \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.O6  ? (* src = "top_bit.v:799.5-806.4|../../techmap/cells_formal.v:63.18-63.44" *) \CLBLL_R_X17Y119_SLICE_X27Y119_CARRY4.CI  : 1'h0;
  assign \CLBLL_R_X17Y119_SLICE_X27Y119_CARRY4.CO[1]  = \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.O6  ? (* src = "top_bit.v:799.5-806.4|../../techmap/cells_formal.v:64.18-64.38" *) \CLBLL_R_X17Y119_SLICE_X27Y119_CARRY4.CO[0]  : 1'h0;
  assign \CLBLL_R_X17Y119_SLICE_X27Y119_CARRY4.CO[2]  = \CLBLL_R_X17Y119_SLICE_X27Y119_CARRY4.S[2]  ? (* src = "top_bit.v:799.5-806.4|../../techmap/cells_formal.v:65.18-65.38" *) \CLBLL_R_X17Y119_SLICE_X27Y119_CARRY4.CO[1]  : 1'h0;
  assign \CLBLL_R_X17Y120_SLICE_X27Y120_CARRY4.CI  = \CLBLL_R_X17Y119_SLICE_X27Y119_CARRY4.S[3]  ? (* src = "top_bit.v:799.5-806.4|../../techmap/cells_formal.v:66.18-66.38" *) \CLBLL_R_X17Y119_SLICE_X27Y119_CARRY4.CO[2]  : 1'h0;
  assign { \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.I4 , \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.I4 , \CLBLL_R_X17Y119_SLICE_X27Y119_CARRY4.O[1] , \CLBLL_R_X17Y119_SLICE_X27Y119_CARRY4.O[0]  } = { \CLBLL_R_X17Y119_SLICE_X27Y119_CARRY4.S[3] , \CLBLL_R_X17Y119_SLICE_X27Y119_CARRY4.S[2] , \CLBLL_R_X17Y119_SLICE_X27Y119_BLUT.O6 , \CLBLL_R_X17Y119_SLICE_X27Y119_ALUT.O6  } ^ (* src = "top_bit.v:799.5-806.4|../../techmap/cells_formal.v:62.14-62.40" *) { \CLBLL_R_X17Y119_SLICE_X27Y119_CARRY4.CO[2] , \CLBLL_R_X17Y119_SLICE_X27Y119_CARRY4.CO[1] , \CLBLL_R_X17Y119_SLICE_X27Y119_CARRY4.CO[0] , \CLBLL_R_X17Y119_SLICE_X27Y119_CARRY4.CI  };
  assign { \CLBLL_R_X17Y119_SLICE_X27Y119_CLUT.upper_s2[3] , \CLBLL_R_X17Y119_SLICE_X27Y119_CLUT.upper_s2[2] , \CLBLL_R_X17Y119_SLICE_X27Y119_CLUT.upper_s2[1] , \CLBLL_R_X17Y119_SLICE_X27Y119_CLUT.upper_s2[0]  } = \$auto$simplemap.cc:420:simplemap_dff$1477CLBLL_R_X17Y119_SLICE_X27Y119_A_FDRE._TECHMAP_REPLACE_.Q  ? (* src = "top_bit.v:827.5-836.4|../../techmap/cells_formal.v:19.26-19.66" *) 4'hf : 4'h0;
  assign { \CLBLL_R_X17Y119_SLICE_X27Y119_CARRY4.S[2] , \CLBLL_R_X17Y119_SLICE_X27Y119_CLUT.upper_s1[0]  } = \CLBLL_R_X17Y119_SLICE_X27Y119_CARRY4.O[0]  ? (* src = "top_bit.v:827.5-836.4|../../techmap/cells_formal.v:20.26-20.66" *) { \CLBLL_R_X17Y119_SLICE_X27Y119_CLUT.upper_s2[3] , \CLBLL_R_X17Y119_SLICE_X27Y119_CLUT.upper_s2[2]  } : { \CLBLL_R_X17Y119_SLICE_X27Y119_CLUT.upper_s2[1] , \CLBLL_R_X17Y119_SLICE_X27Y119_CLUT.upper_s2[0]  };
  assign { \$auto$simplemap.cc:420:simplemap_dff$1475CLBLL_R_X17Y119_SLICE_X27Y119_C_FDRE.D , \CLBLL_R_X17Y119_SLICE_X27Y119_CLUT.lower_s1[0]  } = \CLBLL_R_X17Y119_SLICE_X27Y119_CARRY4.O[0]  ? (* src = "top_bit.v:827.5-836.4|../../techmap/cells_formal.v:27.26-27.66" *) 2'h3 : 2'h0;
  assign { \CLBLL_R_X17Y119_SLICE_X27Y119_DLUT.upper_s1[1] , \CLBLL_R_X17Y119_SLICE_X27Y119_DLUT.upper_s1[0] , \CLBLL_R_X17Y119_SLICE_X27Y119_DLUT.upper_s2[1] , \CLBLL_R_X17Y119_SLICE_X27Y119_DLUT.upper_s2[0] , \CLBLL_R_X17Y119_SLICE_X27Y119_DLUT.upper_s3[3] , \CLBLL_R_X17Y119_SLICE_X27Y119_DLUT.upper_s3[2] , \CLBLL_R_X17Y119_SLICE_X27Y119_DLUT.upper_s3[1] , \CLBLL_R_X17Y119_SLICE_X27Y119_DLUT.upper_s3[0] , \CLBLL_R_X17Y119_SLICE_X27Y119_DLUT.upper_s4[7] , \CLBLL_R_X17Y119_SLICE_X27Y119_DLUT.upper_s4[6] , \CLBLL_R_X17Y119_SLICE_X27Y119_DLUT.upper_s4[5] , \CLBLL_R_X17Y119_SLICE_X27Y119_DLUT.upper_s4[4] , \CLBLL_R_X17Y119_SLICE_X27Y119_DLUT.upper_s4[3] , \CLBLL_R_X17Y119_SLICE_X27Y119_DLUT.upper_s4[2] , \CLBLL_R_X17Y119_SLICE_X27Y119_DLUT.upper_s4[1] , \CLBLL_R_X17Y119_SLICE_X27Y119_DLUT.upper_s4[0]  } = \$auto$simplemap.cc:420:simplemap_dff$1478CLBLL_R_X17Y119_SLICE_X27Y119_B_FDRE._TECHMAP_REPLACE_.Q  ? (* src = "top_bit.v:812.5-821.4|../../techmap/cells_formal.v:17.26-17.66" *) 16'hffff : 16'h0000;
  assign \CLBLL_R_X17Y119_SLICE_X27Y119_CARRY4.S[3]  = \CLBLL_R_X17Y119_SLICE_X27Y119_CARRY4.O[1]  ? (* src = "top_bit.v:812.5-821.4|../../techmap/cells_formal.v:21.26-21.66" *) \CLBLL_R_X17Y119_SLICE_X27Y119_DLUT.upper_s1[1]  : \CLBLL_R_X17Y119_SLICE_X27Y119_DLUT.upper_s1[0] ;
  assign \$auto$simplemap.cc:420:simplemap_dff$1476CLBLL_R_X17Y119_SLICE_X27Y119_D_FDRE.D  = \CLBLL_R_X17Y119_SLICE_X27Y119_CARRY4.O[1]  ? (* src = "top_bit.v:812.5-821.4|../../techmap/cells_formal.v:28.26-28.66" *) 1'h1 : 1'h0;
  assign { \CLBLL_R_X17Y120_SLICE_X27Y120_ALUT.O6 , \CLBLL_R_X17Y120_SLICE_X27Y120_ALUT.upper_s1[0]  } = \led[0]  ? (* src = "top_bit.v:1041.5-1050.4|../../techmap/cells_formal.v:20.26-20.66" *) 2'h3 : 2'h0;
  (* src = "top_bit.v:933.5-939.4|../../techmap/cells_sim.v:17.11-17.69|../../techmap/cells_map.v:48.3-48.67" *)
  always @(posedge clk)
    \led[0]  <= \CLBLL_R_X17Y120_SLICE_X27Y120_A_FDRE.D ;
  assign { \CLBLL_R_X17Y120_SLICE_X27Y120_BLUT.O6 , \CLBLL_R_X17Y120_SLICE_X27Y120_BLUT.upper_s1[0]  } = \led[1]  ? (* src = "top_bit.v:1026.5-1035.4|../../techmap/cells_formal.v:20.26-20.66" *) 2'h3 : 2'h0;
  assign { \CLBLL_R_X17Y120_SLICE_X27Y120_BLUT.lower_s2[3] , \CLBLL_R_X17Y120_SLICE_X27Y120_BLUT.lower_s2[2] , \CLBLL_R_X17Y120_SLICE_X27Y120_BLUT.lower_s2[1] , \CLBLL_R_X17Y120_SLICE_X27Y120_BLUT.lower_s2[0] , \CLBLL_R_X17Y120_SLICE_X27Y120_BLUT.lower_s3[3] , \CLBLL_R_X17Y120_SLICE_X27Y120_BLUT.lower_s3[2] , \CLBLL_R_X17Y120_SLICE_X27Y120_BLUT.lower_s3[1] , \CLBLL_R_X17Y120_SLICE_X27Y120_BLUT.lower_s3[0]  } = \CLBLL_R_X17Y120_SLICE_X27Y120_BLUT.I3  ? (* src = "top_bit.v:1026.5-1035.4|../../techmap/cells_formal.v:25.26-25.66" *) 8'hff : 8'h00;
  assign { \CLBLL_R_X17Y120_SLICE_X27Y120_BLUT.O5 , \CLBLL_R_X17Y120_SLICE_X27Y120_BLUT.lower_s1[0]  } = \led[1]  ? (* src = "top_bit.v:1026.5-1035.4|../../techmap/cells_formal.v:27.26-27.66" *) { \CLBLL_R_X17Y120_SLICE_X27Y120_BLUT.lower_s2[3] , \CLBLL_R_X17Y120_SLICE_X27Y120_BLUT.lower_s2[2]  } : { \CLBLL_R_X17Y120_SLICE_X27Y120_BLUT.lower_s2[1] , \CLBLL_R_X17Y120_SLICE_X27Y120_BLUT.lower_s2[0]  };
  (* src = "top_bit.v:946.5-952.4|../../techmap/cells_sim.v:17.11-17.69|../../techmap/cells_map.v:48.3-48.67" *)
  always @(posedge clk)
    \led[2]  <= \CLBLL_R_X17Y120_SLICE_X27Y120_BLUT.O5 ;
  assign \CLBLL_R_X17Y120_SLICE_X27Y120_CARRY4.CO[0]  = \CLBLL_R_X17Y120_SLICE_X27Y120_ALUT.O6  ? (* src = "top_bit.v:983.5-990.4|../../techmap/cells_formal.v:63.18-63.44" *) \CLBLL_R_X17Y120_SLICE_X27Y120_CARRY4.CI  : 1'h0;
  assign \CLBLL_R_X17Y120_SLICE_X27Y120_CARRY4.CO[1]  = \CLBLL_R_X17Y120_SLICE_X27Y120_BLUT.O6  ? (* src = "top_bit.v:983.5-990.4|../../techmap/cells_formal.v:64.18-64.38" *) \CLBLL_R_X17Y120_SLICE_X27Y120_CARRY4.CO[0]  : 1'h0;
  assign \CLBLL_R_X17Y120_SLICE_X27Y120_CARRY4.CO[2]  = \CLBLL_R_X17Y120_SLICE_X27Y120_CARRY4.S[2]  ? (* src = "top_bit.v:983.5-990.4|../../techmap/cells_formal.v:65.18-65.38" *) \CLBLL_R_X17Y120_SLICE_X27Y120_CARRY4.CO[1]  : 1'h0;
  assign \CLBLL_R_X17Y121_SLICE_X27Y121_CARRY4.CI  = \CLBLL_R_X17Y120_SLICE_X27Y120_CARRY4.S[3]  ? (* src = "top_bit.v:983.5-990.4|../../techmap/cells_formal.v:66.18-66.38" *) \CLBLL_R_X17Y120_SLICE_X27Y120_CARRY4.CO[2]  : 1'h0;
  assign { \CLBLL_R_X17Y120_SLICE_X27Y120_CARRY4.O[3] , \CLBLL_R_X17Y120_SLICE_X27Y120_BLUT.I3 , \CLBLL_R_X17Y120_SLICE_X27Y120_CARRY4.O[1] , \CLBLL_R_X17Y120_SLICE_X27Y120_A_FDRE.D  } = { \CLBLL_R_X17Y120_SLICE_X27Y120_CARRY4.S[3] , \CLBLL_R_X17Y120_SLICE_X27Y120_CARRY4.S[2] , \CLBLL_R_X17Y120_SLICE_X27Y120_BLUT.O6 , \CLBLL_R_X17Y120_SLICE_X27Y120_ALUT.O6  } ^ (* src = "top_bit.v:983.5-990.4|../../techmap/cells_formal.v:62.14-62.40" *) { \CLBLL_R_X17Y120_SLICE_X27Y120_CARRY4.CO[2] , \CLBLL_R_X17Y120_SLICE_X27Y120_CARRY4.CO[1] , \CLBLL_R_X17Y120_SLICE_X27Y120_CARRY4.CO[0] , \CLBLL_R_X17Y120_SLICE_X27Y120_CARRY4.CI  };
  assign { \CLBLL_R_X17Y120_SLICE_X27Y120_CLUT.upper_s1[1] , \CLBLL_R_X17Y120_SLICE_X27Y120_CLUT.upper_s1[0]  } = \led[2]  ? (* src = "top_bit.v:1011.5-1020.4|../../techmap/cells_formal.v:20.26-20.66" *) 2'h3 : 2'h0;
  assign \CLBLL_R_X17Y120_SLICE_X27Y120_CARRY4.S[2]  = \CLBLL_R_X17Y120_SLICE_X27Y120_CARRY4.O[3]  ? (* src = "top_bit.v:1011.5-1020.4|../../techmap/cells_formal.v:21.26-21.66" *) \CLBLL_R_X17Y120_SLICE_X27Y120_CLUT.upper_s1[1]  : \CLBLL_R_X17Y120_SLICE_X27Y120_CLUT.upper_s1[0] ;
  assign \CLBLL_R_X17Y120_SLICE_X27Y120_CLUT.O5  = \CLBLL_R_X17Y120_SLICE_X27Y120_CARRY4.O[3]  ? (* src = "top_bit.v:1011.5-1020.4|../../techmap/cells_formal.v:28.26-28.66" *) 1'h1 : 1'h0;
  (* src = "top_bit.v:959.5-965.4|../../techmap/cells_sim.v:17.11-17.69|../../techmap/cells_map.v:48.3-48.67" *)
  always @(posedge clk)
    \led[3]  <= \CLBLL_R_X17Y120_SLICE_X27Y120_CLUT.O5 ;
  assign { \CLBLL_R_X17Y120_SLICE_X27Y120_CARRY4.S[3] , \CLBLL_R_X17Y120_SLICE_X27Y120_DLUT.upper_s1[0] , \CLBLL_R_X17Y120_SLICE_X27Y120_DLUT.upper_s2[1] , \CLBLL_R_X17Y120_SLICE_X27Y120_DLUT.upper_s2[0]  } = \led[3]  ? (* src = "top_bit.v:996.5-1005.4|../../techmap/cells_formal.v:19.26-19.66" *) 4'hf : 4'h0;
  assign { \CLBLL_R_X17Y120_SLICE_X27Y120_DLUT.lower_s3[7] , \CLBLL_R_X17Y120_SLICE_X27Y120_DLUT.lower_s3[6] , \CLBLL_R_X17Y120_SLICE_X27Y120_DLUT.lower_s3[5] , \CLBLL_R_X17Y120_SLICE_X27Y120_DLUT.lower_s3[4] , \CLBLL_R_X17Y120_SLICE_X27Y120_DLUT.lower_s3[3] , \CLBLL_R_X17Y120_SLICE_X27Y120_DLUT.lower_s3[2] , \CLBLL_R_X17Y120_SLICE_X27Y120_DLUT.lower_s3[1] , \CLBLL_R_X17Y120_SLICE_X27Y120_DLUT.lower_s3[0]  } = \CLBLL_R_X17Y120_SLICE_X27Y120_CARRY4.O[1]  ? (* src = "top_bit.v:996.5-1005.4|../../techmap/cells_formal.v:25.26-25.66" *) 8'hff : 8'h00;
  assign { \CLBLL_R_X17Y120_SLICE_X27Y120_DLUT.O5 , \CLBLL_R_X17Y120_SLICE_X27Y120_DLUT.lower_s1[0] , \CLBLL_R_X17Y120_SLICE_X27Y120_DLUT.lower_s2[1] , \CLBLL_R_X17Y120_SLICE_X27Y120_DLUT.lower_s2[0]  } = \led[3]  ? (* src = "top_bit.v:996.5-1005.4|../../techmap/cells_formal.v:26.26-26.66" *) { \CLBLL_R_X17Y120_SLICE_X27Y120_DLUT.lower_s3[7] , \CLBLL_R_X17Y120_SLICE_X27Y120_DLUT.lower_s3[6] , \CLBLL_R_X17Y120_SLICE_X27Y120_DLUT.lower_s3[5] , \CLBLL_R_X17Y120_SLICE_X27Y120_DLUT.lower_s3[4]  } : { \CLBLL_R_X17Y120_SLICE_X27Y120_DLUT.lower_s3[3] , \CLBLL_R_X17Y120_SLICE_X27Y120_DLUT.lower_s3[2] , \CLBLL_R_X17Y120_SLICE_X27Y120_DLUT.lower_s3[1] , \CLBLL_R_X17Y120_SLICE_X27Y120_DLUT.lower_s3[0]  };
  (* src = "top_bit.v:972.5-978.4|../../techmap/cells_sim.v:17.11-17.69|../../techmap/cells_map.v:48.3-48.67" *)
  always @(posedge clk)
    \led[1]  <= \CLBLL_R_X17Y120_SLICE_X27Y120_DLUT.O5 ;
  assign { \CLBLL_R_X17Y121_SLICE_X27Y121_ALUT.O6 , \CLBLL_R_X17Y121_SLICE_X27Y121_ALUT.upper_s1[0]  } = \led[4]  ? (* src = "top_bit.v:1225.5-1234.4|../../techmap/cells_formal.v:20.26-20.66" *) 2'h3 : 2'h0;
  (* src = "top_bit.v:1117.5-1123.4|../../techmap/cells_sim.v:17.11-17.69|../../techmap/cells_map.v:48.3-48.67" *)
  always @(posedge clk)
    \led[4]  <= \CLBLL_R_X17Y121_SLICE_X27Y121_A_FDRE.D ;
  assign { \CLBLL_R_X17Y121_SLICE_X27Y121_BLUT.O6 , \CLBLL_R_X17Y121_SLICE_X27Y121_BLUT.upper_s1[0]  } = \led[5]  ? (* src = "top_bit.v:1210.5-1219.4|../../techmap/cells_formal.v:20.26-20.66" *) 2'h3 : 2'h0;
  assign { \CLBLL_R_X17Y121_SLICE_X27Y121_BLUT.lower_s2[3] , \CLBLL_R_X17Y121_SLICE_X27Y121_BLUT.lower_s2[2] , \CLBLL_R_X17Y121_SLICE_X27Y121_BLUT.lower_s2[1] , \CLBLL_R_X17Y121_SLICE_X27Y121_BLUT.lower_s2[0] , \CLBLL_R_X17Y121_SLICE_X27Y121_BLUT.lower_s3[3] , \CLBLL_R_X17Y121_SLICE_X27Y121_BLUT.lower_s3[2] , \CLBLL_R_X17Y121_SLICE_X27Y121_BLUT.lower_s3[1] , \CLBLL_R_X17Y121_SLICE_X27Y121_BLUT.lower_s3[0]  } = \CLBLL_R_X17Y121_SLICE_X27Y121_BLUT.I3  ? (* src = "top_bit.v:1210.5-1219.4|../../techmap/cells_formal.v:25.26-25.66" *) 8'hff : 8'h00;
  assign { \CLBLL_R_X17Y121_SLICE_X27Y121_BLUT.O5 , \CLBLL_R_X17Y121_SLICE_X27Y121_BLUT.lower_s1[0]  } = \led[5]  ? (* src = "top_bit.v:1210.5-1219.4|../../techmap/cells_formal.v:27.26-27.66" *) { \CLBLL_R_X17Y121_SLICE_X27Y121_BLUT.lower_s2[3] , \CLBLL_R_X17Y121_SLICE_X27Y121_BLUT.lower_s2[2]  } : { \CLBLL_R_X17Y121_SLICE_X27Y121_BLUT.lower_s2[1] , \CLBLL_R_X17Y121_SLICE_X27Y121_BLUT.lower_s2[0]  };
  (* src = "top_bit.v:1130.5-1136.4|../../techmap/cells_sim.v:17.11-17.69|../../techmap/cells_map.v:48.3-48.67" *)
  always @(posedge clk)
    \led[6]  <= \CLBLL_R_X17Y121_SLICE_X27Y121_BLUT.O5 ;
  assign \CLBLL_R_X17Y121_SLICE_X27Y121_CARRY4.CO[0]  = \CLBLL_R_X17Y121_SLICE_X27Y121_ALUT.O6  ? (* src = "top_bit.v:1167.5-1174.4|../../techmap/cells_formal.v:63.18-63.44" *) \CLBLL_R_X17Y121_SLICE_X27Y121_CARRY4.CI  : 1'h0;
  assign \CLBLL_R_X17Y121_SLICE_X27Y121_CARRY4.CO[1]  = \CLBLL_R_X17Y121_SLICE_X27Y121_BLUT.O6  ? (* src = "top_bit.v:1167.5-1174.4|../../techmap/cells_formal.v:64.18-64.38" *) \CLBLL_R_X17Y121_SLICE_X27Y121_CARRY4.CO[0]  : 1'h0;
  assign \CLBLL_R_X17Y121_SLICE_X27Y121_CARRY4.CO[2]  = \CLBLL_R_X17Y121_SLICE_X27Y121_CARRY4.S[2]  ? (* src = "top_bit.v:1167.5-1174.4|../../techmap/cells_formal.v:65.18-65.38" *) \CLBLL_R_X17Y121_SLICE_X27Y121_CARRY4.CO[1]  : 1'h0;
  assign { \CLBLL_R_X17Y121_SLICE_X27Y121_CARRY4.O[3] , \CLBLL_R_X17Y121_SLICE_X27Y121_BLUT.I3 , \CLBLL_R_X17Y121_SLICE_X27Y121_CARRY4.O[1] , \CLBLL_R_X17Y121_SLICE_X27Y121_A_FDRE.D  } = { \CLBLL_R_X17Y121_SLICE_X27Y121_CARRY4.S[3] , \CLBLL_R_X17Y121_SLICE_X27Y121_CARRY4.S[2] , \CLBLL_R_X17Y121_SLICE_X27Y121_BLUT.O6 , \CLBLL_R_X17Y121_SLICE_X27Y121_ALUT.O6  } ^ (* src = "top_bit.v:1167.5-1174.4|../../techmap/cells_formal.v:62.14-62.40" *) { \CLBLL_R_X17Y121_SLICE_X27Y121_CARRY4.CO[2] , \CLBLL_R_X17Y121_SLICE_X27Y121_CARRY4.CO[1] , \CLBLL_R_X17Y121_SLICE_X27Y121_CARRY4.CO[0] , \CLBLL_R_X17Y121_SLICE_X27Y121_CARRY4.CI  };
  assign { \CLBLL_R_X17Y121_SLICE_X27Y121_CLUT.upper_s1[1] , \CLBLL_R_X17Y121_SLICE_X27Y121_CLUT.upper_s1[0]  } = \led[6]  ? (* src = "top_bit.v:1195.5-1204.4|../../techmap/cells_formal.v:20.26-20.66" *) 2'h3 : 2'h0;
  assign \CLBLL_R_X17Y121_SLICE_X27Y121_CARRY4.S[2]  = \CLBLL_R_X17Y121_SLICE_X27Y121_CARRY4.O[3]  ? (* src = "top_bit.v:1195.5-1204.4|../../techmap/cells_formal.v:21.26-21.66" *) \CLBLL_R_X17Y121_SLICE_X27Y121_CLUT.upper_s1[1]  : \CLBLL_R_X17Y121_SLICE_X27Y121_CLUT.upper_s1[0] ;
  assign \CLBLL_R_X17Y121_SLICE_X27Y121_CLUT.O5  = \CLBLL_R_X17Y121_SLICE_X27Y121_CARRY4.O[3]  ? (* src = "top_bit.v:1195.5-1204.4|../../techmap/cells_formal.v:28.26-28.66" *) 1'h1 : 1'h0;
  (* src = "top_bit.v:1143.5-1149.4|../../techmap/cells_sim.v:17.11-17.69|../../techmap/cells_map.v:48.3-48.67" *)
  always @(posedge clk)
    \led[7]  <= \CLBLL_R_X17Y121_SLICE_X27Y121_CLUT.O5 ;
  assign { \CLBLL_R_X17Y121_SLICE_X27Y121_CARRY4.S[3] , \CLBLL_R_X17Y121_SLICE_X27Y121_DLUT.upper_s1[0] , \CLBLL_R_X17Y121_SLICE_X27Y121_DLUT.upper_s2[1] , \CLBLL_R_X17Y121_SLICE_X27Y121_DLUT.upper_s2[0]  } = \led[7]  ? (* src = "top_bit.v:1180.5-1189.4|../../techmap/cells_formal.v:19.26-19.66" *) 4'hf : 4'h0;
  assign { \CLBLL_R_X17Y121_SLICE_X27Y121_DLUT.lower_s3[7] , \CLBLL_R_X17Y121_SLICE_X27Y121_DLUT.lower_s3[6] , \CLBLL_R_X17Y121_SLICE_X27Y121_DLUT.lower_s3[5] , \CLBLL_R_X17Y121_SLICE_X27Y121_DLUT.lower_s3[4] , \CLBLL_R_X17Y121_SLICE_X27Y121_DLUT.lower_s3[3] , \CLBLL_R_X17Y121_SLICE_X27Y121_DLUT.lower_s3[2] , \CLBLL_R_X17Y121_SLICE_X27Y121_DLUT.lower_s3[1] , \CLBLL_R_X17Y121_SLICE_X27Y121_DLUT.lower_s3[0]  } = \CLBLL_R_X17Y121_SLICE_X27Y121_CARRY4.O[1]  ? (* src = "top_bit.v:1180.5-1189.4|../../techmap/cells_formal.v:25.26-25.66" *) 8'hff : 8'h00;
  assign { \CLBLL_R_X17Y121_SLICE_X27Y121_DLUT.O5 , \CLBLL_R_X17Y121_SLICE_X27Y121_DLUT.lower_s1[0] , \CLBLL_R_X17Y121_SLICE_X27Y121_DLUT.lower_s2[1] , \CLBLL_R_X17Y121_SLICE_X27Y121_DLUT.lower_s2[0]  } = \led[7]  ? (* src = "top_bit.v:1180.5-1189.4|../../techmap/cells_formal.v:26.26-26.66" *) { \CLBLL_R_X17Y121_SLICE_X27Y121_DLUT.lower_s3[7] , \CLBLL_R_X17Y121_SLICE_X27Y121_DLUT.lower_s3[6] , \CLBLL_R_X17Y121_SLICE_X27Y121_DLUT.lower_s3[5] , \CLBLL_R_X17Y121_SLICE_X27Y121_DLUT.lower_s3[4]  } : { \CLBLL_R_X17Y121_SLICE_X27Y121_DLUT.lower_s3[3] , \CLBLL_R_X17Y121_SLICE_X27Y121_DLUT.lower_s3[2] , \CLBLL_R_X17Y121_SLICE_X27Y121_DLUT.lower_s3[1] , \CLBLL_R_X17Y121_SLICE_X27Y121_DLUT.lower_s3[0]  };
  (* src = "top_bit.v:1156.5-1162.4|../../techmap/cells_sim.v:17.11-17.69|../../techmap/cells_map.v:48.3-48.67" *)
  always @(posedge clk)
    \led[5]  <= \CLBLL_R_X17Y121_SLICE_X27Y121_DLUT.O5 ;
  assign \CLBLL_R_X17Y121_SLICE_X27Y121_C_FDRE._TECHMAP_REPLACE_.Q  = \led[7] ;
  assign \CLBLL_R_X17Y121_SLICE_X27Y121_A_FDRE._TECHMAP_REPLACE_.Q  = \led[4] ;
  assign \CLBLL_R_X17Y120_SLICE_X27Y120_A_FDRE._TECHMAP_REPLACE_.Q  = \led[0] ;
  assign \CLBLL_R_X17Y121_SLICE_X27Y121_D_FDRE._TECHMAP_REPLACE_.Q  = \led[5] ;
  assign \CLBLL_R_X17Y120_SLICE_X27Y120_B_FDRE._TECHMAP_REPLACE_.Q  = \led[2] ;
  assign \CLBLL_R_X17Y120_SLICE_X27Y120_D_FDRE._TECHMAP_REPLACE_.Q  = \led[1] ;
  assign \CLBLL_R_X17Y121_SLICE_X27Y121_B_FDRE._TECHMAP_REPLACE_.Q  = \led[6] ;
  assign \CLBLL_R_X17Y120_SLICE_X27Y120_C_FDRE._TECHMAP_REPLACE_.Q  = \led[3] ;
endmodule
