/* Generated by Yosys 0.9+3885 (git sha1 afcc31ce, clang 11.0.1 -fPIC -Os) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:1.1-18.10" *)
module top(clk, \led[0] , \led[1] , \led[2] , \led[3] , \led[4] , \led[5] , \led[6] , \led[7] , \sw[0] , \sw[1] , \sw[2] , \sw[3] , \sw[4] , \sw[5] , \sw[6] , \sw[7] );
  (* DELAY_CONST_CIN = "0.293e-9" *)
  (* DELAY_CONST_CYINIT = "0.578e-9" *)
  (* DELAY_CONST_DI0 = "0.329e-9" *)
  (* DELAY_CONST_S0 = "0.340e-9" *)
  (* hdlname = "$auto$alumacc.cc:485:replace_alu$1385.slice[0].carry4 CO0" *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:174.11-182.5|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:84.7-101.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8297.7-8314.6|../../techmap/cells_sim.v:122.15-122.18" *)
  wire \$auto$alumacc.cc:485:replace_alu$1385.slice[0].carry4.CO0 ;
  (* DELAY_CONST_CIN = "0.178e-9" *)
  (* DELAY_CONST_CYINIT = "0.529e-9" *)
  (* DELAY_CONST_DI0 = "0.396e-9" *)
  (* DELAY_CONST_DI1 = "0.376e-9" *)
  (* DELAY_CONST_S0 = "0.433e-9" *)
  (* DELAY_CONST_S1 = "0.469e-9" *)
  (* hdlname = "$auto$alumacc.cc:485:replace_alu$1385.slice[0].carry4 CO1" *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:174.11-182.5|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:84.7-101.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8297.7-8314.6|../../techmap/cells_sim.v:130.15-130.18" *)
  wire \$auto$alumacc.cc:485:replace_alu$1385.slice[0].carry4.CO1 ;
  (* DELAY_CONST_CIN = "0.250e-9" *)
  (* DELAY_CONST_CYINIT = "0.617e-9" *)
  (* DELAY_CONST_DI0 = "0.474e-9" *)
  (* DELAY_CONST_DI1 = "0.459e-9" *)
  (* DELAY_CONST_DI2 = "0.289e-9" *)
  (* DELAY_CONST_S0 = "0.512e-9" *)
  (* DELAY_CONST_S1 = "0.548e-9" *)
  (* DELAY_CONST_S2 = "0.292e-9" *)
  (* hdlname = "$auto$alumacc.cc:485:replace_alu$1385.slice[0].carry4 CO2" *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:174.11-182.5|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:84.7-101.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8297.7-8314.6|../../techmap/cells_sim.v:140.15-140.18" *)
  wire \$auto$alumacc.cc:485:replace_alu$1385.slice[0].carry4.CO2 ;
  (* DELAY_CONST_CIN = "0.114e-9" *)
  (* DELAY_CONST_CYINIT = "0.580e-9" *)
  (* DELAY_CONST_DI0 = "0.456e-9" *)
  (* DELAY_CONST_DI1 = "0.443e-9" *)
  (* DELAY_CONST_DI2 = "0.324e-9" *)
  (* DELAY_CONST_DI3 = "0.327e-9" *)
  (* DELAY_CONST_S0 = "0.508e-9" *)
  (* DELAY_CONST_S1 = "0.528e-9" *)
  (* DELAY_CONST_S2 = "0.376e-9" *)
  (* DELAY_CONST_S3 = "0.380e-9" *)
  (* hdlname = "$auto$alumacc.cc:485:replace_alu$1385.slice[0].carry4 CO3" *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:174.11-182.5|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:84.7-101.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8297.7-8314.6|../../techmap/cells_sim.v:152.15-152.18" *)
  wire \$auto$alumacc.cc:485:replace_alu$1385.slice[0].carry4.CO3 ;
  (* DELAY_CONST_CIN = "0.235e-9" *)
  (* DELAY_CONST_CYINIT = "0.491e-9" *)
  (* DELAY_CONST_S0 = "0.223e-9" *)
  (* hdlname = "$auto$alumacc.cc:485:replace_alu$1385.slice[0].carry4 O0" *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:174.11-182.5|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:84.7-101.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8297.7-8314.6|../../techmap/cells_sim.v:89.15-89.17" *)
  wire \$auto$alumacc.cc:485:replace_alu$1385.slice[0].carry4.O0 ;
  (* DELAY_CONST_CIN = "0.348e-9" *)
  (* DELAY_CONST_CYINIT = "0.613e-9" *)
  (* DELAY_CONST_DI0 = "0.337e-9" *)
  (* DELAY_CONST_S0 = "0.400e-9" *)
  (* DELAY_CONST_S1 = "0.205e-9" *)
  (* hdlname = "$auto$alumacc.cc:485:replace_alu$1385.slice[0].carry4 O1" *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:174.11-182.5|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:84.7-101.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8297.7-8314.6|../../techmap/cells_sim.v:96.15-96.17" *)
  wire \$auto$alumacc.cc:485:replace_alu$1385.slice[0].carry4.O1 ;
  (* DELAY_CONST_CIN = "0.256e-9" *)
  (* DELAY_CONST_CYINIT = "0.600e-9" *)
  (* DELAY_CONST_DI0 = "0.486e-9" *)
  (* DELAY_CONST_DI1 = "0.471e-9" *)
  (* DELAY_CONST_S0 = "0.523e-9" *)
  (* DELAY_CONST_S1 = "0.558e-9" *)
  (* DELAY_CONST_S2 = "0.226e-9" *)
  (* hdlname = "$auto$alumacc.cc:485:replace_alu$1385.slice[0].carry4 O2" *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:174.11-182.5|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:84.7-101.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8297.7-8314.6|../../techmap/cells_sim.v:105.15-105.17" *)
  wire \$auto$alumacc.cc:485:replace_alu$1385.slice[0].carry4.O2 ;
  (* DELAY_CONST_CIN = "0.329e-9" *)
  (* DELAY_CONST_CYINIT = "0.657e-9" *)
  (* DELAY_CONST_DI0 = "0.545e-9" *)
  (* DELAY_CONST_DI1 = "0.532e-9" *)
  (* DELAY_CONST_DI2 = "0.372e-9" *)
  (* DELAY_CONST_S0 = "0.582e-9" *)
  (* DELAY_CONST_S1 = "0.618e-9" *)
  (* DELAY_CONST_S2 = "0.330e-9" *)
  (* DELAY_CONST_S3 = "0.227e-9" *)
  (* hdlname = "$auto$alumacc.cc:485:replace_alu$1385.slice[0].carry4 O3" *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:174.11-182.5|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:84.7-101.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8297.7-8314.6|../../techmap/cells_sim.v:116.15-116.17" *)
  wire \$auto$alumacc.cc:485:replace_alu$1385.slice[0].carry4.O3 ;
  (* DELAY_CONST_CIN = "0.293e-9" *)
  (* DELAY_CONST_CYINIT = "0.578e-9" *)
  (* DELAY_CONST_DI0 = "0.329e-9" *)
  (* DELAY_CONST_S0 = "0.340e-9" *)
  (* hdlname = "$auto$alumacc.cc:485:replace_alu$1385.slice[1].carry4 CO0" *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:122.15-122.18" *)
  wire \$auto$alumacc.cc:485:replace_alu$1385.slice[1].carry4.CO0 ;
  (* DELAY_CONST_CIN = "0.178e-9" *)
  (* DELAY_CONST_CYINIT = "0.529e-9" *)
  (* DELAY_CONST_DI0 = "0.396e-9" *)
  (* DELAY_CONST_DI1 = "0.376e-9" *)
  (* DELAY_CONST_S0 = "0.433e-9" *)
  (* DELAY_CONST_S1 = "0.469e-9" *)
  (* hdlname = "$auto$alumacc.cc:485:replace_alu$1385.slice[1].carry4 CO1" *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:130.15-130.18" *)
  wire \$auto$alumacc.cc:485:replace_alu$1385.slice[1].carry4.CO1 ;
  (* DELAY_CONST_CIN = "0.250e-9" *)
  (* DELAY_CONST_CYINIT = "0.617e-9" *)
  (* DELAY_CONST_DI0 = "0.474e-9" *)
  (* DELAY_CONST_DI1 = "0.459e-9" *)
  (* DELAY_CONST_DI2 = "0.289e-9" *)
  (* DELAY_CONST_S0 = "0.512e-9" *)
  (* DELAY_CONST_S1 = "0.548e-9" *)
  (* DELAY_CONST_S2 = "0.292e-9" *)
  (* hdlname = "$auto$alumacc.cc:485:replace_alu$1385.slice[1].carry4 CO2" *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:140.15-140.18" *)
  wire \$auto$alumacc.cc:485:replace_alu$1385.slice[1].carry4.CO2 ;
  (* DELAY_CONST_CIN = "0.114e-9" *)
  (* DELAY_CONST_CYINIT = "0.580e-9" *)
  (* DELAY_CONST_DI0 = "0.456e-9" *)
  (* DELAY_CONST_DI1 = "0.443e-9" *)
  (* DELAY_CONST_DI2 = "0.324e-9" *)
  (* DELAY_CONST_DI3 = "0.327e-9" *)
  (* DELAY_CONST_S0 = "0.508e-9" *)
  (* DELAY_CONST_S1 = "0.528e-9" *)
  (* DELAY_CONST_S2 = "0.376e-9" *)
  (* DELAY_CONST_S3 = "0.380e-9" *)
  (* hdlname = "$auto$alumacc.cc:485:replace_alu$1385.slice[1].carry4 CO3" *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:152.15-152.18" *)
  wire \$auto$alumacc.cc:485:replace_alu$1385.slice[1].carry4.CO3 ;
  (* DELAY_CONST_CIN = "0.235e-9" *)
  (* DELAY_CONST_CYINIT = "0.491e-9" *)
  (* DELAY_CONST_S0 = "0.223e-9" *)
  (* hdlname = "$auto$alumacc.cc:485:replace_alu$1385.slice[1].carry4 O0" *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:89.15-89.17" *)
  wire \$auto$alumacc.cc:485:replace_alu$1385.slice[1].carry4.O0 ;
  (* DELAY_CONST_CIN = "0.348e-9" *)
  (* DELAY_CONST_CYINIT = "0.613e-9" *)
  (* DELAY_CONST_DI0 = "0.337e-9" *)
  (* DELAY_CONST_S0 = "0.400e-9" *)
  (* DELAY_CONST_S1 = "0.205e-9" *)
  (* hdlname = "$auto$alumacc.cc:485:replace_alu$1385.slice[1].carry4 O1" *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:96.15-96.17" *)
  wire \$auto$alumacc.cc:485:replace_alu$1385.slice[1].carry4.O1 ;
  (* DELAY_CONST_CIN = "0.256e-9" *)
  (* DELAY_CONST_CYINIT = "0.600e-9" *)
  (* DELAY_CONST_DI0 = "0.486e-9" *)
  (* DELAY_CONST_DI1 = "0.471e-9" *)
  (* DELAY_CONST_S0 = "0.523e-9" *)
  (* DELAY_CONST_S1 = "0.558e-9" *)
  (* DELAY_CONST_S2 = "0.226e-9" *)
  (* hdlname = "$auto$alumacc.cc:485:replace_alu$1385.slice[1].carry4 O2" *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:105.15-105.17" *)
  wire \$auto$alumacc.cc:485:replace_alu$1385.slice[1].carry4.O2 ;
  (* DELAY_CONST_CIN = "0.329e-9" *)
  (* DELAY_CONST_CYINIT = "0.657e-9" *)
  (* DELAY_CONST_DI0 = "0.545e-9" *)
  (* DELAY_CONST_DI1 = "0.532e-9" *)
  (* DELAY_CONST_DI2 = "0.372e-9" *)
  (* DELAY_CONST_S0 = "0.582e-9" *)
  (* DELAY_CONST_S1 = "0.618e-9" *)
  (* DELAY_CONST_S2 = "0.330e-9" *)
  (* DELAY_CONST_S3 = "0.227e-9" *)
  (* hdlname = "$auto$alumacc.cc:485:replace_alu$1385.slice[1].carry4 O3" *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:116.15-116.17" *)
  wire \$auto$alumacc.cc:485:replace_alu$1385.slice[1].carry4.O3 ;
  (* DELAY_CONST_CIN = "0.293e-9" *)
  (* DELAY_CONST_CYINIT = "0.578e-9" *)
  (* DELAY_CONST_DI0 = "0.329e-9" *)
  (* DELAY_CONST_S0 = "0.340e-9" *)
  (* hdlname = "$auto$alumacc.cc:485:replace_alu$1385.slice[2].carry4 CO0" *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:122.15-122.18" *)
  wire \$auto$alumacc.cc:485:replace_alu$1385.slice[2].carry4.CO0 ;
  (* DELAY_CONST_CIN = "0.178e-9" *)
  (* DELAY_CONST_CYINIT = "0.529e-9" *)
  (* DELAY_CONST_DI0 = "0.396e-9" *)
  (* DELAY_CONST_DI1 = "0.376e-9" *)
  (* DELAY_CONST_S0 = "0.433e-9" *)
  (* DELAY_CONST_S1 = "0.469e-9" *)
  (* hdlname = "$auto$alumacc.cc:485:replace_alu$1385.slice[2].carry4 CO1" *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:130.15-130.18" *)
  wire \$auto$alumacc.cc:485:replace_alu$1385.slice[2].carry4.CO1 ;
  (* DELAY_CONST_CIN = "0.250e-9" *)
  (* DELAY_CONST_CYINIT = "0.617e-9" *)
  (* DELAY_CONST_DI0 = "0.474e-9" *)
  (* DELAY_CONST_DI1 = "0.459e-9" *)
  (* DELAY_CONST_DI2 = "0.289e-9" *)
  (* DELAY_CONST_S0 = "0.512e-9" *)
  (* DELAY_CONST_S1 = "0.548e-9" *)
  (* DELAY_CONST_S2 = "0.292e-9" *)
  (* hdlname = "$auto$alumacc.cc:485:replace_alu$1385.slice[2].carry4 CO2" *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:140.15-140.18" *)
  wire \$auto$alumacc.cc:485:replace_alu$1385.slice[2].carry4.CO2 ;
  (* DELAY_CONST_CIN = "0.114e-9" *)
  (* DELAY_CONST_CYINIT = "0.580e-9" *)
  (* DELAY_CONST_DI0 = "0.456e-9" *)
  (* DELAY_CONST_DI1 = "0.443e-9" *)
  (* DELAY_CONST_DI2 = "0.324e-9" *)
  (* DELAY_CONST_DI3 = "0.327e-9" *)
  (* DELAY_CONST_S0 = "0.508e-9" *)
  (* DELAY_CONST_S1 = "0.528e-9" *)
  (* DELAY_CONST_S2 = "0.376e-9" *)
  (* DELAY_CONST_S3 = "0.380e-9" *)
  (* hdlname = "$auto$alumacc.cc:485:replace_alu$1385.slice[2].carry4 CO3" *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:152.15-152.18" *)
  wire \$auto$alumacc.cc:485:replace_alu$1385.slice[2].carry4.CO3 ;
  (* DELAY_CONST_CIN = "0.235e-9" *)
  (* DELAY_CONST_CYINIT = "0.491e-9" *)
  (* DELAY_CONST_S0 = "0.223e-9" *)
  (* hdlname = "$auto$alumacc.cc:485:replace_alu$1385.slice[2].carry4 O0" *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:89.15-89.17" *)
  wire \$auto$alumacc.cc:485:replace_alu$1385.slice[2].carry4.O0 ;
  (* DELAY_CONST_CIN = "0.348e-9" *)
  (* DELAY_CONST_CYINIT = "0.613e-9" *)
  (* DELAY_CONST_DI0 = "0.337e-9" *)
  (* DELAY_CONST_S0 = "0.400e-9" *)
  (* DELAY_CONST_S1 = "0.205e-9" *)
  (* hdlname = "$auto$alumacc.cc:485:replace_alu$1385.slice[2].carry4 O1" *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:96.15-96.17" *)
  wire \$auto$alumacc.cc:485:replace_alu$1385.slice[2].carry4.O1 ;
  (* DELAY_CONST_CIN = "0.256e-9" *)
  (* DELAY_CONST_CYINIT = "0.600e-9" *)
  (* DELAY_CONST_DI0 = "0.486e-9" *)
  (* DELAY_CONST_DI1 = "0.471e-9" *)
  (* DELAY_CONST_S0 = "0.523e-9" *)
  (* DELAY_CONST_S1 = "0.558e-9" *)
  (* DELAY_CONST_S2 = "0.226e-9" *)
  (* hdlname = "$auto$alumacc.cc:485:replace_alu$1385.slice[2].carry4 O2" *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:105.15-105.17" *)
  wire \$auto$alumacc.cc:485:replace_alu$1385.slice[2].carry4.O2 ;
  (* DELAY_CONST_CIN = "0.329e-9" *)
  (* DELAY_CONST_CYINIT = "0.657e-9" *)
  (* DELAY_CONST_DI0 = "0.545e-9" *)
  (* DELAY_CONST_DI1 = "0.532e-9" *)
  (* DELAY_CONST_DI2 = "0.372e-9" *)
  (* DELAY_CONST_S0 = "0.582e-9" *)
  (* DELAY_CONST_S1 = "0.618e-9" *)
  (* DELAY_CONST_S2 = "0.330e-9" *)
  (* DELAY_CONST_S3 = "0.227e-9" *)
  (* hdlname = "$auto$alumacc.cc:485:replace_alu$1385.slice[2].carry4 O3" *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:116.15-116.17" *)
  wire \$auto$alumacc.cc:485:replace_alu$1385.slice[2].carry4.O3 ;
  (* DELAY_CONST_CIN = "0.293e-9" *)
  (* DELAY_CONST_CYINIT = "0.578e-9" *)
  (* DELAY_CONST_DI0 = "0.329e-9" *)
  (* DELAY_CONST_S0 = "0.340e-9" *)
  (* hdlname = "$auto$alumacc.cc:485:replace_alu$1385.slice[3].carry4 CO0" *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:122.15-122.18" *)
  wire \$auto$alumacc.cc:485:replace_alu$1385.slice[3].carry4.CO0 ;
  (* DELAY_CONST_CIN = "0.178e-9" *)
  (* DELAY_CONST_CYINIT = "0.529e-9" *)
  (* DELAY_CONST_DI0 = "0.396e-9" *)
  (* DELAY_CONST_DI1 = "0.376e-9" *)
  (* DELAY_CONST_S0 = "0.433e-9" *)
  (* DELAY_CONST_S1 = "0.469e-9" *)
  (* hdlname = "$auto$alumacc.cc:485:replace_alu$1385.slice[3].carry4 CO1" *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:130.15-130.18" *)
  wire \$auto$alumacc.cc:485:replace_alu$1385.slice[3].carry4.CO1 ;
  (* DELAY_CONST_CIN = "0.250e-9" *)
  (* DELAY_CONST_CYINIT = "0.617e-9" *)
  (* DELAY_CONST_DI0 = "0.474e-9" *)
  (* DELAY_CONST_DI1 = "0.459e-9" *)
  (* DELAY_CONST_DI2 = "0.289e-9" *)
  (* DELAY_CONST_S0 = "0.512e-9" *)
  (* DELAY_CONST_S1 = "0.548e-9" *)
  (* DELAY_CONST_S2 = "0.292e-9" *)
  (* hdlname = "$auto$alumacc.cc:485:replace_alu$1385.slice[3].carry4 CO2" *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:140.15-140.18" *)
  wire \$auto$alumacc.cc:485:replace_alu$1385.slice[3].carry4.CO2 ;
  (* DELAY_CONST_CIN = "0.235e-9" *)
  (* DELAY_CONST_CYINIT = "0.491e-9" *)
  (* DELAY_CONST_S0 = "0.223e-9" *)
  (* hdlname = "$auto$alumacc.cc:485:replace_alu$1385.slice[3].carry4 O0" *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:89.15-89.17" *)
  wire \$auto$alumacc.cc:485:replace_alu$1385.slice[3].carry4.O0 ;
  (* DELAY_CONST_CIN = "0.348e-9" *)
  (* DELAY_CONST_CYINIT = "0.613e-9" *)
  (* DELAY_CONST_DI0 = "0.337e-9" *)
  (* DELAY_CONST_S0 = "0.400e-9" *)
  (* DELAY_CONST_S1 = "0.205e-9" *)
  (* hdlname = "$auto$alumacc.cc:485:replace_alu$1385.slice[3].carry4 O1" *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:96.15-96.17" *)
  wire \$auto$alumacc.cc:485:replace_alu$1385.slice[3].carry4.O1 ;
  (* DELAY_CONST_CIN = "0.256e-9" *)
  (* DELAY_CONST_CYINIT = "0.600e-9" *)
  (* DELAY_CONST_DI0 = "0.486e-9" *)
  (* DELAY_CONST_DI1 = "0.471e-9" *)
  (* DELAY_CONST_S0 = "0.523e-9" *)
  (* DELAY_CONST_S1 = "0.558e-9" *)
  (* DELAY_CONST_S2 = "0.226e-9" *)
  (* hdlname = "$auto$alumacc.cc:485:replace_alu$1385.slice[3].carry4 O2" *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:105.15-105.17" *)
  wire \$auto$alumacc.cc:485:replace_alu$1385.slice[3].carry4.O2 ;
  (* DELAY_CONST_CIN = "0.329e-9" *)
  (* DELAY_CONST_CYINIT = "0.657e-9" *)
  (* DELAY_CONST_DI0 = "0.545e-9" *)
  (* DELAY_CONST_DI1 = "0.532e-9" *)
  (* DELAY_CONST_DI2 = "0.372e-9" *)
  (* DELAY_CONST_S0 = "0.582e-9" *)
  (* DELAY_CONST_S1 = "0.618e-9" *)
  (* DELAY_CONST_S2 = "0.330e-9" *)
  (* DELAY_CONST_S3 = "0.227e-9" *)
  (* hdlname = "$auto$alumacc.cc:485:replace_alu$1385.slice[3].carry4 O3" *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:116.15-116.17" *)
  wire \$auto$alumacc.cc:485:replace_alu$1385.slice[3].carry4.O3 ;
  (* hdlname = "$auto$simplemap.cc:420:simplemap_dff$1471 Q" *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67|../../techmap/cells_sim.v:12.30-12.31" *)
  reg \$auto$simplemap.cc:420:simplemap_dff$1471.Q  = 1'h0;
  (* hdlname = "$auto$simplemap.cc:420:simplemap_dff$1472 Q" *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67|../../techmap/cells_sim.v:12.30-12.31" *)
  reg \$auto$simplemap.cc:420:simplemap_dff$1472.Q  = 1'h0;
  (* hdlname = "$auto$simplemap.cc:420:simplemap_dff$1473 Q" *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67|../../techmap/cells_sim.v:12.30-12.31" *)
  reg \$auto$simplemap.cc:420:simplemap_dff$1473.Q  = 1'h0;
  (* hdlname = "$auto$simplemap.cc:420:simplemap_dff$1474 Q" *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67|../../techmap/cells_sim.v:12.30-12.31" *)
  reg \$auto$simplemap.cc:420:simplemap_dff$1474.Q  = 1'h0;
  (* hdlname = "$auto$simplemap.cc:420:simplemap_dff$1475 Q" *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67|../../techmap/cells_sim.v:12.30-12.31" *)
  reg \$auto$simplemap.cc:420:simplemap_dff$1475.Q  = 1'h0;
  (* hdlname = "$auto$simplemap.cc:420:simplemap_dff$1476 Q" *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67|../../techmap/cells_sim.v:12.30-12.31" *)
  reg \$auto$simplemap.cc:420:simplemap_dff$1476.Q  = 1'h0;
  (* hdlname = "$auto$simplemap.cc:420:simplemap_dff$1477 Q" *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67|../../techmap/cells_sim.v:12.30-12.31" *)
  reg \$auto$simplemap.cc:420:simplemap_dff$1477.Q  = 1'h0;
  (* hdlname = "$auto$simplemap.cc:420:simplemap_dff$1478 Q" *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67|../../techmap/cells_sim.v:12.30-12.31" *)
  reg \$auto$simplemap.cc:420:simplemap_dff$1478.Q  = 1'h0;
  (* hdlname = "$auto$simplemap.cc:420:simplemap_dff$1479 Q" *)
  (* init = 1'h0 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67|../../techmap/cells_sim.v:12.30-12.31" *)
  wire \$auto$simplemap.cc:420:simplemap_dff$1479.Q ;
  (* hdlname = "$auto$simplemap.cc:420:simplemap_dff$1480 Q" *)
  (* init = 1'h0 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67|../../techmap/cells_sim.v:12.30-12.31" *)
  wire \$auto$simplemap.cc:420:simplemap_dff$1480.Q ;
  (* hdlname = "$auto$simplemap.cc:420:simplemap_dff$1481 Q" *)
  (* init = 1'h0 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67|../../techmap/cells_sim.v:12.30-12.31" *)
  wire \$auto$simplemap.cc:420:simplemap_dff$1481.Q ;
  (* hdlname = "$auto$simplemap.cc:420:simplemap_dff$1482 Q" *)
  (* init = 1'h0 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67|../../techmap/cells_sim.v:12.30-12.31" *)
  wire \$auto$simplemap.cc:420:simplemap_dff$1482.Q ;
  (* hdlname = "$auto$simplemap.cc:420:simplemap_dff$1483 Q" *)
  (* init = 1'h0 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67|../../techmap/cells_sim.v:12.30-12.31" *)
  wire \$auto$simplemap.cc:420:simplemap_dff$1483.Q ;
  (* hdlname = "$auto$simplemap.cc:420:simplemap_dff$1484 Q" *)
  (* init = 1'h0 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67|../../techmap/cells_sim.v:12.30-12.31" *)
  wire \$auto$simplemap.cc:420:simplemap_dff$1484.Q ;
  (* hdlname = "$auto$simplemap.cc:420:simplemap_dff$1485 Q" *)
  (* init = 1'h0 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67|../../techmap/cells_sim.v:12.30-12.31" *)
  wire \$auto$simplemap.cc:420:simplemap_dff$1485.Q ;
  (* hdlname = "$auto$simplemap.cc:420:simplemap_dff$1486 Q" *)
  (* init = 1'h0 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67|../../techmap/cells_sim.v:12.30-12.31" *)
  wire \$auto$simplemap.cc:420:simplemap_dff$1486.Q ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:2.17-2.20" *)
  input clk;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:5.23-5.26" *)
  output \led[0] ;
  reg \led[0] ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:5.23-5.26" *)
  output \led[1] ;
  reg \led[1] ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:5.23-5.26" *)
  output \led[2] ;
  reg \led[2] ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:5.23-5.26" *)
  output \led[3] ;
  reg \led[3] ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:5.23-5.26" *)
  output \led[4] ;
  reg \led[4] ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:5.23-5.26" *)
  output \led[5] ;
  reg \led[5] ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:5.23-5.26" *)
  output \led[6] ;
  reg \led[6] ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:5.23-5.26" *)
  output \led[7] ;
  reg \led[7] ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:4.23-4.25" *)
  input \sw[0] ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:4.23-4.25" *)
  input \sw[1] ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:4.23-4.25" *)
  input \sw[2] ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:4.23-4.25" *)
  input \sw[3] ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:4.23-4.25" *)
  input \sw[4] ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:4.23-4.25" *)
  input \sw[5] ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:4.23-4.25" *)
  input \sw[6] ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:4.23-4.25" *)
  input \sw[7] ;
  assign \$auto$alumacc.cc:485:replace_alu$1385.slice[0].carry4.CO0  = \$auto$alumacc.cc:485:replace_alu$1385.slice[0].carry4.O0  ? (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:174.11-182.5|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:84.7-101.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8297.7-8314.6|../../techmap/cells_sim.v:170.16-170.30" *) 1'h0 : 1'h1;
  assign \$auto$alumacc.cc:485:replace_alu$1385.slice[0].carry4.CO1  = \$auto$simplemap.cc:420:simplemap_dff$1472.Q  ? (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:174.11-182.5|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:84.7-101.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8297.7-8314.6|../../techmap/cells_sim.v:171.16-171.30" *) \$auto$alumacc.cc:485:replace_alu$1385.slice[0].carry4.CO0  : 1'h0;
  assign \$auto$alumacc.cc:485:replace_alu$1385.slice[0].carry4.CO2  = \$auto$simplemap.cc:420:simplemap_dff$1473.Q  ? (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:174.11-182.5|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:84.7-101.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8297.7-8314.6|../../techmap/cells_sim.v:172.16-172.30" *) \$auto$alumacc.cc:485:replace_alu$1385.slice[0].carry4.CO1  : 1'h0;
  assign \$auto$alumacc.cc:485:replace_alu$1385.slice[0].carry4.CO3  = \$auto$simplemap.cc:420:simplemap_dff$1474.Q  ? (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:174.11-182.5|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:84.7-101.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8297.7-8314.6|../../techmap/cells_sim.v:173.16-173.30" *) \$auto$alumacc.cc:485:replace_alu$1385.slice[0].carry4.CO2  : 1'h0;
  assign \$auto$alumacc.cc:485:replace_alu$1385.slice[0].carry4.O1  = \$auto$alumacc.cc:485:replace_alu$1385.slice[0].carry4.CO0  ^ (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:174.11-182.5|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:84.7-101.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8297.7-8314.6|../../techmap/cells_sim.v:181.15-181.23" *) \$auto$simplemap.cc:420:simplemap_dff$1472.Q ;
  assign \$auto$alumacc.cc:485:replace_alu$1385.slice[0].carry4.O2  = \$auto$alumacc.cc:485:replace_alu$1385.slice[0].carry4.CO1  ^ (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:174.11-182.5|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:84.7-101.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8297.7-8314.6|../../techmap/cells_sim.v:182.15-182.23" *) \$auto$simplemap.cc:420:simplemap_dff$1473.Q ;
  assign \$auto$alumacc.cc:485:replace_alu$1385.slice[0].carry4.O3  = \$auto$alumacc.cc:485:replace_alu$1385.slice[0].carry4.CO2  ^ (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:174.11-182.5|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:84.7-101.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8297.7-8314.6|../../techmap/cells_sim.v:183.15-183.23" *) \$auto$simplemap.cc:420:simplemap_dff$1474.Q ;
  assign \$auto$alumacc.cc:485:replace_alu$1385.slice[1].carry4.CO0  = \$auto$simplemap.cc:420:simplemap_dff$1475.Q  ? (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:170.16-170.30" *) \$auto$alumacc.cc:485:replace_alu$1385.slice[0].carry4.CO3  : 1'h0;
  assign \$auto$alumacc.cc:485:replace_alu$1385.slice[1].carry4.CO1  = \$auto$simplemap.cc:420:simplemap_dff$1476.Q  ? (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:171.16-171.30" *) \$auto$alumacc.cc:485:replace_alu$1385.slice[1].carry4.CO0  : 1'h0;
  assign \$auto$alumacc.cc:485:replace_alu$1385.slice[1].carry4.CO2  = \$auto$simplemap.cc:420:simplemap_dff$1477.Q  ? (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:172.16-172.30" *) \$auto$alumacc.cc:485:replace_alu$1385.slice[1].carry4.CO1  : 1'h0;
  assign \$auto$alumacc.cc:485:replace_alu$1385.slice[1].carry4.CO3  = \$auto$simplemap.cc:420:simplemap_dff$1478.Q  ? (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:173.16-173.30" *) \$auto$alumacc.cc:485:replace_alu$1385.slice[1].carry4.CO2  : 1'h0;
  assign \$auto$alumacc.cc:485:replace_alu$1385.slice[1].carry4.O0  = \$auto$alumacc.cc:485:replace_alu$1385.slice[0].carry4.CO3  ^ (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:180.15-180.23" *) \$auto$simplemap.cc:420:simplemap_dff$1475.Q ;
  assign \$auto$alumacc.cc:485:replace_alu$1385.slice[1].carry4.O1  = \$auto$alumacc.cc:485:replace_alu$1385.slice[1].carry4.CO0  ^ (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:181.15-181.23" *) \$auto$simplemap.cc:420:simplemap_dff$1476.Q ;
  assign \$auto$alumacc.cc:485:replace_alu$1385.slice[1].carry4.O2  = \$auto$alumacc.cc:485:replace_alu$1385.slice[1].carry4.CO1  ^ (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:182.15-182.23" *) \$auto$simplemap.cc:420:simplemap_dff$1477.Q ;
  assign \$auto$alumacc.cc:485:replace_alu$1385.slice[1].carry4.O3  = \$auto$alumacc.cc:485:replace_alu$1385.slice[1].carry4.CO2  ^ (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:183.15-183.23" *) \$auto$simplemap.cc:420:simplemap_dff$1478.Q ;
  assign \$auto$alumacc.cc:485:replace_alu$1385.slice[2].carry4.CO0  = \led[0]  ? (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:170.16-170.30" *) \$auto$alumacc.cc:485:replace_alu$1385.slice[1].carry4.CO3  : 1'h0;
  assign \$auto$alumacc.cc:485:replace_alu$1385.slice[2].carry4.CO1  = \led[1]  ? (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:171.16-171.30" *) \$auto$alumacc.cc:485:replace_alu$1385.slice[2].carry4.CO0  : 1'h0;
  assign \$auto$alumacc.cc:485:replace_alu$1385.slice[2].carry4.CO2  = \led[2]  ? (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:172.16-172.30" *) \$auto$alumacc.cc:485:replace_alu$1385.slice[2].carry4.CO1  : 1'h0;
  assign \$auto$alumacc.cc:485:replace_alu$1385.slice[2].carry4.CO3  = \led[3]  ? (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:173.16-173.30" *) \$auto$alumacc.cc:485:replace_alu$1385.slice[2].carry4.CO2  : 1'h0;
  assign \$auto$alumacc.cc:485:replace_alu$1385.slice[2].carry4.O0  = \$auto$alumacc.cc:485:replace_alu$1385.slice[1].carry4.CO3  ^ (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:180.15-180.23" *) \led[0] ;
  assign \$auto$alumacc.cc:485:replace_alu$1385.slice[2].carry4.O1  = \$auto$alumacc.cc:485:replace_alu$1385.slice[2].carry4.CO0  ^ (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:181.15-181.23" *) \led[1] ;
  assign \$auto$alumacc.cc:485:replace_alu$1385.slice[2].carry4.O2  = \$auto$alumacc.cc:485:replace_alu$1385.slice[2].carry4.CO1  ^ (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:182.15-182.23" *) \led[2] ;
  assign \$auto$alumacc.cc:485:replace_alu$1385.slice[2].carry4.O3  = \$auto$alumacc.cc:485:replace_alu$1385.slice[2].carry4.CO2  ^ (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:183.15-183.23" *) \led[3] ;
  assign \$auto$alumacc.cc:485:replace_alu$1385.slice[3].carry4.CO0  = \led[4]  ? (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:170.16-170.30" *) \$auto$alumacc.cc:485:replace_alu$1385.slice[2].carry4.CO3  : 1'h0;
  assign \$auto$alumacc.cc:485:replace_alu$1385.slice[3].carry4.CO1  = \led[5]  ? (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:171.16-171.30" *) \$auto$alumacc.cc:485:replace_alu$1385.slice[3].carry4.CO0  : 1'h0;
  assign \$auto$alumacc.cc:485:replace_alu$1385.slice[3].carry4.CO2  = \led[6]  ? (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:172.16-172.30" *) \$auto$alumacc.cc:485:replace_alu$1385.slice[3].carry4.CO1  : 1'h0;
  assign \$auto$alumacc.cc:485:replace_alu$1385.slice[3].carry4.O0  = \$auto$alumacc.cc:485:replace_alu$1385.slice[2].carry4.CO3  ^ (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:180.15-180.23" *) \led[4] ;
  assign \$auto$alumacc.cc:485:replace_alu$1385.slice[3].carry4.O1  = \$auto$alumacc.cc:485:replace_alu$1385.slice[3].carry4.CO0  ^ (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:181.15-181.23" *) \led[5] ;
  assign \$auto$alumacc.cc:485:replace_alu$1385.slice[3].carry4.O2  = \$auto$alumacc.cc:485:replace_alu$1385.slice[3].carry4.CO1  ^ (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:182.15-182.23" *) \led[6] ;
  assign \$auto$alumacc.cc:485:replace_alu$1385.slice[3].carry4.O3  = \$auto$alumacc.cc:485:replace_alu$1385.slice[3].carry4.CO2  ^ (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6|../../techmap/cells_sim.v:183.15-183.23" *) \led[7] ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67|../../techmap/cells_sim.v:17.11-17.69" *)
  always @(posedge clk)
    \$auto$simplemap.cc:420:simplemap_dff$1471.Q  <= \$auto$alumacc.cc:485:replace_alu$1385.slice[0].carry4.O0 ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67|../../techmap/cells_sim.v:17.11-17.69" *)
  always @(posedge clk)
    \$auto$simplemap.cc:420:simplemap_dff$1472.Q  <= \$auto$alumacc.cc:485:replace_alu$1385.slice[0].carry4.O1 ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67|../../techmap/cells_sim.v:17.11-17.69" *)
  always @(posedge clk)
    \$auto$simplemap.cc:420:simplemap_dff$1473.Q  <= \$auto$alumacc.cc:485:replace_alu$1385.slice[0].carry4.O2 ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67|../../techmap/cells_sim.v:17.11-17.69" *)
  always @(posedge clk)
    \$auto$simplemap.cc:420:simplemap_dff$1474.Q  <= \$auto$alumacc.cc:485:replace_alu$1385.slice[0].carry4.O3 ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67|../../techmap/cells_sim.v:17.11-17.69" *)
  always @(posedge clk)
    \$auto$simplemap.cc:420:simplemap_dff$1475.Q  <= \$auto$alumacc.cc:485:replace_alu$1385.slice[1].carry4.O0 ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67|../../techmap/cells_sim.v:17.11-17.69" *)
  always @(posedge clk)
    \$auto$simplemap.cc:420:simplemap_dff$1476.Q  <= \$auto$alumacc.cc:485:replace_alu$1385.slice[1].carry4.O1 ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67|../../techmap/cells_sim.v:17.11-17.69" *)
  always @(posedge clk)
    \$auto$simplemap.cc:420:simplemap_dff$1477.Q  <= \$auto$alumacc.cc:485:replace_alu$1385.slice[1].carry4.O2 ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67|../../techmap/cells_sim.v:17.11-17.69" *)
  always @(posedge clk)
    \$auto$simplemap.cc:420:simplemap_dff$1478.Q  <= \$auto$alumacc.cc:485:replace_alu$1385.slice[1].carry4.O3 ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67|../../techmap/cells_sim.v:17.11-17.69" *)
  always @(posedge clk)
    \led[0]  <= \$auto$alumacc.cc:485:replace_alu$1385.slice[2].carry4.O0 ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67|../../techmap/cells_sim.v:17.11-17.69" *)
  always @(posedge clk)
    \led[1]  <= \$auto$alumacc.cc:485:replace_alu$1385.slice[2].carry4.O1 ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67|../../techmap/cells_sim.v:17.11-17.69" *)
  always @(posedge clk)
    \led[2]  <= \$auto$alumacc.cc:485:replace_alu$1385.slice[2].carry4.O2 ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67|../../techmap/cells_sim.v:17.11-17.69" *)
  always @(posedge clk)
    \led[3]  <= \$auto$alumacc.cc:485:replace_alu$1385.slice[2].carry4.O3 ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67|../../techmap/cells_sim.v:17.11-17.69" *)
  always @(posedge clk)
    \led[4]  <= \$auto$alumacc.cc:485:replace_alu$1385.slice[3].carry4.O0 ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67|../../techmap/cells_sim.v:17.11-17.69" *)
  always @(posedge clk)
    \led[5]  <= \$auto$alumacc.cc:485:replace_alu$1385.slice[3].carry4.O1 ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67|../../techmap/cells_sim.v:17.11-17.69" *)
  always @(posedge clk)
    \led[6]  <= \$auto$alumacc.cc:485:replace_alu$1385.slice[3].carry4.O2 ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67|../../techmap/cells_sim.v:17.11-17.69" *)
  always @(posedge clk)
    \led[7]  <= \$auto$alumacc.cc:485:replace_alu$1385.slice[3].carry4.O3 ;
  assign \$auto$alumacc.cc:485:replace_alu$1385.slice[0].carry4.O0  = 1'h1 >> (* module_not_derived = 32'd1 *) (* src = "/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:4425.24-4425.57|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:190.5-193.4" *) \$auto$simplemap.cc:420:simplemap_dff$1471.Q ;
  assign \$auto$simplemap.cc:420:simplemap_dff$1486.Q  = \led[7] ;
  assign \$auto$simplemap.cc:420:simplemap_dff$1481.Q  = \led[2] ;
  assign \$auto$simplemap.cc:420:simplemap_dff$1482.Q  = \led[3] ;
  assign \$auto$simplemap.cc:420:simplemap_dff$1479.Q  = \led[0] ;
  assign \$auto$simplemap.cc:420:simplemap_dff$1483.Q  = \led[4] ;
  assign \$auto$simplemap.cc:420:simplemap_dff$1484.Q  = \led[5] ;
  assign \$auto$simplemap.cc:420:simplemap_dff$1485.Q  = \led[6] ;
  assign \$auto$simplemap.cc:420:simplemap_dff$1480.Q  = \led[1] ;
endmodule
