/* Generated by Yosys 0.9+3710 (git sha1 2116c585, x86_64-conda_cos6-linux-gnu-gcc 1.23.0.449-a04d0 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/tmp/really-long-path/conda/conda-bld/yosys_1606966417886/work=/usr/local/src/conda/yosys-0.9_5007_g2116c585 -fdebug-prefix-map=/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base=/usr/local/src/conda-prefix -fPIC -Os -fno-merge-constants) */

(* dynports =  1  *)
(* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:1.1-18.10" *)
(* top =  1  *)
module top(clk, led, sw);
  (* unused_bits = "0" *)
  wire \$abc$3464$aiger3463$27 ;
  (* unused_bits = "0" *)
  wire \$abc$3464$aiger3463$31 ;
  (* unused_bits = "0" *)
  wire \$abc$3464$aiger3463$32 ;
  (* unused_bits = "0" *)
  wire \$abc$3464$aiger3463$33 ;
  wire \$abc$3464$aiger3463$34 ;
  wire \$abc$3464$aiger3463$35 ;
  (* unused_bits = "0" *)
  wire \$abc$3464$aiger3463$40 ;
  (* unused_bits = "0" *)
  wire \$abc$3464$aiger3463$41 ;
  (* unused_bits = "0" *)
  wire \$abc$3464$aiger3463$42 ;
  wire \$abc$3464$aiger3463$43 ;
  wire \$abc$3464$aiger3463$44 ;
  (* unused_bits = "0" *)
  wire \$abc$3464$aiger3463$49 ;
  (* unused_bits = "0" *)
  wire \$abc$3464$aiger3463$50 ;
  (* unused_bits = "0" *)
  wire \$abc$3464$aiger3463$51 ;
  wire \$abc$3464$aiger3463$52 ;
  wire \$abc$3464$aiger3463$53 ;
  (* unused_bits = "0" *)
  wire \$abc$3464$aiger3463$58 ;
  (* unused_bits = "0" *)
  wire \$abc$3464$aiger3463$59 ;
  (* unused_bits = "0" *)
  wire \$abc$3464$aiger3463$60 ;
  (* unused_bits = "0" *)
  wire \$abc$3464$aiger3463$61 ;
  (* force_downto = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:166.23-166.24" *)
  wire [15:0] \$auto$alumacc.cc:485:replace_alu$1385.O ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:36.6-36.12" *)
  wire \$techmap3690$auto$simplemap.cc:420:simplemap_dff$1471.CE_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:37.6-37.12" *)
  wire \$techmap3690$auto$simplemap.cc:420:simplemap_dff$1471.SR_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:36.6-36.12" *)
  wire \$techmap3692$auto$simplemap.cc:420:simplemap_dff$1485.CE_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:37.6-37.12" *)
  wire \$techmap3692$auto$simplemap.cc:420:simplemap_dff$1485.SR_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:36.6-36.12" *)
  wire \$techmap3693$auto$simplemap.cc:420:simplemap_dff$1483.CE_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:37.6-37.12" *)
  wire \$techmap3693$auto$simplemap.cc:420:simplemap_dff$1483.SR_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:36.6-36.12" *)
  wire \$techmap3694$auto$simplemap.cc:420:simplemap_dff$1484.CE_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:37.6-37.12" *)
  wire \$techmap3694$auto$simplemap.cc:420:simplemap_dff$1484.SR_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:36.6-36.12" *)
  wire \$techmap3696$auto$simplemap.cc:420:simplemap_dff$1486.CE_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:37.6-37.12" *)
  wire \$techmap3696$auto$simplemap.cc:420:simplemap_dff$1486.SR_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:36.6-36.12" *)
  wire \$techmap3697$auto$simplemap.cc:420:simplemap_dff$1480.CE_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:37.6-37.12" *)
  wire \$techmap3697$auto$simplemap.cc:420:simplemap_dff$1480.SR_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:36.6-36.12" *)
  wire \$techmap3698$auto$simplemap.cc:420:simplemap_dff$1481.CE_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:37.6-37.12" *)
  wire \$techmap3698$auto$simplemap.cc:420:simplemap_dff$1481.SR_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:36.6-36.12" *)
  wire \$techmap3699$auto$simplemap.cc:420:simplemap_dff$1479.CE_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:37.6-37.12" *)
  wire \$techmap3699$auto$simplemap.cc:420:simplemap_dff$1479.SR_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:36.6-36.12" *)
  wire \$techmap3701$auto$simplemap.cc:420:simplemap_dff$1482.CE_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:37.6-37.12" *)
  wire \$techmap3701$auto$simplemap.cc:420:simplemap_dff$1482.SR_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:36.6-36.12" *)
  wire \$techmap3702$auto$simplemap.cc:420:simplemap_dff$1477.CE_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:37.6-37.12" *)
  wire \$techmap3702$auto$simplemap.cc:420:simplemap_dff$1477.SR_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:36.6-36.12" *)
  wire \$techmap3703$auto$simplemap.cc:420:simplemap_dff$1476.CE_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:37.6-37.12" *)
  wire \$techmap3703$auto$simplemap.cc:420:simplemap_dff$1476.SR_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:36.6-36.12" *)
  wire \$techmap3704$auto$simplemap.cc:420:simplemap_dff$1475.CE_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:37.6-37.12" *)
  wire \$techmap3704$auto$simplemap.cc:420:simplemap_dff$1475.SR_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:36.6-36.12" *)
  wire \$techmap3706$auto$simplemap.cc:420:simplemap_dff$1478.CE_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:37.6-37.12" *)
  wire \$techmap3706$auto$simplemap.cc:420:simplemap_dff$1478.SR_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:36.6-36.12" *)
  wire \$techmap3707$auto$simplemap.cc:420:simplemap_dff$1472.CE_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:37.6-37.12" *)
  wire \$techmap3707$auto$simplemap.cc:420:simplemap_dff$1472.SR_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:36.6-36.12" *)
  wire \$techmap3708$auto$simplemap.cc:420:simplemap_dff$1473.CE_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:37.6-37.12" *)
  wire \$techmap3708$auto$simplemap.cc:420:simplemap_dff$1473.SR_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:36.6-36.12" *)
  wire \$techmap3710$auto$simplemap.cc:420:simplemap_dff$1474.CE_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:37.6-37.12" *)
  wire \$techmap3710$auto$simplemap.cc:420:simplemap_dff$1474.SR_SIG ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:2.17-2.20" *)
  input clk;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:11.20-11.27" *)
  wire [15:0] counter;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:5.23-5.26" *)
  output [7:0] led;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:4.23-4.25" *)
  input [7:0] sw;
  assign \$auto$alumacc.cc:485:replace_alu$1385.O [0] = 2'h1 >> (* module_not_derived = 32'd1 *) (* src = "/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:4425.24-4425.57|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:190.5-193.4" *) counter[0];
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:174.11-182.5|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:84.7-101.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8297.7-8314.6" *)
  CARRY4_VPR #(
    .CYINIT_AX(1'h0),
    .CYINIT_C0(1'h1),
    .CYINIT_C1(1'h0)
  ) \$auto$alumacc.cc:485:replace_alu$1385.slice[0].carry4  (
    .CO0(\$abc$3464$aiger3463$31 ),
    .CO1(\$abc$3464$aiger3463$32 ),
    .CO2(\$abc$3464$aiger3463$33 ),
    .CO3(\$abc$3464$aiger3463$34 ),
    .DI0(1'h1),
    .DI1(1'h0),
    .DI2(1'h0),
    .DI3(1'h0),
    .O0(\$abc$3464$aiger3463$27 ),
    .O1(\$auto$alumacc.cc:485:replace_alu$1385.O [1]),
    .O2(\$auto$alumacc.cc:485:replace_alu$1385.O [2]),
    .O3(\$auto$alumacc.cc:485:replace_alu$1385.O [3]),
    .S0(\$auto$alumacc.cc:485:replace_alu$1385.O [0]),
    .S1(counter[1]),
    .S2(counter[2]),
    .S3(counter[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6" *)
  CARRY4_VPR #(
    .CYINIT_AX(1'h0),
    .CYINIT_C0(1'h0),
    .CYINIT_C1(1'h0)
  ) \$auto$alumacc.cc:485:replace_alu$1385.slice[1].carry4  (
    .CIN(\$abc$3464$aiger3463$35 ),
    .CO0(\$abc$3464$aiger3463$40 ),
    .CO1(\$abc$3464$aiger3463$41 ),
    .CO2(\$abc$3464$aiger3463$42 ),
    .CO3(\$abc$3464$aiger3463$43 ),
    .DI0(1'h0),
    .DI1(1'h0),
    .DI2(1'h0),
    .DI3(1'h0),
    .O0(\$auto$alumacc.cc:485:replace_alu$1385.O [4]),
    .O1(\$auto$alumacc.cc:485:replace_alu$1385.O [5]),
    .O2(\$auto$alumacc.cc:485:replace_alu$1385.O [6]),
    .O3(\$auto$alumacc.cc:485:replace_alu$1385.O [7]),
    .S0(counter[4]),
    .S1(counter[5]),
    .S2(counter[6]),
    .S3(counter[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6" *)
  CARRY4_VPR #(
    .CYINIT_AX(1'h0),
    .CYINIT_C0(1'h0),
    .CYINIT_C1(1'h0)
  ) \$auto$alumacc.cc:485:replace_alu$1385.slice[2].carry4  (
    .CIN(\$abc$3464$aiger3463$44 ),
    .CO0(\$abc$3464$aiger3463$49 ),
    .CO1(\$abc$3464$aiger3463$50 ),
    .CO2(\$abc$3464$aiger3463$51 ),
    .CO3(\$abc$3464$aiger3463$52 ),
    .DI0(1'h0),
    .DI1(1'h0),
    .DI2(1'h0),
    .DI3(1'h0),
    .O0(\$auto$alumacc.cc:485:replace_alu$1385.O [8]),
    .O1(\$auto$alumacc.cc:485:replace_alu$1385.O [9]),
    .O2(\$auto$alumacc.cc:485:replace_alu$1385.O [10]),
    .O3(\$auto$alumacc.cc:485:replace_alu$1385.O [11]),
    .S0(led[0]),
    .S1(led[1]),
    .S2(led[2]),
    .S3(led[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6" *)
  CARRY4_VPR #(
    .CYINIT_AX(1'h0),
    .CYINIT_C0(1'h0),
    .CYINIT_C1(1'h0)
  ) \$auto$alumacc.cc:485:replace_alu$1385.slice[3].carry4  (
    .CIN(\$abc$3464$aiger3463$53 ),
    .CO0(\$abc$3464$aiger3463$58 ),
    .CO1(\$abc$3464$aiger3463$59 ),
    .CO2(\$abc$3464$aiger3463$60 ),
    .CO3(\$abc$3464$aiger3463$61 ),
    .DI0(1'h0),
    .DI1(1'h0),
    .DI2(1'h0),
    .DI3(1'h0),
    .O0(\$auto$alumacc.cc:485:replace_alu$1385.O [12]),
    .O1(\$auto$alumacc.cc:485:replace_alu$1385.O [13]),
    .O2(\$auto$alumacc.cc:485:replace_alu$1385.O [14]),
    .O3(\$auto$alumacc.cc:485:replace_alu$1385.O [15]),
    .S0(led[4]),
    .S1(led[5]),
    .S2(led[6]),
    .S3(led[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:420:simplemap_dff$1471  (
    .C(clk),
    .CE(\$techmap3690$auto$simplemap.cc:420:simplemap_dff$1471.CE_SIG ),
    .D(\$auto$alumacc.cc:485:replace_alu$1385.O [0]),
    .Q(counter[0]),
    .R(\$techmap3690$auto$simplemap.cc:420:simplemap_dff$1471.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:420:simplemap_dff$1472  (
    .C(clk),
    .CE(\$techmap3707$auto$simplemap.cc:420:simplemap_dff$1472.CE_SIG ),
    .D(\$auto$alumacc.cc:485:replace_alu$1385.O [1]),
    .Q(counter[1]),
    .R(\$techmap3707$auto$simplemap.cc:420:simplemap_dff$1472.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:420:simplemap_dff$1473  (
    .C(clk),
    .CE(\$techmap3708$auto$simplemap.cc:420:simplemap_dff$1473.CE_SIG ),
    .D(\$auto$alumacc.cc:485:replace_alu$1385.O [2]),
    .Q(counter[2]),
    .R(\$techmap3708$auto$simplemap.cc:420:simplemap_dff$1473.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:420:simplemap_dff$1474  (
    .C(clk),
    .CE(\$techmap3710$auto$simplemap.cc:420:simplemap_dff$1474.CE_SIG ),
    .D(\$auto$alumacc.cc:485:replace_alu$1385.O [3]),
    .Q(counter[3]),
    .R(\$techmap3710$auto$simplemap.cc:420:simplemap_dff$1474.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:420:simplemap_dff$1475  (
    .C(clk),
    .CE(\$techmap3704$auto$simplemap.cc:420:simplemap_dff$1475.CE_SIG ),
    .D(\$auto$alumacc.cc:485:replace_alu$1385.O [4]),
    .Q(counter[4]),
    .R(\$techmap3704$auto$simplemap.cc:420:simplemap_dff$1475.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:420:simplemap_dff$1476  (
    .C(clk),
    .CE(\$techmap3703$auto$simplemap.cc:420:simplemap_dff$1476.CE_SIG ),
    .D(\$auto$alumacc.cc:485:replace_alu$1385.O [5]),
    .Q(counter[5]),
    .R(\$techmap3703$auto$simplemap.cc:420:simplemap_dff$1476.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:420:simplemap_dff$1477  (
    .C(clk),
    .CE(\$techmap3702$auto$simplemap.cc:420:simplemap_dff$1477.CE_SIG ),
    .D(\$auto$alumacc.cc:485:replace_alu$1385.O [6]),
    .Q(counter[6]),
    .R(\$techmap3702$auto$simplemap.cc:420:simplemap_dff$1477.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:420:simplemap_dff$1478  (
    .C(clk),
    .CE(\$techmap3706$auto$simplemap.cc:420:simplemap_dff$1478.CE_SIG ),
    .D(\$auto$alumacc.cc:485:replace_alu$1385.O [7]),
    .Q(counter[7]),
    .R(\$techmap3706$auto$simplemap.cc:420:simplemap_dff$1478.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:420:simplemap_dff$1479  (
    .C(clk),
    .CE(\$techmap3699$auto$simplemap.cc:420:simplemap_dff$1479.CE_SIG ),
    .D(\$auto$alumacc.cc:485:replace_alu$1385.O [8]),
    .Q(led[0]),
    .R(\$techmap3699$auto$simplemap.cc:420:simplemap_dff$1479.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:420:simplemap_dff$1480  (
    .C(clk),
    .CE(\$techmap3697$auto$simplemap.cc:420:simplemap_dff$1480.CE_SIG ),
    .D(\$auto$alumacc.cc:485:replace_alu$1385.O [9]),
    .Q(led[1]),
    .R(\$techmap3697$auto$simplemap.cc:420:simplemap_dff$1480.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:420:simplemap_dff$1481  (
    .C(clk),
    .CE(\$techmap3698$auto$simplemap.cc:420:simplemap_dff$1481.CE_SIG ),
    .D(\$auto$alumacc.cc:485:replace_alu$1385.O [10]),
    .Q(led[2]),
    .R(\$techmap3698$auto$simplemap.cc:420:simplemap_dff$1481.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:420:simplemap_dff$1482  (
    .C(clk),
    .CE(\$techmap3701$auto$simplemap.cc:420:simplemap_dff$1482.CE_SIG ),
    .D(\$auto$alumacc.cc:485:replace_alu$1385.O [11]),
    .Q(led[3]),
    .R(\$techmap3701$auto$simplemap.cc:420:simplemap_dff$1482.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:420:simplemap_dff$1483  (
    .C(clk),
    .CE(\$techmap3693$auto$simplemap.cc:420:simplemap_dff$1483.CE_SIG ),
    .D(\$auto$alumacc.cc:485:replace_alu$1385.O [12]),
    .Q(led[4]),
    .R(\$techmap3693$auto$simplemap.cc:420:simplemap_dff$1483.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:420:simplemap_dff$1484  (
    .C(clk),
    .CE(\$techmap3694$auto$simplemap.cc:420:simplemap_dff$1484.CE_SIG ),
    .D(\$auto$alumacc.cc:485:replace_alu$1385.O [13]),
    .Q(led[5]),
    .R(\$techmap3694$auto$simplemap.cc:420:simplemap_dff$1484.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:420:simplemap_dff$1485  (
    .C(clk),
    .CE(\$techmap3692$auto$simplemap.cc:420:simplemap_dff$1485.CE_SIG ),
    .D(\$auto$alumacc.cc:485:replace_alu$1385.O [14]),
    .Q(led[6]),
    .R(\$techmap3692$auto$simplemap.cc:420:simplemap_dff$1485.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:420:simplemap_dff$1486  (
    .C(clk),
    .CE(\$techmap3696$auto$simplemap.cc:420:simplemap_dff$1486.CE_SIG ),
    .D(\$auto$alumacc.cc:485:replace_alu$1385.O [15]),
    .Q(led[7]),
    .R(\$techmap3696$auto$simplemap.cc:420:simplemap_dff$1486.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:104.21-107.6" *)
  CARRY_COUT_PLUG \$techmap2033$auto$alumacc.cc:485:replace_alu$1385.slice[1].carry4.cin_plug  (
    .CIN(\$abc$3464$aiger3463$34 ),
    .COUT(\$abc$3464$aiger3463$35 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:104.21-107.6" *)
  CARRY_COUT_PLUG \$techmap2034$auto$alumacc.cc:485:replace_alu$1385.slice[2].carry4.cin_plug  (
    .CIN(\$abc$3464$aiger3463$43 ),
    .COUT(\$abc$3464$aiger3463$44 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:14.20-14.31|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:104.21-107.6" *)
  CARRY_COUT_PLUG \$techmap2035$auto$alumacc.cc:485:replace_alu$1385.slice[3].carry4.cin_plug  (
    .CIN(\$abc$3464$aiger3463$52 ),
    .COUT(\$abc$3464$aiger3463$53 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:17.12-19.6" *)
  CE_VCC \$techmap3690$auto$simplemap.cc:420:simplemap_dff$1471.cesr_mux.ce  (
    .VCC(\$techmap3690$auto$simplemap.cc:420:simplemap_dff$1471.CE_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:25.12-27.6" *)
  SR_GND \$techmap3690$auto$simplemap.cc:420:simplemap_dff$1471.cesr_mux.sr  (
    .GND(\$techmap3690$auto$simplemap.cc:420:simplemap_dff$1471.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:17.12-19.6" *)
  CE_VCC \$techmap3692$auto$simplemap.cc:420:simplemap_dff$1485.cesr_mux.ce  (
    .VCC(\$techmap3692$auto$simplemap.cc:420:simplemap_dff$1485.CE_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:25.12-27.6" *)
  SR_GND \$techmap3692$auto$simplemap.cc:420:simplemap_dff$1485.cesr_mux.sr  (
    .GND(\$techmap3692$auto$simplemap.cc:420:simplemap_dff$1485.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:17.12-19.6" *)
  CE_VCC \$techmap3693$auto$simplemap.cc:420:simplemap_dff$1483.cesr_mux.ce  (
    .VCC(\$techmap3693$auto$simplemap.cc:420:simplemap_dff$1483.CE_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:25.12-27.6" *)
  SR_GND \$techmap3693$auto$simplemap.cc:420:simplemap_dff$1483.cesr_mux.sr  (
    .GND(\$techmap3693$auto$simplemap.cc:420:simplemap_dff$1483.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:17.12-19.6" *)
  CE_VCC \$techmap3694$auto$simplemap.cc:420:simplemap_dff$1484.cesr_mux.ce  (
    .VCC(\$techmap3694$auto$simplemap.cc:420:simplemap_dff$1484.CE_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:25.12-27.6" *)
  SR_GND \$techmap3694$auto$simplemap.cc:420:simplemap_dff$1484.cesr_mux.sr  (
    .GND(\$techmap3694$auto$simplemap.cc:420:simplemap_dff$1484.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:17.12-19.6" *)
  CE_VCC \$techmap3696$auto$simplemap.cc:420:simplemap_dff$1486.cesr_mux.ce  (
    .VCC(\$techmap3696$auto$simplemap.cc:420:simplemap_dff$1486.CE_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:25.12-27.6" *)
  SR_GND \$techmap3696$auto$simplemap.cc:420:simplemap_dff$1486.cesr_mux.sr  (
    .GND(\$techmap3696$auto$simplemap.cc:420:simplemap_dff$1486.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:17.12-19.6" *)
  CE_VCC \$techmap3697$auto$simplemap.cc:420:simplemap_dff$1480.cesr_mux.ce  (
    .VCC(\$techmap3697$auto$simplemap.cc:420:simplemap_dff$1480.CE_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:25.12-27.6" *)
  SR_GND \$techmap3697$auto$simplemap.cc:420:simplemap_dff$1480.cesr_mux.sr  (
    .GND(\$techmap3697$auto$simplemap.cc:420:simplemap_dff$1480.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:17.12-19.6" *)
  CE_VCC \$techmap3698$auto$simplemap.cc:420:simplemap_dff$1481.cesr_mux.ce  (
    .VCC(\$techmap3698$auto$simplemap.cc:420:simplemap_dff$1481.CE_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:25.12-27.6" *)
  SR_GND \$techmap3698$auto$simplemap.cc:420:simplemap_dff$1481.cesr_mux.sr  (
    .GND(\$techmap3698$auto$simplemap.cc:420:simplemap_dff$1481.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:17.12-19.6" *)
  CE_VCC \$techmap3699$auto$simplemap.cc:420:simplemap_dff$1479.cesr_mux.ce  (
    .VCC(\$techmap3699$auto$simplemap.cc:420:simplemap_dff$1479.CE_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:25.12-27.6" *)
  SR_GND \$techmap3699$auto$simplemap.cc:420:simplemap_dff$1479.cesr_mux.sr  (
    .GND(\$techmap3699$auto$simplemap.cc:420:simplemap_dff$1479.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:17.12-19.6" *)
  CE_VCC \$techmap3701$auto$simplemap.cc:420:simplemap_dff$1482.cesr_mux.ce  (
    .VCC(\$techmap3701$auto$simplemap.cc:420:simplemap_dff$1482.CE_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:25.12-27.6" *)
  SR_GND \$techmap3701$auto$simplemap.cc:420:simplemap_dff$1482.cesr_mux.sr  (
    .GND(\$techmap3701$auto$simplemap.cc:420:simplemap_dff$1482.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:17.12-19.6" *)
  CE_VCC \$techmap3702$auto$simplemap.cc:420:simplemap_dff$1477.cesr_mux.ce  (
    .VCC(\$techmap3702$auto$simplemap.cc:420:simplemap_dff$1477.CE_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:25.12-27.6" *)
  SR_GND \$techmap3702$auto$simplemap.cc:420:simplemap_dff$1477.cesr_mux.sr  (
    .GND(\$techmap3702$auto$simplemap.cc:420:simplemap_dff$1477.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:17.12-19.6" *)
  CE_VCC \$techmap3703$auto$simplemap.cc:420:simplemap_dff$1476.cesr_mux.ce  (
    .VCC(\$techmap3703$auto$simplemap.cc:420:simplemap_dff$1476.CE_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:25.12-27.6" *)
  SR_GND \$techmap3703$auto$simplemap.cc:420:simplemap_dff$1476.cesr_mux.sr  (
    .GND(\$techmap3703$auto$simplemap.cc:420:simplemap_dff$1476.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:17.12-19.6" *)
  CE_VCC \$techmap3704$auto$simplemap.cc:420:simplemap_dff$1475.cesr_mux.ce  (
    .VCC(\$techmap3704$auto$simplemap.cc:420:simplemap_dff$1475.CE_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:25.12-27.6" *)
  SR_GND \$techmap3704$auto$simplemap.cc:420:simplemap_dff$1475.cesr_mux.sr  (
    .GND(\$techmap3704$auto$simplemap.cc:420:simplemap_dff$1475.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:17.12-19.6" *)
  CE_VCC \$techmap3706$auto$simplemap.cc:420:simplemap_dff$1478.cesr_mux.ce  (
    .VCC(\$techmap3706$auto$simplemap.cc:420:simplemap_dff$1478.CE_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:25.12-27.6" *)
  SR_GND \$techmap3706$auto$simplemap.cc:420:simplemap_dff$1478.cesr_mux.sr  (
    .GND(\$techmap3706$auto$simplemap.cc:420:simplemap_dff$1478.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:17.12-19.6" *)
  CE_VCC \$techmap3707$auto$simplemap.cc:420:simplemap_dff$1472.cesr_mux.ce  (
    .VCC(\$techmap3707$auto$simplemap.cc:420:simplemap_dff$1472.CE_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:25.12-27.6" *)
  SR_GND \$techmap3707$auto$simplemap.cc:420:simplemap_dff$1472.cesr_mux.sr  (
    .GND(\$techmap3707$auto$simplemap.cc:420:simplemap_dff$1472.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:17.12-19.6" *)
  CE_VCC \$techmap3708$auto$simplemap.cc:420:simplemap_dff$1473.cesr_mux.ce  (
    .VCC(\$techmap3708$auto$simplemap.cc:420:simplemap_dff$1473.CE_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:25.12-27.6" *)
  SR_GND \$techmap3708$auto$simplemap.cc:420:simplemap_dff$1473.cesr_mux.sr  (
    .GND(\$techmap3708$auto$simplemap.cc:420:simplemap_dff$1473.SR_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:17.12-19.6" *)
  CE_VCC \$techmap3710$auto$simplemap.cc:420:simplemap_dff$1474.cesr_mux.ce  (
    .VCC(\$techmap3710$auto$simplemap.cc:420:simplemap_dff$1474.CE_SIG )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.5-15.8|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:39.10-44.2|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:25.12-27.6" *)
  SR_GND \$techmap3710$auto$simplemap.cc:420:simplemap_dff$1474.cesr_mux.sr  (
    .GND(\$techmap3710$auto$simplemap.cc:420:simplemap_dff$1474.SR_SIG )
  );
  assign counter[15:8] = led;
endmodule
