/* Generated by Yosys 0.9+3710 (git sha1 2116c585, x86_64-conda_cos6-linux-gnu-gcc 1.23.0.449-a04d0 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/tmp/really-long-path/conda/conda-bld/yosys_1606966417886/work=/usr/local/src/conda/yosys-0.9_5007_g2116c585 -fdebug-prefix-map=/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base=/usr/local/src/conda-prefix -fPIC -Os -fno-merge-constants) */

(* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/carry/carry.v:1.1-14.10" *)
(* top =  1  *)
module top(clk, led, rx, sw, tx);
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/carry/carry.v:2.17-2.20" *)
  input clk;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/carry/carry.v:8.21-8.24" *)
  output [15:0] led;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/carry/carry.v:4.17-4.19" *)
  input rx;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/carry/carry.v:7.21-7.23" *)
  input [15:0] sw;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/carry/carry.v:5.17-5.19" *)
  output tx;
  assign tx = rx;
  assign led = sw;
endmodule
