/* Generated by Yosys 0.9+3710 (git sha1 2116c585, x86_64-conda_cos6-linux-gnu-gcc 1.23.0.449-a04d0 -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/tmp/really-long-path/conda/conda-bld/yosys_1606966417886/work=/usr/local/src/conda/yosys-0.9_5007_g2116c585 -fdebug-prefix-map=/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base=/usr/local/src/conda-prefix -fPIC -Os -fno-merge-constants) */

(* dynports =  1  *)
(* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:1.1-16.10" *)
(* top =  1  *)
module top(clk, led, sw);
  wire \$abc$1875$aiger1874$4b ;
  wire \$abc$1875$aiger1874$6b ;
  (* unused_bits = "0" *)
  wire \$abc$3409$aiger3408$12 ;
  (* unused_bits = "0" *)
  wire \$abc$3409$aiger3408$13 ;
  (* unused_bits = "0" *)
  wire \$abc$3409$aiger3408$14 ;
  (* unused_bits = "0" *)
  wire \$abc$3409$aiger3408$15 ;
  (* unused_bits = "0" *)
  wire \$abc$3409$aiger3408$16 ;
  (* unused_bits = "0" *)
  wire \$abc$3409$aiger3408$17 ;
  (* unused_bits = "0" *)
  wire \$abc$3409$aiger3408$18 ;
  wire \$abc$3409$aiger3408$19 ;
  wire \$abc$3409$aiger3408$20 ;
  (* unused_bits = "0" *)
  wire \$abc$3409$aiger3408$21 ;
  (* unused_bits = "0" *)
  wire \$abc$3409$aiger3408$22 ;
  (* unused_bits = "0" *)
  wire \$abc$3409$aiger3408$25 ;
  (* unused_bits = "0" *)
  wire \$abc$3409$aiger3408$26 ;
  (* unused_bits = "0" *)
  wire \$abc$3409$aiger3408$27 ;
  wire \$abc$3409$aiger3408$28 ;
  wire \$abc$3409$aiger3408$29 ;
  (* unused_bits = "0" *)
  wire \$abc$3409$aiger3408$34 ;
  (* unused_bits = "0" *)
  wire \$abc$3409$aiger3408$35 ;
  (* unused_bits = "0" *)
  wire \$abc$3409$aiger3408$36 ;
  wire \$abc$3409$aiger3408$37 ;
  wire \$abc$3409$aiger3408$38 ;
  (* unused_bits = "0" *)
  wire \$abc$3409$aiger3408$41 ;
  (* unused_bits = "0" *)
  wire \$abc$3409$aiger3408$42 ;
  (* unused_bits = "0" *)
  wire \$abc$3409$aiger3408$43 ;
  (* unused_bits = "0" *)
  wire \$abc$3409$aiger3408$44 ;
  (* unused_bits = "0" *)
  wire \$abc$3409$aiger3408$45 ;
  (* unused_bits = "0" *)
  wire \$abc$3409$aiger3408$46 ;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:11.21-11.26" *)
  wire [15:0] adder;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:2.17-2.20" *)
  input clk;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:5.23-5.26" *)
  output [7:0] led;
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:4.23-4.25" *)
  input [7:0] sw;
  assign \$abc$1875$aiger1874$4b  = 2'h1 >> (* module_not_derived = 32'd1 *) (* src = "/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:4425.24-4425.57|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:190.5-193.4" *) sw[2];
  assign \$abc$1875$aiger1874$6b  = 2'h1 >> (* module_not_derived = 32'd1 *) (* src = "/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:36.13-36.48|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:4425.24-4425.57|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:190.5-193.4" *) sw[4];
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.20-13.33|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:174.11-182.5|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:84.7-101.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8297.7-8314.6" *)
  CARRY4_VPR #(
    .CYINIT_AX(1'h0),
    .CYINIT_C0(1'h1),
    .CYINIT_C1(1'h0)
  ) \$auto$alumacc.cc:485:replace_alu$1382.slice[0].carry4  (
    .CO0(\$abc$3409$aiger3408$16 ),
    .CO1(\$abc$3409$aiger3408$17 ),
    .CO2(\$abc$3409$aiger3408$18 ),
    .CO3(\$abc$3409$aiger3408$19 ),
    .DI0(1'h1),
    .DI1(1'h0),
    .DI2(1'h1),
    .DI3(1'h0),
    .O0(\$abc$3409$aiger3408$12 ),
    .O1(\$abc$3409$aiger3408$13 ),
    .O2(\$abc$3409$aiger3408$14 ),
    .O3(\$abc$3409$aiger3408$15 ),
    .S0(\$abc$1875$aiger1874$4b ),
    .S1(sw[3]),
    .S2(\$abc$1875$aiger1874$6b ),
    .S3(sw[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.20-13.33|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6" *)
  CARRY4_VPR #(
    .CYINIT_AX(1'h0),
    .CYINIT_C0(1'h0),
    .CYINIT_C1(1'h0)
  ) \$auto$alumacc.cc:485:replace_alu$1382.slice[1].carry4  (
    .CIN(\$abc$3409$aiger3408$20 ),
    .CO0(\$abc$3409$aiger3408$25 ),
    .CO1(\$abc$3409$aiger3408$26 ),
    .CO2(\$abc$3409$aiger3408$27 ),
    .CO3(\$abc$3409$aiger3408$28 ),
    .DI0(1'h0),
    .DI1(1'h0),
    .DI2(1'h0),
    .DI3(1'h0),
    .O0(\$abc$3409$aiger3408$21 ),
    .O1(\$abc$3409$aiger3408$22 ),
    .O2(led[0]),
    .O3(led[1]),
    .S0(sw[6]),
    .S1(sw[7]),
    .S2(sw[0]),
    .S3(sw[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.20-13.33|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6" *)
  CARRY4_VPR #(
    .CYINIT_AX(1'h0),
    .CYINIT_C0(1'h0),
    .CYINIT_C1(1'h0)
  ) \$auto$alumacc.cc:485:replace_alu$1382.slice[2].carry4  (
    .CIN(\$abc$3409$aiger3408$29 ),
    .CO0(\$abc$3409$aiger3408$34 ),
    .CO1(\$abc$3409$aiger3408$35 ),
    .CO2(\$abc$3409$aiger3408$36 ),
    .CO3(\$abc$3409$aiger3408$37 ),
    .DI0(1'h0),
    .DI1(1'h0),
    .DI2(1'h0),
    .DI3(1'h0),
    .O0(led[2]),
    .O1(led[3]),
    .O2(led[4]),
    .O3(led[5]),
    .S0(sw[2]),
    .S1(sw[3]),
    .S2(sw[4]),
    .S3(sw[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.20-13.33|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:113.7-131.6|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:8320.7-8338.6" *)
  CARRY4_VPR #(
    .CYINIT_AX(1'h0),
    .CYINIT_C0(1'h0),
    .CYINIT_C1(1'h0)
  ) \$auto$alumacc.cc:485:replace_alu$1382.slice[3].carry4  (
    .CIN(\$abc$3409$aiger3408$38 ),
    .CO0(\$abc$3409$aiger3408$43 ),
    .CO1(\$abc$3409$aiger3408$44 ),
    .CO2(\$abc$3409$aiger3408$45 ),
    .CO3(\$abc$3409$aiger3408$46 ),
    .DI0(1'h0),
    .DI1(1'h0),
    .DI2(1'h0),
    .DI3(1'h0),
    .O0(led[6]),
    .O1(led[7]),
    .O2(\$abc$3409$aiger3408$41 ),
    .O3(\$abc$3409$aiger3408$42 ),
    .S0(sw[6]),
    .S1(sw[7]),
    .S2(1'h0),
    .S3(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.20-13.33|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:104.21-107.6" *)
  CARRY_COUT_PLUG \$techmap1977$auto$alumacc.cc:485:replace_alu$1382.slice[1].carry4.cin_plug  (
    .CIN(\$abc$3409$aiger3408$19 ),
    .COUT(\$abc$3409$aiger3408$20 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.20-13.33|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:104.21-107.6" *)
  CARRY_COUT_PLUG \$techmap1978$auto$alumacc.cc:485:replace_alu$1382.slice[2].carry4.cin_plug  (
    .CIN(\$abc$3409$aiger3408$28 ),
    .COUT(\$abc$3409$aiger3408$29 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/scratch/unsafe/butta/symbiflow-arch-defs/build/xc/xc7/tests/counter/counter_arty.v:13.20-13.33|/mnt/icgridio2/unsafe/butta/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/arith_map.v:184.14-192.8|/scratch/unsafe/butta/symbiflow-arch-defs/xc/xc7/techmap/carry_map.v:104.21-107.6" *)
  CARRY_COUT_PLUG \$techmap1979$auto$alumacc.cc:485:replace_alu$1382.slice[3].carry4.cin_plug  (
    .CIN(\$abc$3409$aiger3408$37 ),
    .COUT(\$abc$3409$aiger3408$38 )
  );
  assign adder = { led, 6'h00, sw[1:0] };
endmodule
