/* Generated by Yosys 0.9+3885 (git sha1 afcc31ce, clang 11.0.1 -fPIC -Os) */

(* top =  1  *)
(* src = "top_bit.v:1.1-3727.10" *)
module top(clk, rx, \sw[0] , \sw[1] , \sw[2] , \sw[3] , \sw[4] , \sw[5] , \sw[6] , \sw[7] , \sw[8] , \sw[9] , \sw[10] , \sw[11] , \sw[12] , \sw[13] , \sw[14] , \sw[15] , \led[0] , \led[1] , \led[2] , \led[3] , \led[4] , \led[5] , \led[6] , \led[7] , \led[8] , \led[9] , \led[10] , \led[11] , \led[12] , \led[13] , \led[14] , \led[15] , tx);
  (* src = "top_bit.v:10.14-10.54" *)
  wire _000_;
  (* src = "top_bit.v:11.14-11.54" *)
  wire _001_;
  (* src = "top_bit.v:12.14-12.54" *)
  wire _002_;
  (* src = "top_bit.v:13.14-13.54" *)
  wire _003_;
  (* src = "top_bit.v:16.14-16.53" *)
  wire _004_;
  (* src = "top_bit.v:17.14-17.53" *)
  wire _005_;
  (* src = "top_bit.v:18.14-18.53" *)
  wire _006_;
  (* src = "top_bit.v:19.14-19.53" *)
  wire _007_;
  (* src = "top_bit.v:20.14-20.53" *)
  wire _008_;
  (* src = "top_bit.v:21.14-21.53" *)
  wire _009_;
  (* src = "top_bit.v:56.14-56.47" *)
  wire _010_;
  (* src = "top_bit.v:57.14-57.47" *)
  wire _011_;
  (* src = "top_bit.v:58.14-58.48" *)
  wire _012_;
  (* src = "top_bit.v:59.14-59.48" *)
  wire _013_;
  (* src = "top_bit.v:60.14-60.48" *)
  wire _014_;
  (* src = "top_bit.v:61.14-61.48" *)
  wire _015_;
  (* src = "top_bit.v:62.14-62.48" *)
  wire _016_;
  (* src = "top_bit.v:64.14-64.47" *)
  wire _017_;
  (* src = "top_bit.v:65.14-65.47" *)
  wire _018_;
  (* src = "top_bit.v:66.14-66.47" *)
  wire _019_;
  (* src = "top_bit.v:67.14-67.47" *)
  wire _020_;
  (* src = "top_bit.v:68.14-68.47" *)
  wire _021_;
  (* src = "top_bit.v:69.14-69.47" *)
  wire _022_;
  (* src = "top_bit.v:70.14-70.47" *)
  wire _023_;
  (* src = "top_bit.v:71.14-71.47" *)
  wire _024_;
  (* src = "top_bit.v:74.14-74.49" *)
  wire _025_;
  (* src = "top_bit.v:76.14-76.44" *)
  wire _026_;
  (* src = "top_bit.v:77.14-77.44" *)
  wire _027_;
  (* src = "top_bit.v:78.14-78.45" *)
  wire _028_;
  (* src = "top_bit.v:79.14-79.45" *)
  wire _029_;
  (* src = "top_bit.v:80.14-80.45" *)
  wire _030_;
  (* src = "top_bit.v:81.14-81.45" *)
  wire _031_;
  (* src = "top_bit.v:82.14-82.45" *)
  wire _032_;
  (* src = "top_bit.v:83.14-83.45" *)
  (* unused_bits = "0" *)
  wire _033_;
  (* src = "top_bit.v:84.14-84.45" *)
  (* unused_bits = "0" *)
  wire _034_;
  (* src = "top_bit.v:85.14-85.45" *)
  (* unused_bits = "0" *)
  wire _035_;
  (* src = "top_bit.v:86.14-86.45" *)
  (* unused_bits = "0" *)
  wire _036_;
  (* src = "top_bit.v:87.14-87.45" *)
  (* unused_bits = "0" *)
  wire _037_;
  (* src = "top_bit.v:88.14-88.44" *)
  wire _038_;
  (* src = "top_bit.v:89.14-89.45" *)
  (* unused_bits = "0" *)
  wire _039_;
  (* src = "top_bit.v:90.14-90.45" *)
  (* unused_bits = "0" *)
  wire _040_;
  (* src = "top_bit.v:91.14-91.45" *)
  (* unused_bits = "0" *)
  wire _041_;
  (* src = "top_bit.v:92.14-92.45" *)
  (* unused_bits = "0" *)
  wire _042_;
  (* src = "top_bit.v:93.14-93.45" *)
  (* unused_bits = "0" *)
  wire _043_;
  (* src = "top_bit.v:94.14-94.45" *)
  (* unused_bits = "0" *)
  wire _044_;
  (* src = "top_bit.v:95.14-95.45" *)
  (* unused_bits = "0" *)
  wire _045_;
  (* src = "top_bit.v:96.14-96.45" *)
  (* unused_bits = "0" *)
  wire _046_;
  (* src = "top_bit.v:97.14-97.45" *)
  (* unused_bits = "0" *)
  wire _047_;
  (* src = "top_bit.v:98.14-98.45" *)
  (* unused_bits = "0" *)
  wire _048_;
  (* src = "top_bit.v:99.14-99.44" *)
  wire _049_;
  (* src = "top_bit.v:100.14-100.45" *)
  (* unused_bits = "0" *)
  wire _050_;
  (* src = "top_bit.v:101.14-101.45" *)
  (* unused_bits = "0" *)
  wire _051_;
  (* src = "top_bit.v:102.14-102.44" *)
  wire _052_;
  (* src = "top_bit.v:103.14-103.44" *)
  wire _053_;
  (* src = "top_bit.v:104.14-104.44" *)
  wire _054_;
  (* src = "top_bit.v:105.14-105.44" *)
  wire _055_;
  (* src = "top_bit.v:106.14-106.44" *)
  wire _056_;
  (* src = "top_bit.v:107.14-107.44" *)
  wire _057_;
  (* src = "top_bit.v:108.14-108.45" *)
  wire _058_;
  (* src = "top_bit.v:109.14-109.45" *)
  (* unused_bits = "0" *)
  wire _059_;
  (* src = "top_bit.v:110.14-110.45" *)
  (* unused_bits = "0" *)
  wire _060_;
  (* src = "top_bit.v:111.14-111.45" *)
  (* unused_bits = "0" *)
  wire _061_;
  (* src = "top_bit.v:126.14-126.47" *)
  wire _062_;
  (* src = "top_bit.v:242.14-242.43" *)
  wire _063_;
  (* src = "top_bit.v:254.14-254.43" *)
  wire _064_;
  (* src = "top_bit.v:349.14-349.43" *)
  wire _065_;
  (* src = "top_bit.v:361.14-361.43" *)
  wire _066_;
  (* src = "top_bit.v:464.14-464.43" *)
  wire _067_;
  (* src = "top_bit.v:476.14-476.43" *)
  wire _068_;
  (* src = "top_bit.v:517.14-517.43" *)
  wire _069_;
  (* src = "top_bit.v:529.14-529.43" *)
  wire _070_;
  (* src = "top_bit.v:570.14-570.43" *)
  wire _071_;
  (* src = "top_bit.v:582.14-582.43" *)
  wire _072_;
  (* src = "top_bit.v:1254.5-1263.4|../../techmap/lut_simplif.v:4.8-4.16" *)
  wire _073_;
  (* src = "top_bit.v:1239.5-1248.4|../../techmap/lut_simplif.v:4.8-4.16" *)
  wire _074_;
  (* src = "top_bit.v:1340.5-1349.4|../../techmap/lut_simplif.v:4.8-4.16" *)
  wire _075_;
  (* src = "top_bit.v:1325.5-1334.4|../../techmap/lut_simplif.v:4.8-4.16" *)
  wire _076_;
  (* src = "top_bit.v:1426.5-1435.4|../../techmap/lut_simplif.v:4.8-4.16" *)
  wire _077_;
  (* src = "top_bit.v:1426.5-1435.4|../../techmap/lut_simplif.v:4.18-4.26" *)
  wire _078_;
  (* src = "top_bit.v:1411.5-1420.4|../../techmap/lut_simplif.v:4.8-4.16" *)
  wire _079_;
  (* src = "top_bit.v:1411.5-1420.4|../../techmap/lut_simplif.v:4.18-4.26" *)
  wire _080_;
  (* src = "top_bit.v:1624.5-1633.4|../../techmap/lut_simplif.v:4.8-4.16" *)
  wire _081_;
  (* src = "top_bit.v:1624.5-1633.4|../../techmap/lut_simplif.v:4.18-4.26" *)
  wire _082_;
  (* src = "top_bit.v:1609.5-1618.4|../../techmap/lut_simplif.v:4.8-4.16" *)
  wire _083_;
  (* src = "top_bit.v:1609.5-1618.4|../../techmap/lut_simplif.v:4.18-4.26" *)
  wire _084_;
  (* src = "top_bit.v:1874.5-1883.4|../../techmap/lut_simplif.v:4.8-4.16" *)
  wire _085_;
  (* src = "top_bit.v:1874.5-1883.4|../../techmap/lut_simplif.v:4.18-4.26" *)
  wire _086_;
  (* src = "top_bit.v:1859.5-1868.4|../../techmap/lut_simplif.v:4.8-4.16" *)
  wire _087_;
  (* src = "top_bit.v:1859.5-1868.4|../../techmap/lut_simplif.v:4.18-4.26" *)
  wire _088_;
  (* src = "top_bit.v:1960.5-1969.4|../../techmap/lut_simplif.v:4.8-4.16" *)
  wire _089_;
  (* src = "top_bit.v:1960.5-1969.4|../../techmap/lut_simplif.v:4.18-4.26" *)
  wire _090_;
  (* src = "top_bit.v:1945.5-1954.4|../../techmap/lut_simplif.v:4.8-4.16" *)
  wire _091_;
  (* src = "top_bit.v:1945.5-1954.4|../../techmap/lut_simplif.v:4.18-4.26" *)
  wire _092_;
  (* src = "top_bit.v:2046.5-2055.4|../../techmap/lut_simplif.v:4.8-4.16" *)
  wire _093_;
  (* src = "top_bit.v:2046.5-2055.4|../../techmap/lut_simplif.v:4.18-4.26" *)
  wire _094_;
  (* src = "top_bit.v:2031.5-2040.4|../../techmap/lut_simplif.v:4.8-4.16" *)
  wire _095_;
  (* src = "top_bit.v:2031.5-2040.4|../../techmap/lut_simplif.v:4.18-4.26" *)
  wire _096_;
  (* src = "top_bit.v:2132.5-2141.4|../../techmap/lut_simplif.v:4.8-4.16" *)
  wire _097_;
  (* src = "top_bit.v:2117.5-2126.4|../../techmap/lut_simplif.v:4.8-4.16" *)
  wire _098_;
  (* src = "top_bit.v:2270.5-2279.4|../../techmap/lut_simplif.v:4.8-4.16" *)
  wire _099_;
  (* src = "top_bit.v:2270.5-2279.4|../../techmap/lut_simplif.v:4.18-4.26" *)
  wire _100_;
  (* src = "top_bit.v:2255.5-2264.4|../../techmap/lut_simplif.v:4.8-4.16" *)
  wire _101_;
  (* src = "top_bit.v:2255.5-2264.4|../../techmap/lut_simplif.v:4.18-4.26" *)
  wire _102_;
  (* src = "top_bit.v:2225.5-2234.4|../../techmap/lut_simplif.v:4.18-4.26" *)
  wire _103_;
  (* src = "top_bit.v:2.9-2.12" *)
  input clk;
  (* src = "top_bit.v:5.17-5.20" *)
  output \led[0] ;
  (* src = "top_bit.v:5.17-5.20" *)
  output \led[10] ;
  (* src = "top_bit.v:5.17-5.20" *)
  output \led[11] ;
  (* src = "top_bit.v:5.17-5.20" *)
  output \led[12] ;
  (* src = "top_bit.v:5.17-5.20" *)
  output \led[13] ;
  (* src = "top_bit.v:5.17-5.20" *)
  output \led[14] ;
  (* src = "top_bit.v:5.17-5.20" *)
  output \led[15] ;
  (* src = "top_bit.v:5.17-5.20" *)
  output \led[1] ;
  (* src = "top_bit.v:5.17-5.20" *)
  output \led[2] ;
  (* src = "top_bit.v:5.17-5.20" *)
  output \led[3] ;
  (* src = "top_bit.v:5.17-5.20" *)
  output \led[4] ;
  (* src = "top_bit.v:5.17-5.20" *)
  output \led[5] ;
  (* src = "top_bit.v:5.17-5.20" *)
  output \led[6] ;
  (* src = "top_bit.v:5.17-5.20" *)
  output \led[7] ;
  (* src = "top_bit.v:5.17-5.20" *)
  output \led[8] ;
  (* src = "top_bit.v:5.17-5.20" *)
  output \led[9] ;
  (* src = "top_bit.v:3.9-3.11" *)
  input rx;
  (* src = "top_bit.v:4.16-4.18" *)
  input \sw[0] ;
  (* src = "top_bit.v:4.16-4.18" *)
  input \sw[10] ;
  (* src = "top_bit.v:4.16-4.18" *)
  input \sw[11] ;
  (* src = "top_bit.v:4.16-4.18" *)
  input \sw[12] ;
  (* src = "top_bit.v:4.16-4.18" *)
  input \sw[13] ;
  (* src = "top_bit.v:4.16-4.18" *)
  input \sw[14] ;
  (* src = "top_bit.v:4.16-4.18" *)
  input \sw[15] ;
  (* src = "top_bit.v:4.16-4.18" *)
  input \sw[1] ;
  (* src = "top_bit.v:4.16-4.18" *)
  input \sw[2] ;
  (* src = "top_bit.v:4.16-4.18" *)
  input \sw[3] ;
  (* src = "top_bit.v:4.16-4.18" *)
  input \sw[4] ;
  (* src = "top_bit.v:4.16-4.18" *)
  input \sw[5] ;
  (* src = "top_bit.v:4.16-4.18" *)
  input \sw[6] ;
  (* src = "top_bit.v:4.16-4.18" *)
  input \sw[7] ;
  (* src = "top_bit.v:4.16-4.18" *)
  input \sw[8] ;
  (* src = "top_bit.v:4.16-4.18" *)
  input \sw[9] ;
  (* src = "top_bit.v:6.10-6.12" *)
  output tx;
  (* BEL = "D5FF" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:2325.5-2331.4|../../techmap/bels2vpr_map.v:480.3-480.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:442:simplemap_dffe$1676CLBLM_R_X7Y120_SLICE_X9Y120_D5_FDRE  (
    .C(clk),
    .CE(_103_),
    .D(\sw[0] ),
    .Q(_025_),
    .R(1'h0)
  );
  (* BEL = "A5FF" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:2286.5-2292.4|../../techmap/bels2vpr_map.v:480.3-480.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:442:simplemap_dffe$1677CLBLM_R_X7Y120_SLICE_X9Y120_A5_FDRE  (
    .C(clk),
    .CE(_103_),
    .D(\sw[1] ),
    .Q(_023_),
    .R(1'h0)
  );
  (* BEL = "B5FF" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:2299.5-2305.4|../../techmap/bels2vpr_map.v:480.3-480.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:442:simplemap_dffe$1678CLBLM_R_X7Y120_SLICE_X9Y120_B5_FDRE  (
    .C(clk),
    .CE(_103_),
    .D(\sw[2] ),
    .Q(_024_),
    .R(1'h0)
  );
  (* BEL = "AFF" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:2338.5-2344.4|../../techmap/bels2vpr_map.v:480.3-480.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:442:simplemap_dffe$1679CLBLM_R_X7Y120_SLICE_X9Y120_A_FDRE  (
    .C(clk),
    .CE(_103_),
    .D(\sw[3] ),
    .Q(_012_),
    .R(1'h0)
  );
  (* BEL = "BFF" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:2351.5-2357.4|../../techmap/bels2vpr_map.v:480.3-480.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:442:simplemap_dffe$1680CLBLM_R_X7Y120_SLICE_X9Y120_B_FDRE  (
    .C(clk),
    .CE(_103_),
    .D(\sw[4] ),
    .Q(_013_),
    .R(1'h0)
  );
  (* BEL = "CFF" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:2364.5-2370.4|../../techmap/bels2vpr_map.v:480.3-480.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:442:simplemap_dffe$1681CLBLM_R_X7Y120_SLICE_X9Y120_C_FDRE  (
    .C(clk),
    .CE(_103_),
    .D(\sw[5] ),
    .Q(_014_),
    .R(1'h0)
  );
  (* BEL = "DFF" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:2377.5-2383.4|../../techmap/bels2vpr_map.v:480.3-480.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:442:simplemap_dffe$1682CLBLM_R_X7Y120_SLICE_X9Y120_D_FDRE  (
    .C(clk),
    .CE(_103_),
    .D(\sw[6] ),
    .Q(_015_),
    .R(1'h0)
  );
  (* BEL = "C5FF" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:2312.5-2318.4|../../techmap/bels2vpr_map.v:480.3-480.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:442:simplemap_dffe$1683CLBLM_R_X7Y120_SLICE_X9Y120_C5_FDRE  (
    .C(clk),
    .CE(_103_),
    .D(\sw[7] ),
    .Q(_016_),
    .R(1'h0)
  );
  (* BEL = "D5FF" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:2161.5-2167.4|../../techmap/bels2vpr_map.v:480.3-480.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:442:simplemap_dffe$1754CLBLM_R_X7Y120_SLICE_X8Y120_D5_FDRE  (
    .C(clk),
    .CE(_099_),
    .D(\sw[0] ),
    .Q(_004_),
    .R(1'h0)
  );
  (* BEL = "D5FF" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1455.5-1461.4|../../techmap/bels2vpr_map.v:480.3-480.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:442:simplemap_dffe$1755CLBLM_R_X5Y119_SLICE_X7Y119_D5_FDRE  (
    .C(clk),
    .CE(_099_),
    .D(\sw[1] ),
    .Q(_005_),
    .R(1'h0)
  );
  (* BEL = "CFF" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1468.5-1474.4|../../techmap/bels2vpr_map.v:480.3-480.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:442:simplemap_dffe$1756CLBLM_R_X5Y119_SLICE_X7Y119_C_FDRE  (
    .C(clk),
    .CE(_099_),
    .D(\sw[2] ),
    .Q(_006_),
    .R(1'h0)
  );
  (* BEL = "DFF" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1481.5-1487.4|../../techmap/bels2vpr_map.v:480.3-480.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:442:simplemap_dffe$1757CLBLM_R_X5Y119_SLICE_X7Y119_D_FDRE  (
    .C(clk),
    .CE(_099_),
    .D(\sw[3] ),
    .Q(_007_),
    .R(1'h0)
  );
  (* BEL = "C5FF" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1442.5-1448.4|../../techmap/bels2vpr_map.v:480.3-480.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:442:simplemap_dffe$1758CLBLM_R_X5Y119_SLICE_X7Y119_C5_FDRE  (
    .C(clk),
    .CE(_099_),
    .D(\sw[4] ),
    .Q(_008_),
    .R(1'h0)
  );
  (* BEL = "AFF" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:2174.5-2180.4|../../techmap/bels2vpr_map.v:480.3-480.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:442:simplemap_dffe$1759CLBLM_R_X7Y120_SLICE_X8Y120_A_FDRE  (
    .C(clk),
    .CE(_099_),
    .D(\sw[5] ),
    .Q(_009_),
    .R(1'h0)
  );
  (* BEL = "BFF" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:2187.5-2193.4|../../techmap/bels2vpr_map.v:480.3-480.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:442:simplemap_dffe$1760CLBLM_R_X7Y120_SLICE_X8Y120_B_FDRE  (
    .C(clk),
    .CE(_099_),
    .D(\sw[6] ),
    .Q(_000_),
    .R(1'h0)
  );
  (* BEL = "CFF" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:2200.5-2206.4|../../techmap/bels2vpr_map.v:480.3-480.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:442:simplemap_dffe$1761CLBLM_R_X7Y120_SLICE_X8Y120_C_FDRE  (
    .C(clk),
    .CE(_099_),
    .D(\sw[7] ),
    .Q(_001_),
    .R(1'h0)
  );
  (* BEL = "DFF" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:2213.5-2219.4|../../techmap/bels2vpr_map.v:480.3-480.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:442:simplemap_dffe$1762CLBLM_R_X7Y120_SLICE_X8Y120_D_FDRE  (
    .C(clk),
    .CE(_099_),
    .D(\sw[8] ),
    .Q(_002_),
    .R(1'h0)
  );
  (* BEL = "C5FF" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:2148.5-2154.4|../../techmap/bels2vpr_map.v:480.3-480.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:442:simplemap_dffe$1763CLBLM_R_X7Y120_SLICE_X8Y120_C5_FDRE  (
    .C(clk),
    .CE(_099_),
    .D(\sw[9] ),
    .Q(_003_),
    .R(1'h0)
  );
  (* BEL = "D5FF" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1679.5-1685.4|../../techmap/bels2vpr_map.v:480.3-480.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:442:simplemap_dffe$1766CLBLM_R_X5Y120_SLICE_X7Y120_D5_FDRE  (
    .C(clk),
    .CE(_101_),
    .D(\sw[0] ),
    .Q(_010_),
    .R(1'h0)
  );
  (* BEL = "A5FF" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1640.5-1646.4|../../techmap/bels2vpr_map.v:480.3-480.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:442:simplemap_dffe$1767CLBLM_R_X5Y120_SLICE_X7Y120_A5_FDRE  (
    .C(clk),
    .CE(_101_),
    .D(\sw[1] ),
    .Q(_011_),
    .R(1'h0)
  );
  (* BEL = "B5FF" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1653.5-1659.4|../../techmap/bels2vpr_map.v:480.3-480.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:442:simplemap_dffe$1768CLBLM_R_X5Y120_SLICE_X7Y120_B5_FDRE  (
    .C(clk),
    .CE(_101_),
    .D(\sw[2] ),
    .Q(_017_),
    .R(1'h0)
  );
  (* BEL = "AFF" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1692.5-1698.4|../../techmap/bels2vpr_map.v:480.3-480.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:442:simplemap_dffe$1769CLBLM_R_X5Y120_SLICE_X7Y120_A_FDRE  (
    .C(clk),
    .CE(_101_),
    .D(\sw[3] ),
    .Q(_018_),
    .R(1'h0)
  );
  (* BEL = "BFF" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1705.5-1711.4|../../techmap/bels2vpr_map.v:480.3-480.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:442:simplemap_dffe$1770CLBLM_R_X5Y120_SLICE_X7Y120_B_FDRE  (
    .C(clk),
    .CE(_101_),
    .D(\sw[4] ),
    .Q(_019_),
    .R(1'h0)
  );
  (* BEL = "CFF" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1718.5-1724.4|../../techmap/bels2vpr_map.v:480.3-480.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:442:simplemap_dffe$1771CLBLM_R_X5Y120_SLICE_X7Y120_C_FDRE  (
    .C(clk),
    .CE(_101_),
    .D(\sw[5] ),
    .Q(_020_),
    .R(1'h0)
  );
  (* BEL = "DFF" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1731.5-1737.4|../../techmap/bels2vpr_map.v:480.3-480.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:442:simplemap_dffe$1772CLBLM_R_X5Y120_SLICE_X7Y120_D_FDRE  (
    .C(clk),
    .CE(_101_),
    .D(\sw[6] ),
    .Q(_021_),
    .R(1'h0)
  );
  (* BEL = "C5FF" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1666.5-1672.4|../../techmap/bels2vpr_map.v:480.3-480.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) \$auto$simplemap.cc:442:simplemap_dffe$1773CLBLM_R_X5Y120_SLICE_X7Y120_C5_FDRE  (
    .C(clk),
    .CE(_101_),
    .D(\sw[7] ),
    .Q(_022_),
    .R(1'h0)
  );
  (* BEL = "DFF" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:2450.5-2456.4|../../techmap/bels2vpr_map.v:480.3-480.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h0)
  ) \$auto$simplemap.cc:559:simplemap_adffe_sdffe_sdffce$1726CLBLM_R_X7Y121_SLICE_X8Y121_D_FDRE  (
    .C(clk),
    .CE(\sw[11] ),
    .D(1'h1),
    .Q(_062_),
    .R(_102_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1254.5-1263.4|../../techmap/lut_simplif.v:19.5-26.4" *)
  LUT5 #(
    .INIT(32'd3418884872)
  ) \CLBLM_L_X8Y120_SLICE_X10Y120_ALUT.lut5_1  (
    .I0(_013_),
    .I1(\sw[15] ),
    .I2(\sw[14] ),
    .I3(_029_),
    .I4(\led[12] ),
    .O(_073_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1239.5-1248.4|../../techmap/lut_simplif.v:19.5-26.4" *)
  LUT5 #(
    .INIT(32'd3473588234)
  ) \CLBLM_L_X8Y120_SLICE_X10Y120_BLUT.lut5_1  (
    .I0(_030_),
    .I1(\led[13] ),
    .I2(\sw[14] ),
    .I3(\sw[15] ),
    .I4(_014_),
    .O(_074_)
  );
  (* BEL = "C5FF" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1184.5-1190.4|../../techmap/bels2vpr_map.v:480.3-480.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) CLBLM_L_X8Y120_SLICE_X10Y120_C5_FDRE (
    .C(clk),
    .CE(1'h1),
    .D(_074_),
    .Q(\led[13] ),
    .R(1'h0)
  );
  (* BEL = "D5FF" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1197.5-1203.4|../../techmap/bels2vpr_map.v:480.3-480.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) CLBLM_L_X8Y120_SLICE_X10Y120_D5_FDRE (
    .C(clk),
    .CE(1'h1),
    .D(_073_),
    .Q(\led[12] ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1340.5-1349.4|../../techmap/lut_simplif.v:19.5-26.4" *)
  LUT5 #(
    .INIT(32'd3418884872)
  ) \CLBLM_L_X8Y120_SLICE_X11Y120_ALUT.lut5_1  (
    .I0(_024_),
    .I1(\sw[15] ),
    .I2(\sw[14] ),
    .I3(_057_),
    .I4(\led[10] ),
    .O(_075_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1325.5-1334.4|../../techmap/lut_simplif.v:19.5-26.4" *)
  LUT5 #(
    .INIT(32'd3473588234)
  ) \CLBLM_L_X8Y120_SLICE_X11Y120_BLUT.lut5_1  (
    .I0(_032_),
    .I1(\led[15] ),
    .I2(\sw[14] ),
    .I3(\sw[15] ),
    .I4(_016_),
    .O(_076_)
  );
  (* BEL = "C5FF" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1270.5-1276.4|../../techmap/bels2vpr_map.v:480.3-480.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) CLBLM_L_X8Y120_SLICE_X11Y120_C5_FDRE (
    .C(clk),
    .CE(1'h1),
    .D(_076_),
    .Q(\led[15] ),
    .R(1'h0)
  );
  (* BEL = "D5FF" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1283.5-1289.4|../../techmap/bels2vpr_map.v:480.3-480.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) CLBLM_L_X8Y120_SLICE_X11Y120_D5_FDRE (
    .C(clk),
    .CE(1'h1),
    .D(_075_),
    .Q(\led[10] ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1426.5-1435.4|../../techmap/lut_simplif.v:30.9-30.66" *)
  MUXF6 \CLBLM_R_X5Y119_SLICE_X6Y119_ALUT.fpga_mux_0  (
    .I0(_077_),
    .I1(_078_),
    .O(_063_),
    .S(_038_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1426.5-1435.4|../../techmap/lut_simplif.v:8.5-15.4" *)
  LUT5 #(
    .INIT(32'd4024643363)
  ) \CLBLM_R_X5Y119_SLICE_X6Y119_ALUT.lut5_0  (
    .I0(_017_),
    .I1(\sw[14] ),
    .I2(\sw[15] ),
    .I3(_006_),
    .I4(\led[2] ),
    .O(_078_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1426.5-1435.4|../../techmap/lut_simplif.v:19.5-26.4" *)
  LUT5 #(
    .INIT(32'd3974114336)
  ) \CLBLM_R_X5Y119_SLICE_X6Y119_ALUT.lut5_1  (
    .I0(_017_),
    .I1(\sw[14] ),
    .I2(\sw[15] ),
    .I3(_006_),
    .I4(\led[2] ),
    .O(_077_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1411.5-1420.4|../../techmap/lut_simplif.v:30.9-30.66" *)
  MUXF6 \CLBLM_R_X5Y119_SLICE_X6Y119_BLUT.fpga_mux_0  (
    .I0(_079_),
    .I1(_080_),
    .O(_064_),
    .S(_055_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1411.5-1420.4|../../techmap/lut_simplif.v:8.5-15.4" *)
  LUT5 #(
    .INIT(32'd4208808157)
  ) \CLBLM_R_X5Y119_SLICE_X6Y119_BLUT.lut5_0  (
    .I0(\sw[14] ),
    .I1(_001_),
    .I2(_022_),
    .I3(\sw[15] ),
    .I4(\led[7] ),
    .O(_080_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1411.5-1420.4|../../techmap/lut_simplif.v:19.5-26.4" *)
  LUT5 #(
    .INIT(32'd4203237512)
  ) \CLBLM_R_X5Y119_SLICE_X6Y119_BLUT.lut5_1  (
    .I0(\sw[14] ),
    .I1(_001_),
    .I2(_022_),
    .I3(\sw[15] ),
    .I4(\led[7] ),
    .O(_079_)
  );
  (* BEL = "C5FF" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1356.5-1362.4|../../techmap/bels2vpr_map.v:480.3-480.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) CLBLM_R_X5Y119_SLICE_X6Y119_C5_FDRE (
    .C(clk),
    .CE(1'h1),
    .D(_064_),
    .Q(\led[7] ),
    .R(1'h0)
  );
  (* BEL = "D5FF" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1369.5-1375.4|../../techmap/bels2vpr_map.v:480.3-480.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) CLBLM_R_X5Y119_SLICE_X6Y119_D5_FDRE (
    .C(clk),
    .CE(1'h1),
    .D(_063_),
    .Q(\led[2] ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1624.5-1633.4|../../techmap/lut_simplif.v:30.9-30.66" *)
  MUXF6 \CLBLM_R_X5Y120_SLICE_X6Y120_ALUT.fpga_mux_0  (
    .I0(_081_),
    .I1(_082_),
    .O(_065_),
    .S(_027_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1624.5-1633.4|../../techmap/lut_simplif.v:8.5-15.4" *)
  LUT5 #(
    .INIT(32'd4024643363)
  ) \CLBLM_R_X5Y120_SLICE_X6Y120_ALUT.lut5_0  (
    .I0(_011_),
    .I1(\sw[14] ),
    .I2(\sw[15] ),
    .I3(_005_),
    .I4(\led[1] ),
    .O(_082_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1624.5-1633.4|../../techmap/lut_simplif.v:19.5-26.4" *)
  LUT5 #(
    .INIT(32'd3974114336)
  ) \CLBLM_R_X5Y120_SLICE_X6Y120_ALUT.lut5_1  (
    .I0(_011_),
    .I1(\sw[14] ),
    .I2(\sw[15] ),
    .I3(_005_),
    .I4(\led[1] ),
    .O(_081_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1609.5-1618.4|../../techmap/lut_simplif.v:30.9-30.66" *)
  MUXF6 \CLBLM_R_X5Y120_SLICE_X6Y120_BLUT.fpga_mux_0  (
    .I0(_083_),
    .I1(_084_),
    .O(_066_),
    .S(_058_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1609.5-1618.4|../../techmap/lut_simplif.v:8.5-15.4" *)
  LUT5 #(
    .INIT(32'd4208808157)
  ) \CLBLM_R_X5Y120_SLICE_X6Y120_BLUT.lut5_0  (
    .I0(\sw[14] ),
    .I1(_002_),
    .I2(_025_),
    .I3(\sw[15] ),
    .I4(\led[8] ),
    .O(_084_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1609.5-1618.4|../../techmap/lut_simplif.v:19.5-26.4" *)
  LUT5 #(
    .INIT(32'd4203237512)
  ) \CLBLM_R_X5Y120_SLICE_X6Y120_BLUT.lut5_1  (
    .I0(\sw[14] ),
    .I1(_002_),
    .I2(_025_),
    .I3(\sw[15] ),
    .I4(\led[8] ),
    .O(_083_)
  );
  (* BEL = "C5FF" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1554.5-1560.4|../../techmap/bels2vpr_map.v:480.3-480.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) CLBLM_R_X5Y120_SLICE_X6Y120_C5_FDRE (
    .C(clk),
    .CE(1'h1),
    .D(_066_),
    .Q(\led[8] ),
    .R(1'h0)
  );
  (* BEL = "D5FF" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1567.5-1573.4|../../techmap/bels2vpr_map.v:480.3-480.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) CLBLM_R_X5Y120_SLICE_X6Y120_D5_FDRE (
    .C(clk),
    .CE(1'h1),
    .D(_065_),
    .Q(\led[1] ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1874.5-1883.4|../../techmap/lut_simplif.v:30.9-30.66" *)
  MUXF6 \CLBLM_R_X5Y121_SLICE_X6Y121_ALUT.fpga_mux_0  (
    .I0(_085_),
    .I1(_086_),
    .O(_067_),
    .S(_049_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1874.5-1883.4|../../techmap/lut_simplif.v:8.5-15.4" *)
  LUT5 #(
    .INIT(32'd4224400139)
  ) \CLBLM_R_X5Y121_SLICE_X6Y121_ALUT.lut5_0  (
    .I0(_007_),
    .I1(\sw[14] ),
    .I2(\sw[15] ),
    .I3(_018_),
    .I4(\led[3] ),
    .O(_086_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1874.5-1883.4|../../techmap/lut_simplif.v:19.5-26.4" *)
  LUT5 #(
    .INIT(32'd4173871112)
  ) \CLBLM_R_X5Y121_SLICE_X6Y121_ALUT.lut5_1  (
    .I0(_007_),
    .I1(\sw[14] ),
    .I2(\sw[15] ),
    .I3(_018_),
    .I4(\led[3] ),
    .O(_085_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1859.5-1868.4|../../techmap/lut_simplif.v:30.9-30.66" *)
  MUXF6 \CLBLM_R_X5Y121_SLICE_X6Y121_BLUT.fpga_mux_0  (
    .I0(_087_),
    .I1(_088_),
    .O(_068_),
    .S(_054_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1859.5-1868.4|../../techmap/lut_simplif.v:8.5-15.4" *)
  LUT5 #(
    .INIT(32'd4208808157)
  ) \CLBLM_R_X5Y121_SLICE_X6Y121_BLUT.lut5_0  (
    .I0(\sw[14] ),
    .I1(_000_),
    .I2(_021_),
    .I3(\sw[15] ),
    .I4(\led[6] ),
    .O(_088_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1859.5-1868.4|../../techmap/lut_simplif.v:19.5-26.4" *)
  LUT5 #(
    .INIT(32'd4203237512)
  ) \CLBLM_R_X5Y121_SLICE_X6Y121_BLUT.lut5_1  (
    .I0(\sw[14] ),
    .I1(_000_),
    .I2(_021_),
    .I3(\sw[15] ),
    .I4(\led[6] ),
    .O(_087_)
  );
  (* BEL = "C5FF" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1804.5-1810.4|../../techmap/bels2vpr_map.v:480.3-480.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) CLBLM_R_X5Y121_SLICE_X6Y121_C5_FDRE (
    .C(clk),
    .CE(1'h1),
    .D(_068_),
    .Q(\led[6] ),
    .R(1'h0)
  );
  (* BEL = "D5FF" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1817.5-1823.4|../../techmap/bels2vpr_map.v:480.3-480.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) CLBLM_R_X5Y121_SLICE_X6Y121_D5_FDRE (
    .C(clk),
    .CE(1'h1),
    .D(_067_),
    .Q(\led[3] ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1960.5-1969.4|../../techmap/lut_simplif.v:30.9-30.66" *)
  MUXF6 \CLBLM_R_X5Y121_SLICE_X7Y121_ALUT.fpga_mux_0  (
    .I0(_089_),
    .I1(_090_),
    .O(_069_),
    .S(_052_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1960.5-1969.4|../../techmap/lut_simplif.v:8.5-15.4" *)
  LUT5 #(
    .INIT(32'd4024643363)
  ) \CLBLM_R_X5Y121_SLICE_X7Y121_ALUT.lut5_0  (
    .I0(_019_),
    .I1(\sw[14] ),
    .I2(\sw[15] ),
    .I3(_008_),
    .I4(\led[4] ),
    .O(_090_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1960.5-1969.4|../../techmap/lut_simplif.v:19.5-26.4" *)
  LUT5 #(
    .INIT(32'd3974114336)
  ) \CLBLM_R_X5Y121_SLICE_X7Y121_ALUT.lut5_1  (
    .I0(_019_),
    .I1(\sw[14] ),
    .I2(\sw[15] ),
    .I3(_008_),
    .I4(\led[4] ),
    .O(_089_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1945.5-1954.4|../../techmap/lut_simplif.v:30.9-30.66" *)
  MUXF6 \CLBLM_R_X5Y121_SLICE_X7Y121_BLUT.fpga_mux_0  (
    .I0(_091_),
    .I1(_092_),
    .O(_070_),
    .S(_053_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1945.5-1954.4|../../techmap/lut_simplif.v:8.5-15.4" *)
  LUT5 #(
    .INIT(32'd4208808157)
  ) \CLBLM_R_X5Y121_SLICE_X7Y121_BLUT.lut5_0  (
    .I0(\sw[14] ),
    .I1(_009_),
    .I2(_020_),
    .I3(\sw[15] ),
    .I4(\led[5] ),
    .O(_092_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1945.5-1954.4|../../techmap/lut_simplif.v:19.5-26.4" *)
  LUT5 #(
    .INIT(32'd4203237512)
  ) \CLBLM_R_X5Y121_SLICE_X7Y121_BLUT.lut5_1  (
    .I0(\sw[14] ),
    .I1(_009_),
    .I2(_020_),
    .I3(\sw[15] ),
    .I4(\led[5] ),
    .O(_091_)
  );
  (* BEL = "C5FF" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1890.5-1896.4|../../techmap/bels2vpr_map.v:480.3-480.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) CLBLM_R_X5Y121_SLICE_X7Y121_C5_FDRE (
    .C(clk),
    .CE(1'h1),
    .D(_070_),
    .Q(\led[5] ),
    .R(1'h0)
  );
  (* BEL = "D5FF" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1903.5-1909.4|../../techmap/bels2vpr_map.v:480.3-480.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) CLBLM_R_X5Y121_SLICE_X7Y121_D5_FDRE (
    .C(clk),
    .CE(1'h1),
    .D(_069_),
    .Q(\led[4] ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:2046.5-2055.4|../../techmap/lut_simplif.v:30.9-30.66" *)
  MUXF6 \CLBLM_R_X7Y119_SLICE_X8Y119_ALUT.fpga_mux_0  (
    .I0(_093_),
    .I1(_094_),
    .O(_071_),
    .S(_026_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:2046.5-2055.4|../../techmap/lut_simplif.v:8.5-15.4" *)
  LUT5 #(
    .INIT(32'd4224400139)
  ) \CLBLM_R_X7Y119_SLICE_X8Y119_ALUT.lut5_0  (
    .I0(_004_),
    .I1(\sw[14] ),
    .I2(\sw[15] ),
    .I3(_010_),
    .I4(\led[0] ),
    .O(_094_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:2046.5-2055.4|../../techmap/lut_simplif.v:19.5-26.4" *)
  LUT5 #(
    .INIT(32'd4173871112)
  ) \CLBLM_R_X7Y119_SLICE_X8Y119_ALUT.lut5_1  (
    .I0(_004_),
    .I1(\sw[14] ),
    .I2(\sw[15] ),
    .I3(_010_),
    .I4(\led[0] ),
    .O(_093_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:2031.5-2040.4|../../techmap/lut_simplif.v:30.9-30.66" *)
  MUXF6 \CLBLM_R_X7Y119_SLICE_X8Y119_BLUT.fpga_mux_0  (
    .I0(_095_),
    .I1(_096_),
    .O(_072_),
    .S(_056_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:2031.5-2040.4|../../techmap/lut_simplif.v:8.5-15.4" *)
  LUT5 #(
    .INIT(32'd4009051381)
  ) \CLBLM_R_X7Y119_SLICE_X8Y119_BLUT.lut5_0  (
    .I0(\sw[14] ),
    .I1(_023_),
    .I2(_003_),
    .I3(\sw[15] ),
    .I4(\led[9] ),
    .O(_096_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:2031.5-2040.4|../../techmap/lut_simplif.v:19.5-26.4" *)
  LUT5 #(
    .INIT(32'd4003480736)
  ) \CLBLM_R_X7Y119_SLICE_X8Y119_BLUT.lut5_1  (
    .I0(\sw[14] ),
    .I1(_023_),
    .I2(_003_),
    .I3(\sw[15] ),
    .I4(\led[9] ),
    .O(_095_)
  );
  (* BEL = "C5FF" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1976.5-1982.4|../../techmap/bels2vpr_map.v:480.3-480.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) CLBLM_R_X7Y119_SLICE_X8Y119_C5_FDRE (
    .C(clk),
    .CE(1'h1),
    .D(_072_),
    .Q(\led[9] ),
    .R(1'h0)
  );
  (* BEL = "D5FF" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1989.5-1995.4|../../techmap/bels2vpr_map.v:480.3-480.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) CLBLM_R_X7Y119_SLICE_X8Y119_D5_FDRE (
    .C(clk),
    .CE(1'h1),
    .D(_071_),
    .Q(\led[0] ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:2132.5-2141.4|../../techmap/lut_simplif.v:19.5-26.4" *)
  LUT5 #(
    .INIT(32'd3418884872)
  ) \CLBLM_R_X7Y119_SLICE_X9Y119_ALUT.lut5_1  (
    .I0(_012_),
    .I1(\sw[15] ),
    .I2(\sw[14] ),
    .I3(_028_),
    .I4(\led[11] ),
    .O(_097_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:2117.5-2126.4|../../techmap/lut_simplif.v:19.5-26.4" *)
  LUT5 #(
    .INIT(32'd3473588234)
  ) \CLBLM_R_X7Y119_SLICE_X9Y119_BLUT.lut5_1  (
    .I0(_031_),
    .I1(\led[14] ),
    .I2(\sw[14] ),
    .I3(\sw[15] ),
    .I4(_015_),
    .O(_098_)
  );
  (* BEL = "C5FF" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:2062.5-2068.4|../../techmap/bels2vpr_map.v:480.3-480.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) CLBLM_R_X7Y119_SLICE_X9Y119_C5_FDRE (
    .C(clk),
    .CE(1'h1),
    .D(_098_),
    .Q(\led[14] ),
    .R(1'h0)
  );
  (* BEL = "D5FF" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:2075.5-2081.4|../../techmap/bels2vpr_map.v:480.3-480.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) CLBLM_R_X7Y119_SLICE_X9Y119_D5_FDRE (
    .C(clk),
    .CE(1'h1),
    .D(_097_),
    .Q(\led[11] ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:2270.5-2279.4|../../techmap/lut_simplif.v:8.5-15.4" *)
  LUT2 #(
    .INIT(4'h2)
  ) \CLBLM_R_X7Y120_SLICE_X8Y120_ALUT.lut5_0  (
    .I0(\sw[11] ),
    .I1(\sw[13] ),
    .O(_100_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:2270.5-2279.4|../../techmap/lut_simplif.v:19.5-26.4" *)
  LUT2 #(
    .INIT(4'h4)
  ) \CLBLM_R_X7Y120_SLICE_X8Y120_ALUT.lut5_1  (
    .I0(\sw[12] ),
    .I1(_100_),
    .O(_099_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:2255.5-2264.4|../../techmap/lut_simplif.v:8.5-15.4" *)
  LUT3 #(
    .INIT(8'h2a)
  ) \CLBLM_R_X7Y120_SLICE_X8Y120_BLUT.lut5_0  (
    .I0(\sw[11] ),
    .I1(\sw[12] ),
    .I2(\sw[13] ),
    .O(_102_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:2255.5-2264.4|../../techmap/lut_simplif.v:19.5-26.4" *)
  LUT2 #(
    .INIT(4'h8)
  ) \CLBLM_R_X7Y120_SLICE_X8Y120_BLUT.lut5_1  (
    .I0(\sw[12] ),
    .I1(_100_),
    .O(_101_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:2225.5-2234.4|../../techmap/lut_simplif.v:8.5-15.4" *)
  LUT3 #(
    .INIT(8'h20)
  ) \CLBLM_R_X7Y120_SLICE_X8Y120_DLUT.lut5_0  (
    .I0(\sw[11] ),
    .I1(\sw[12] ),
    .I2(\sw[13] ),
    .O(_103_)
  );
  (* BEL = "RAMB18E1" *)
  (* DONT_TOUCH = 32'd1 *)
  (* KEEP = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "top_bit.v:1154.5-1177.4|../../techmap/bels2vpr_map.v:432.5-461.4" *)
  RAMB18E1_VPR #(
    .DOA_REG(32'sd0),
    .DOB_REG(32'sd0),
    .INITP_00(256'h0000000000000000000000000000000000000000000000000000000000004450),
    .INITP_01(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INITP_02(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INITP_03(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INITP_04(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INITP_05(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INITP_06(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INITP_07(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_00(256'h00000000000000000000000000040002193366cc070f78f07fff2a5555aa0001),
    .INIT_01(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_02(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_03(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_04(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_05(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_06(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_07(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_08(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_09(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_0A(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_0B(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_0C(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_0D(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_0E(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_0F(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_10(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_11(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_12(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_13(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_14(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_15(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_16(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_17(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_18(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_19(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_1A(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_1B(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_1C(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_1D(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_1E(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_1F(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_20(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_21(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_22(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_23(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_24(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_25(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_26(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_27(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_28(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_29(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_2A(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_2B(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_2C(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_2D(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_2E(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_2F(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_30(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_31(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_32(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_33(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_34(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_35(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_36(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_37(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_38(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_39(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_3A(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_3B(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_3C(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_3D(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_3E(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_3F(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .IN_USE(1'h1),
    .READ_WIDTH_A_1(1'h0),
    .READ_WIDTH_A_18(1'h1),
    .READ_WIDTH_A_2(1'h0),
    .READ_WIDTH_A_4(1'h0),
    .READ_WIDTH_A_9(1'h0),
    .READ_WIDTH_B_1(1'h0),
    .READ_WIDTH_B_18(1'h1),
    .READ_WIDTH_B_2(1'h0),
    .READ_WIDTH_B_4(1'h0),
    .READ_WIDTH_B_9(1'h0),
    .SDP_READ_WIDTH_36(1'h0),
    .SDP_WRITE_WIDTH_36(1'h0),
    .WRITE_MODE_A_NO_CHANGE(1'h0),
    .WRITE_MODE_A_READ_FIRST(1'h1),
    .WRITE_MODE_B_NO_CHANGE(1'h0),
    .WRITE_MODE_B_READ_FIRST(1'h1),
    .WRITE_WIDTH_A_1(1'h0),
    .WRITE_WIDTH_A_18(1'h1),
    .WRITE_WIDTH_A_2(1'h0),
    .WRITE_WIDTH_A_4(1'h0),
    .WRITE_WIDTH_A_9(1'h0),
    .WRITE_WIDTH_B_1(1'h0),
    .WRITE_WIDTH_B_18(1'h1),
    .WRITE_WIDTH_B_2(1'h0),
    .WRITE_WIDTH_B_4(1'h0),
    .WRITE_WIDTH_B_9(1'h0),
    .Y0_READ_WIDTH_A_1(1'h0),
    .Y0_READ_WIDTH_A_18(1'h1),
    .Y1_READ_WIDTH_A_1(1'h0),
    .Y1_READ_WIDTH_A_18(1'h1),
    .ZINIT_A(18'h3ffff),
    .ZINIT_B(18'h3ffff),
    .ZINV_CLKARDCLK(1'h1),
    .ZINV_CLKBWRCLK(1'h1),
    .ZINV_ENARDEN(1'h1),
    .ZINV_ENBWREN(1'h1),
    .ZINV_REGCLKARDRCLK(1'h0),
    .ZINV_REGCLKB(1'h0),
    .ZINV_RSTRAMARSTRAM(1'h0),
    .ZINV_RSTRAMB(1'h0),
    .ZINV_RSTREGARSTREG(1'h0),
    .ZINV_RSTREGB(1'h0),
    .ZSRVAL_A(18'h3ffff),
    .ZSRVAL_B(18'h3ffff)
  ) \ram.ram.0.0.0BRAM_L_X6Y120_RAMB18_X0Y48_RAMB18E1  (
    .ADDRARDADDR({ _003_, _002_, _001_, _000_, _009_, _008_, _007_, _006_, _005_, _004_, 4'h0 }),
    .ADDRATIEHIGH(2'h3),
    .ADDRBTIEHIGH(2'h3),
    .ADDRBWRADDR({ _003_, _002_, _001_, _000_, _009_, _008_, _007_, _006_, _005_, _004_, 4'h0 }),
    .CLKARDCLK(clk),
    .CLKBWRCLK(clk),
    .DIADI(16'h0000),
    .DIBDI({ 1'h0, _016_, _015_, _014_, _013_, _012_, _024_, _023_, _022_, _021_, _020_, _019_, _018_, _017_, _011_, _010_ }),
    .DIPADIP(2'h0),
    .DIPBDIP({ 1'h0, _025_ }),
    .DOADO({ _033_, _032_, _031_, _030_, _029_, _028_, _057_, _056_, _055_, _054_, _053_, _052_, _049_, _038_, _027_, _026_ }),
    .DOBDO({ _051_, _050_, _048_, _047_, _046_, _045_, _044_, _043_, _042_, _041_, _040_, _039_, _037_, _036_, _035_, _034_ }),
    .DOPADOP({ _059_, _058_ }),
    .DOPBDOP({ _061_, _060_ }),
    .ENARDEN(1'h1),
    .ENBWREN(1'h1),
    .REGCEAREGCE(1'h1),
    .REGCEB(1'h0),
    .REGCLKARDRCLK(1'h1),
    .REGCLKB(1'h1),
    .RSTRAMARSTRAM(1'h1),
    .RSTRAMB(1'h1),
    .RSTREGARSTREG(1'h1),
    .RSTREGB(1'h1),
    .WEA(4'h0),
    .WEBWE({ 4'h0, _062_, _062_, _062_, _062_ })
  );
  assign tx = rx;
endmodule
