/* Generated by Yosys 0.9+3885 (git sha1 afcc31ce, clang 11.0.1 -fPIC -Os) */

(* top =  1  *)
(* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:42.1-134.10" *)
module top(clk, rx, tx, \sw[0] , \sw[1] , \sw[2] , \sw[3] , \sw[4] , \sw[5] , \sw[6] , \sw[7] , \sw[8] , \sw[9] , \sw[10] , \sw[11] , \sw[12] , \sw[13] , \sw[14] , \sw[15] , \led[0] , \led[1] , \led[2] , \led[3] , \led[4] , \led[5] , \led[6] , \led[7] , \led[8] , \led[9] , \led[10] , \led[11] , \led[12] , \led[13] , \led[14] , \led[15] );
  (* src = "top_synth.v:6.8-6.13" *)
  wire \$auto$rename.cc:294:execute$476 ;
  (* src = "top_synth.v:7.8-7.13" *)
  wire \$auto$rename.cc:294:execute$477 ;
  (* src = "top_synth.v:8.8-8.13" *)
  wire \$auto$rename.cc:294:execute$478 ;
  (* src = "top_synth.v:9.8-9.13" *)
  wire \$auto$rename.cc:294:execute$479 ;
  (* src = "top_synth.v:10.8-10.13" *)
  wire \$auto$rename.cc:294:execute$480 ;
  (* src = "top_synth.v:11.8-11.13" *)
  wire \$auto$rename.cc:294:execute$481 ;
  (* src = "top_synth.v:12.8-12.13" *)
  wire \$auto$rename.cc:294:execute$482 ;
  (* src = "top_synth.v:13.8-13.13" *)
  wire \$auto$rename.cc:294:execute$483 ;
  (* src = "top_synth.v:14.8-14.13" *)
  wire \$auto$rename.cc:294:execute$484 ;
  (* src = "top_synth.v:15.8-15.13" *)
  wire \$auto$rename.cc:294:execute$485 ;
  (* src = "top_synth.v:16.8-16.13" *)
  wire \$auto$rename.cc:294:execute$486 ;
  (* src = "top_synth.v:17.8-17.13" *)
  wire \$auto$rename.cc:294:execute$487 ;
  (* src = "top_synth.v:18.8-18.13" *)
  wire \$auto$rename.cc:294:execute$488 ;
  (* src = "top_synth.v:19.8-19.13" *)
  wire \$auto$rename.cc:294:execute$489 ;
  (* src = "top_synth.v:20.8-20.13" *)
  wire \$auto$rename.cc:294:execute$490 ;
  (* src = "top_synth.v:21.8-21.13" *)
  wire \$auto$rename.cc:294:execute$491 ;
  (* src = "top_synth.v:22.8-22.13" *)
  wire \$auto$rename.cc:294:execute$492 ;
  (* src = "top_synth.v:23.8-23.13" *)
  wire \$auto$rename.cc:294:execute$493 ;
  (* src = "top_synth.v:24.8-24.13" *)
  wire \$auto$rename.cc:294:execute$494 ;
  (* src = "top_synth.v:25.8-25.13" *)
  wire \$auto$rename.cc:294:execute$495 ;
  (* src = "top_synth.v:27.15-27.20" *)
  wire \$auto$rename.cc:294:execute$496 ;
  (* src = "top_synth.v:27.15-27.20" *)
  wire \$auto$rename.cc:294:execute$497 ;
  (* src = "top_synth.v:27.15-27.20" *)
  wire \$auto$rename.cc:294:execute$498 ;
  (* src = "top_synth.v:27.15-27.20" *)
  wire \$auto$rename.cc:294:execute$499 ;
  (* src = "top_synth.v:27.15-27.20" *)
  wire \$auto$rename.cc:294:execute$500 ;
  (* src = "top_synth.v:27.15-27.20" *)
  wire \$auto$rename.cc:294:execute$501 ;
  (* src = "top_synth.v:27.15-27.20" *)
  wire \$auto$rename.cc:294:execute$502 ;
  (* src = "top_synth.v:27.15-27.20" *)
  (* unused_bits = "0" *)
  wire \$auto$rename.cc:294:execute$503 ;
  (* src = "top_synth.v:27.15-27.20" *)
  (* unused_bits = "0" *)
  wire \$auto$rename.cc:294:execute$504 ;
  (* src = "top_synth.v:27.15-27.20" *)
  wire \$auto$rename.cc:294:execute$505 ;
  (* src = "top_synth.v:27.15-27.20" *)
  wire \$auto$rename.cc:294:execute$506 ;
  (* src = "top_synth.v:27.15-27.20" *)
  wire \$auto$rename.cc:294:execute$507 ;
  (* src = "top_synth.v:27.15-27.20" *)
  wire \$auto$rename.cc:294:execute$508 ;
  (* src = "top_synth.v:27.15-27.20" *)
  wire \$auto$rename.cc:294:execute$509 ;
  (* src = "top_synth.v:27.15-27.20" *)
  wire \$auto$rename.cc:294:execute$510 ;
  (* src = "top_synth.v:27.15-27.20" *)
  wire \$auto$rename.cc:294:execute$511 ;
  (* src = "top_synth.v:27.15-27.20" *)
  wire \$auto$rename.cc:294:execute$512 ;
  (* src = "top_synth.v:27.15-27.20" *)
  wire \$auto$rename.cc:294:execute$513 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:242.8-242.10" *)
  wire \$auto$rename.cc:294:execute$514 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:242.12-242.14" *)
  wire \$auto$rename.cc:294:execute$515 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:242.8-242.10" *)
  wire \$auto$rename.cc:294:execute$516 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:242.12-242.14" *)
  wire \$auto$rename.cc:294:execute$517 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:242.8-242.10" *)
  wire \$auto$rename.cc:294:execute$518 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:242.12-242.14" *)
  wire \$auto$rename.cc:294:execute$519 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:242.8-242.10" *)
  wire \$auto$rename.cc:294:execute$520 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:242.12-242.14" *)
  wire \$auto$rename.cc:294:execute$521 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:242.8-242.10" *)
  wire \$auto$rename.cc:294:execute$522 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:242.12-242.14" *)
  wire \$auto$rename.cc:294:execute$523 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:242.8-242.10" *)
  wire \$auto$rename.cc:294:execute$524 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:242.12-242.14" *)
  wire \$auto$rename.cc:294:execute$525 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:242.8-242.10" *)
  wire \$auto$rename.cc:294:execute$526 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:242.12-242.14" *)
  wire \$auto$rename.cc:294:execute$527 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:242.8-242.10" *)
  wire \$auto$rename.cc:294:execute$528 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:242.12-242.14" *)
  wire \$auto$rename.cc:294:execute$529 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:242.8-242.10" *)
  wire \$auto$rename.cc:294:execute$530 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:242.12-242.14" *)
  wire \$auto$rename.cc:294:execute$531 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:242.8-242.10" *)
  wire \$auto$rename.cc:294:execute$532 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:242.12-242.14" *)
  wire \$auto$rename.cc:294:execute$533 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/xc7_brams_map.v:277.14-277.19" *)
  (* unused_bits = "0" *)
  wire \$auto$rename.cc:294:execute$534 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/xc7_brams_map.v:277.14-277.19" *)
  (* unused_bits = "0" *)
  wire \$auto$rename.cc:294:execute$535 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/xc7_brams_map.v:277.14-277.19" *)
  (* unused_bits = "0" *)
  wire \$auto$rename.cc:294:execute$536 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/xc7_brams_map.v:277.14-277.19" *)
  (* unused_bits = "0" *)
  wire \$auto$rename.cc:294:execute$537 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/xc7_brams_map.v:277.14-277.19" *)
  (* unused_bits = "0" *)
  wire \$auto$rename.cc:294:execute$538 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/xc7_brams_map.v:277.14-277.19" *)
  (* unused_bits = "0" *)
  wire \$auto$rename.cc:294:execute$539 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/xc7_brams_map.v:277.14-277.19" *)
  (* unused_bits = "0" *)
  wire \$auto$rename.cc:294:execute$540 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/xc7_brams_map.v:277.14-277.19" *)
  (* unused_bits = "0" *)
  wire \$auto$rename.cc:294:execute$541 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/xc7_brams_map.v:277.14-277.19" *)
  (* unused_bits = "0" *)
  wire \$auto$rename.cc:294:execute$542 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/xc7_brams_map.v:277.14-277.19" *)
  (* unused_bits = "0" *)
  wire \$auto$rename.cc:294:execute$543 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/xc7_brams_map.v:277.14-277.19" *)
  (* unused_bits = "0" *)
  wire \$auto$rename.cc:294:execute$544 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/xc7_brams_map.v:277.14-277.19" *)
  (* unused_bits = "0" *)
  wire \$auto$rename.cc:294:execute$545 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/xc7_brams_map.v:277.14-277.19" *)
  (* unused_bits = "0" *)
  wire \$auto$rename.cc:294:execute$546 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/xc7_brams_map.v:277.14-277.19" *)
  (* unused_bits = "0" *)
  wire \$auto$rename.cc:294:execute$547 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/xc7_brams_map.v:277.14-277.19" *)
  (* unused_bits = "0" *)
  wire \$auto$rename.cc:294:execute$548 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/xc7_brams_map.v:277.14-277.19" *)
  (* unused_bits = "0" *)
  wire \$auto$rename.cc:294:execute$549 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/xc7_brams_map.v:278.13-278.20" *)
  (* unused_bits = "0" *)
  wire \$auto$rename.cc:294:execute$550 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/xc7_brams_map.v:278.13-278.20" *)
  (* unused_bits = "0" *)
  wire \$auto$rename.cc:294:execute$551 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire \$auto$rename.cc:294:execute$552 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:68.15-68.26" *)
  wire \$auto$rename.cc:294:execute$553 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:68.15-68.26" *)
  wire \$auto$rename.cc:294:execute$554 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:68.15-68.26" *)
  wire \$auto$rename.cc:294:execute$555 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:68.15-68.26" *)
  wire \$auto$rename.cc:294:execute$556 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:68.15-68.26" *)
  wire \$auto$rename.cc:294:execute$557 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:68.15-68.26" *)
  wire \$auto$rename.cc:294:execute$558 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:68.15-68.26" *)
  wire \$auto$rename.cc:294:execute$559 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:68.15-68.26" *)
  wire \$auto$rename.cc:294:execute$560 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:68.15-68.26" *)
  wire \$auto$rename.cc:294:execute$561 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:68.15-68.26" *)
  wire \$auto$rename.cc:294:execute$562 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:69.16-69.24" *)
  wire \$auto$rename.cc:294:execute$563 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:69.16-69.24" *)
  wire \$auto$rename.cc:294:execute$564 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:69.16-69.24" *)
  wire \$auto$rename.cc:294:execute$565 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:69.16-69.24" *)
  wire \$auto$rename.cc:294:execute$566 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:69.16-69.24" *)
  wire \$auto$rename.cc:294:execute$567 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:69.16-69.24" *)
  wire \$auto$rename.cc:294:execute$568 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:69.16-69.24" *)
  wire \$auto$rename.cc:294:execute$569 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:69.16-69.24" *)
  wire \$auto$rename.cc:294:execute$570 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:69.16-69.24" *)
  wire \$auto$rename.cc:294:execute$571 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:69.16-69.24" *)
  wire \$auto$rename.cc:294:execute$572 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:69.16-69.24" *)
  wire \$auto$rename.cc:294:execute$573 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:69.16-69.24" *)
  wire \$auto$rename.cc:294:execute$574 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:69.16-69.24" *)
  wire \$auto$rename.cc:294:execute$575 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:69.16-69.24" *)
  wire \$auto$rename.cc:294:execute$576 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:69.16-69.24" *)
  wire \$auto$rename.cc:294:execute$577 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:69.16-69.24" *)
  wire \$auto$rename.cc:294:execute$578 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:57.10-66.6|/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:5.11-5.15" *)
  wire \$auto$rename.cc:294:execute$579 ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:43.17-43.20" *)
  input clk;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:49.24-49.27" *)
  output \led[0] ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:49.24-49.27" *)
  output \led[10] ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:49.24-49.27" *)
  output \led[11] ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:49.24-49.27" *)
  output \led[12] ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:49.24-49.27" *)
  output \led[13] ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:49.24-49.27" *)
  output \led[14] ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:49.24-49.27" *)
  output \led[15] ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:49.24-49.27" *)
  output \led[1] ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:49.24-49.27" *)
  output \led[2] ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:49.24-49.27" *)
  output \led[3] ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:49.24-49.27" *)
  output \led[4] ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:49.24-49.27" *)
  output \led[5] ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:49.24-49.27" *)
  output \led[6] ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:49.24-49.27" *)
  output \led[7] ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:49.24-49.27" *)
  output \led[8] ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:49.24-49.27" *)
  output \led[9] ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:45.17-45.19" *)
  input rx;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:48.24-48.26" *)
  input \sw[0] ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:48.24-48.26" *)
  input \sw[10] ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:48.24-48.26" *)
  input \sw[11] ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:48.24-48.26" *)
  input \sw[12] ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:48.24-48.26" *)
  input \sw[13] ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:48.24-48.26" *)
  input \sw[14] ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:48.24-48.26" *)
  input \sw[15] ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:48.24-48.26" *)
  input \sw[1] ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:48.24-48.26" *)
  input \sw[2] ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:48.24-48.26" *)
  input \sw[3] ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:48.24-48.26" *)
  input \sw[4] ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:48.24-48.26" *)
  input \sw[5] ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:48.24-48.26" *)
  input \sw[6] ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:48.24-48.26" *)
  input \sw[7] ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:48.24-48.26" *)
  input \sw[8] ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:48.24-48.26" *)
  input \sw[9] ;
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:46.17-46.19" *)
  output tx;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:201.5-204.4|/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h4)
  ) _102_ (
    .I0(\sw[13] ),
    .I1(\sw[11] ),
    .O(\$auto$rename.cc:294:execute$552 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:212.5-215.4|/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h20)
  ) _103_ (
    .I0(\sw[13] ),
    .I1(\sw[12] ),
    .I2(\sw[11] ),
    .O(\$auto$rename.cc:294:execute$476 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:201.5-204.4|/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h8)
  ) _104_ (
    .I0(\sw[12] ),
    .I1(\$auto$rename.cc:294:execute$552 ),
    .O(\$auto$rename.cc:294:execute$477 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:201.5-204.4|/usr/local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h4)
  ) _105_ (
    .I0(\sw[12] ),
    .I1(\$auto$rename.cc:294:execute$552 ),
    .O(\$auto$rename.cc:294:execute$478 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:212.5-215.4|/usr/local/bin/../share/yosys/xilinx/lut_map.v:47.26-48.41" *)
  LUT3 #(
    .INIT(8'h70)
  ) _106_ (
    .I0(\sw[13] ),
    .I1(\sw[12] ),
    .I2(\sw[11] ),
    .O(\$auto$rename.cc:294:execute$479 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:107.5-130.8|/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) _107_ (
    .C(clk),
    .CE(\$auto$rename.cc:294:execute$476 ),
    .D(\sw[0] ),
    .Q(\$auto$rename.cc:294:execute$577 ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:107.5-130.8|/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) _108_ (
    .C(clk),
    .CE(\$auto$rename.cc:294:execute$476 ),
    .D(\sw[1] ),
    .Q(\$auto$rename.cc:294:execute$578 ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:107.5-130.8|/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) _109_ (
    .C(clk),
    .CE(\$auto$rename.cc:294:execute$476 ),
    .D(\sw[2] ),
    .Q(\$auto$rename.cc:294:execute$564 ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:107.5-130.8|/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) _110_ (
    .C(clk),
    .CE(\$auto$rename.cc:294:execute$476 ),
    .D(\sw[3] ),
    .Q(\$auto$rename.cc:294:execute$565 ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:107.5-130.8|/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) _111_ (
    .C(clk),
    .CE(\$auto$rename.cc:294:execute$476 ),
    .D(\sw[4] ),
    .Q(\$auto$rename.cc:294:execute$566 ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:107.5-130.8|/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) _112_ (
    .C(clk),
    .CE(\$auto$rename.cc:294:execute$476 ),
    .D(\sw[5] ),
    .Q(\$auto$rename.cc:294:execute$567 ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:107.5-130.8|/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) _113_ (
    .C(clk),
    .CE(\$auto$rename.cc:294:execute$476 ),
    .D(\sw[6] ),
    .Q(\$auto$rename.cc:294:execute$568 ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:107.5-130.8|/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) _114_ (
    .C(clk),
    .CE(\$auto$rename.cc:294:execute$476 ),
    .D(\sw[7] ),
    .Q(\$auto$rename.cc:294:execute$569 ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:107.5-130.8|/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) _115_ (
    .C(clk),
    .CE(1'h1),
    .D(\$auto$rename.cc:294:execute$480 ),
    .Q(\led[0] ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:107.5-130.8|/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) _116_ (
    .C(clk),
    .CE(1'h1),
    .D(\$auto$rename.cc:294:execute$481 ),
    .Q(\led[1] ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:107.5-130.8|/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) _117_ (
    .C(clk),
    .CE(1'h1),
    .D(\$auto$rename.cc:294:execute$482 ),
    .Q(\led[2] ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:107.5-130.8|/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) _118_ (
    .C(clk),
    .CE(1'h1),
    .D(\$auto$rename.cc:294:execute$483 ),
    .Q(\led[3] ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:107.5-130.8|/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) _119_ (
    .C(clk),
    .CE(1'h1),
    .D(\$auto$rename.cc:294:execute$484 ),
    .Q(\led[4] ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:107.5-130.8|/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) _120_ (
    .C(clk),
    .CE(1'h1),
    .D(\$auto$rename.cc:294:execute$485 ),
    .Q(\led[5] ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:107.5-130.8|/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) _121_ (
    .C(clk),
    .CE(1'h1),
    .D(\$auto$rename.cc:294:execute$486 ),
    .Q(\led[6] ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:107.5-130.8|/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) _122_ (
    .C(clk),
    .CE(1'h1),
    .D(\$auto$rename.cc:294:execute$487 ),
    .Q(\led[7] ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:107.5-130.8|/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) _123_ (
    .C(clk),
    .CE(1'h1),
    .D(\$auto$rename.cc:294:execute$488 ),
    .Q(\led[8] ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:107.5-130.8|/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) _124_ (
    .C(clk),
    .CE(1'h1),
    .D(\$auto$rename.cc:294:execute$489 ),
    .Q(\led[9] ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:107.5-130.8|/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) _125_ (
    .C(clk),
    .CE(1'h1),
    .D(\$auto$rename.cc:294:execute$490 ),
    .Q(\led[10] ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:107.5-130.8|/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) _126_ (
    .C(clk),
    .CE(1'h1),
    .D(\$auto$rename.cc:294:execute$491 ),
    .Q(\led[11] ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:107.5-130.8|/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) _127_ (
    .C(clk),
    .CE(1'h1),
    .D(\$auto$rename.cc:294:execute$492 ),
    .Q(\led[12] ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:107.5-130.8|/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) _128_ (
    .C(clk),
    .CE(1'h1),
    .D(\$auto$rename.cc:294:execute$493 ),
    .Q(\led[13] ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:107.5-130.8|/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) _129_ (
    .C(clk),
    .CE(1'h1),
    .D(\$auto$rename.cc:294:execute$494 ),
    .Q(\led[14] ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:107.5-130.8|/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) _130_ (
    .C(clk),
    .CE(1'h1),
    .D(\$auto$rename.cc:294:execute$495 ),
    .Q(\led[15] ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:107.5-130.8|/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) _131_ (
    .C(clk),
    .CE(\$auto$rename.cc:294:execute$478 ),
    .D(\sw[0] ),
    .Q(\$auto$rename.cc:294:execute$553 ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:107.5-130.8|/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) _132_ (
    .C(clk),
    .CE(\$auto$rename.cc:294:execute$478 ),
    .D(\sw[1] ),
    .Q(\$auto$rename.cc:294:execute$554 ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:107.5-130.8|/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) _133_ (
    .C(clk),
    .CE(\$auto$rename.cc:294:execute$478 ),
    .D(\sw[2] ),
    .Q(\$auto$rename.cc:294:execute$555 ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:107.5-130.8|/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) _134_ (
    .C(clk),
    .CE(\$auto$rename.cc:294:execute$478 ),
    .D(\sw[3] ),
    .Q(\$auto$rename.cc:294:execute$556 ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:107.5-130.8|/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) _135_ (
    .C(clk),
    .CE(\$auto$rename.cc:294:execute$478 ),
    .D(\sw[4] ),
    .Q(\$auto$rename.cc:294:execute$557 ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:107.5-130.8|/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) _136_ (
    .C(clk),
    .CE(\$auto$rename.cc:294:execute$478 ),
    .D(\sw[5] ),
    .Q(\$auto$rename.cc:294:execute$558 ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:107.5-130.8|/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) _137_ (
    .C(clk),
    .CE(\$auto$rename.cc:294:execute$478 ),
    .D(\sw[6] ),
    .Q(\$auto$rename.cc:294:execute$559 ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:107.5-130.8|/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) _138_ (
    .C(clk),
    .CE(\$auto$rename.cc:294:execute$478 ),
    .D(\sw[7] ),
    .Q(\$auto$rename.cc:294:execute$560 ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:107.5-130.8|/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) _139_ (
    .C(clk),
    .CE(\$auto$rename.cc:294:execute$478 ),
    .D(\sw[8] ),
    .Q(\$auto$rename.cc:294:execute$561 ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:107.5-130.8|/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) _140_ (
    .C(clk),
    .CE(\$auto$rename.cc:294:execute$478 ),
    .D(\sw[9] ),
    .Q(\$auto$rename.cc:294:execute$562 ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:107.5-130.8|/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) _141_ (
    .C(clk),
    .CE(\$auto$rename.cc:294:execute$477 ),
    .D(\sw[0] ),
    .Q(\$auto$rename.cc:294:execute$563 ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:107.5-130.8|/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) _142_ (
    .C(clk),
    .CE(\$auto$rename.cc:294:execute$477 ),
    .D(\sw[1] ),
    .Q(\$auto$rename.cc:294:execute$570 ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:107.5-130.8|/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) _143_ (
    .C(clk),
    .CE(\$auto$rename.cc:294:execute$477 ),
    .D(\sw[2] ),
    .Q(\$auto$rename.cc:294:execute$571 ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:107.5-130.8|/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) _144_ (
    .C(clk),
    .CE(\$auto$rename.cc:294:execute$477 ),
    .D(\sw[3] ),
    .Q(\$auto$rename.cc:294:execute$572 ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:107.5-130.8|/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) _145_ (
    .C(clk),
    .CE(\$auto$rename.cc:294:execute$477 ),
    .D(\sw[4] ),
    .Q(\$auto$rename.cc:294:execute$573 ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:107.5-130.8|/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) _146_ (
    .C(clk),
    .CE(\$auto$rename.cc:294:execute$477 ),
    .D(\sw[5] ),
    .Q(\$auto$rename.cc:294:execute$574 ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:107.5-130.8|/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) _147_ (
    .C(clk),
    .CE(\$auto$rename.cc:294:execute$477 ),
    .D(\sw[6] ),
    .Q(\$auto$rename.cc:294:execute$575 ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:107.5-130.8|/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h1)
  ) _148_ (
    .C(clk),
    .CE(\$auto$rename.cc:294:execute$477 ),
    .D(\sw[7] ),
    .Q(\$auto$rename.cc:294:execute$576 ),
    .R(1'h0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/build/xc/xc7/tests/bram/bram.v:107.5-130.8|/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/ff_map.v:68.41-68.95|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:47.3-47.67" *)
  FDRE_ZINI #(
    .IS_C_INVERTED(1'h0),
    .ZINI(1'h0)
  ) _149_ (
    .C(clk),
    .CE(\sw[11] ),
    .D(1'h1),
    .Q(\$auto$rename.cc:294:execute$579 ),
    .R(\$auto$rename.cc:294:execute$479 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:234.5-237.4|/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd2407763072)
  ) _150_ (
    .I0(\led[10] ),
    .I1(\sw[15] ),
    .I2(\sw[14] ),
    .I3(\$auto$rename.cc:294:execute$564 ),
    .I4(\$auto$rename.cc:294:execute$497 ),
    .O(\$auto$rename.cc:294:execute$490 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:234.5-237.4|/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd2407763072)
  ) _151_ (
    .I0(\led[11] ),
    .I1(\sw[15] ),
    .I2(\sw[14] ),
    .I3(\$auto$rename.cc:294:execute$565 ),
    .I4(\$auto$rename.cc:294:execute$498 ),
    .O(\$auto$rename.cc:294:execute$491 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:234.5-237.4|/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd2407763072)
  ) _152_ (
    .I0(\led[12] ),
    .I1(\sw[15] ),
    .I2(\sw[14] ),
    .I3(\$auto$rename.cc:294:execute$566 ),
    .I4(\$auto$rename.cc:294:execute$499 ),
    .O(\$auto$rename.cc:294:execute$492 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:234.5-237.4|/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd2407763072)
  ) _153_ (
    .I0(\led[13] ),
    .I1(\sw[15] ),
    .I2(\sw[14] ),
    .I3(\$auto$rename.cc:294:execute$567 ),
    .I4(\$auto$rename.cc:294:execute$500 ),
    .O(\$auto$rename.cc:294:execute$493 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:234.5-237.4|/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd2407763072)
  ) _154_ (
    .I0(\led[14] ),
    .I1(\sw[15] ),
    .I2(\sw[14] ),
    .I3(\$auto$rename.cc:294:execute$568 ),
    .I4(\$auto$rename.cc:294:execute$501 ),
    .O(\$auto$rename.cc:294:execute$494 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:51.26-53.19|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:234.5-237.4|/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd2407763072)
  ) _155_ (
    .I0(\led[15] ),
    .I1(\sw[15] ),
    .I2(\sw[14] ),
    .I3(\$auto$rename.cc:294:execute$569 ),
    .I4(\$auto$rename.cc:294:execute$502 ),
    .O(\$auto$rename.cc:294:execute$495 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:246.5-249.4|/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd3165686912)
  ) _156_ (
    .I0(\led[0] ),
    .I1(\sw[15] ),
    .I2(\sw[14] ),
    .I3(\$auto$rename.cc:294:execute$563 ),
    .I4(\$auto$rename.cc:294:execute$553 ),
    .O(\$auto$rename.cc:294:execute$514 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:253.5-256.4|/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd3216215939)
  ) _157_ (
    .I0(\led[0] ),
    .I1(\sw[15] ),
    .I2(\sw[14] ),
    .I3(\$auto$rename.cc:294:execute$563 ),
    .I4(\$auto$rename.cc:294:execute$553 ),
    .O(\$auto$rename.cc:294:execute$515 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:257.9-257.53" *)
  MUXF6 _158_ (
    .I0(\$auto$rename.cc:294:execute$514 ),
    .I1(\$auto$rename.cc:294:execute$515 ),
    .O(\$auto$rename.cc:294:execute$480 ),
    .S(\$auto$rename.cc:294:execute$496 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:246.5-249.4|/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd3163336832)
  ) _159_ (
    .I0(\led[1] ),
    .I1(\sw[15] ),
    .I2(\sw[14] ),
    .I3(\$auto$rename.cc:294:execute$554 ),
    .I4(\$auto$rename.cc:294:execute$570 ),
    .O(\$auto$rename.cc:294:execute$516 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:253.5-256.4|/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd3213865859)
  ) _160_ (
    .I0(\led[1] ),
    .I1(\sw[15] ),
    .I2(\sw[14] ),
    .I3(\$auto$rename.cc:294:execute$554 ),
    .I4(\$auto$rename.cc:294:execute$570 ),
    .O(\$auto$rename.cc:294:execute$517 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:257.9-257.53" *)
  MUXF6 _161_ (
    .I0(\$auto$rename.cc:294:execute$516 ),
    .I1(\$auto$rename.cc:294:execute$517 ),
    .O(\$auto$rename.cc:294:execute$481 ),
    .S(\$auto$rename.cc:294:execute$505 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:246.5-249.4|/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd3163336832)
  ) _162_ (
    .I0(\led[2] ),
    .I1(\sw[15] ),
    .I2(\sw[14] ),
    .I3(\$auto$rename.cc:294:execute$555 ),
    .I4(\$auto$rename.cc:294:execute$571 ),
    .O(\$auto$rename.cc:294:execute$518 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:253.5-256.4|/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd3213865859)
  ) _163_ (
    .I0(\led[2] ),
    .I1(\sw[15] ),
    .I2(\sw[14] ),
    .I3(\$auto$rename.cc:294:execute$555 ),
    .I4(\$auto$rename.cc:294:execute$571 ),
    .O(\$auto$rename.cc:294:execute$519 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:257.9-257.53" *)
  MUXF6 _164_ (
    .I0(\$auto$rename.cc:294:execute$518 ),
    .I1(\$auto$rename.cc:294:execute$519 ),
    .O(\$auto$rename.cc:294:execute$482 ),
    .S(\$auto$rename.cc:294:execute$506 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:246.5-249.4|/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd3165686912)
  ) _165_ (
    .I0(\led[3] ),
    .I1(\sw[15] ),
    .I2(\sw[14] ),
    .I3(\$auto$rename.cc:294:execute$572 ),
    .I4(\$auto$rename.cc:294:execute$556 ),
    .O(\$auto$rename.cc:294:execute$520 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:253.5-256.4|/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd3216215939)
  ) _166_ (
    .I0(\led[3] ),
    .I1(\sw[15] ),
    .I2(\sw[14] ),
    .I3(\$auto$rename.cc:294:execute$572 ),
    .I4(\$auto$rename.cc:294:execute$556 ),
    .O(\$auto$rename.cc:294:execute$521 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:257.9-257.53" *)
  MUXF6 _167_ (
    .I0(\$auto$rename.cc:294:execute$520 ),
    .I1(\$auto$rename.cc:294:execute$521 ),
    .O(\$auto$rename.cc:294:execute$483 ),
    .S(\$auto$rename.cc:294:execute$507 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:246.5-249.4|/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd3163336832)
  ) _168_ (
    .I0(\led[4] ),
    .I1(\sw[15] ),
    .I2(\sw[14] ),
    .I3(\$auto$rename.cc:294:execute$557 ),
    .I4(\$auto$rename.cc:294:execute$573 ),
    .O(\$auto$rename.cc:294:execute$522 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:253.5-256.4|/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd3213865859)
  ) _169_ (
    .I0(\led[4] ),
    .I1(\sw[15] ),
    .I2(\sw[14] ),
    .I3(\$auto$rename.cc:294:execute$557 ),
    .I4(\$auto$rename.cc:294:execute$573 ),
    .O(\$auto$rename.cc:294:execute$523 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:257.9-257.53" *)
  MUXF6 _170_ (
    .I0(\$auto$rename.cc:294:execute$522 ),
    .I1(\$auto$rename.cc:294:execute$523 ),
    .O(\$auto$rename.cc:294:execute$484 ),
    .S(\$auto$rename.cc:294:execute$508 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:246.5-249.4|/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd3165686912)
  ) _171_ (
    .I0(\led[5] ),
    .I1(\sw[15] ),
    .I2(\sw[14] ),
    .I3(\$auto$rename.cc:294:execute$574 ),
    .I4(\$auto$rename.cc:294:execute$558 ),
    .O(\$auto$rename.cc:294:execute$524 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:253.5-256.4|/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd3216215939)
  ) _172_ (
    .I0(\led[5] ),
    .I1(\sw[15] ),
    .I2(\sw[14] ),
    .I3(\$auto$rename.cc:294:execute$574 ),
    .I4(\$auto$rename.cc:294:execute$558 ),
    .O(\$auto$rename.cc:294:execute$525 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:257.9-257.53" *)
  MUXF6 _173_ (
    .I0(\$auto$rename.cc:294:execute$524 ),
    .I1(\$auto$rename.cc:294:execute$525 ),
    .O(\$auto$rename.cc:294:execute$485 ),
    .S(\$auto$rename.cc:294:execute$509 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:246.5-249.4|/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd3165686912)
  ) _174_ (
    .I0(\led[6] ),
    .I1(\sw[15] ),
    .I2(\sw[14] ),
    .I3(\$auto$rename.cc:294:execute$575 ),
    .I4(\$auto$rename.cc:294:execute$559 ),
    .O(\$auto$rename.cc:294:execute$526 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:253.5-256.4|/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd3216215939)
  ) _175_ (
    .I0(\led[6] ),
    .I1(\sw[15] ),
    .I2(\sw[14] ),
    .I3(\$auto$rename.cc:294:execute$575 ),
    .I4(\$auto$rename.cc:294:execute$559 ),
    .O(\$auto$rename.cc:294:execute$527 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:257.9-257.53" *)
  MUXF6 _176_ (
    .I0(\$auto$rename.cc:294:execute$526 ),
    .I1(\$auto$rename.cc:294:execute$527 ),
    .O(\$auto$rename.cc:294:execute$486 ),
    .S(\$auto$rename.cc:294:execute$510 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:246.5-249.4|/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd3165686912)
  ) _177_ (
    .I0(\led[7] ),
    .I1(\sw[15] ),
    .I2(\sw[14] ),
    .I3(\$auto$rename.cc:294:execute$576 ),
    .I4(\$auto$rename.cc:294:execute$560 ),
    .O(\$auto$rename.cc:294:execute$528 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:253.5-256.4|/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd3216215939)
  ) _178_ (
    .I0(\led[7] ),
    .I1(\sw[15] ),
    .I2(\sw[14] ),
    .I3(\$auto$rename.cc:294:execute$576 ),
    .I4(\$auto$rename.cc:294:execute$560 ),
    .O(\$auto$rename.cc:294:execute$529 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:257.9-257.53" *)
  MUXF6 _179_ (
    .I0(\$auto$rename.cc:294:execute$528 ),
    .I1(\$auto$rename.cc:294:execute$529 ),
    .O(\$auto$rename.cc:294:execute$487 ),
    .S(\$auto$rename.cc:294:execute$511 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:246.5-249.4|/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd3165686912)
  ) _180_ (
    .I0(\led[8] ),
    .I1(\sw[15] ),
    .I2(\sw[14] ),
    .I3(\$auto$rename.cc:294:execute$577 ),
    .I4(\$auto$rename.cc:294:execute$561 ),
    .O(\$auto$rename.cc:294:execute$530 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:253.5-256.4|/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd3216215939)
  ) _181_ (
    .I0(\led[8] ),
    .I1(\sw[15] ),
    .I2(\sw[14] ),
    .I3(\$auto$rename.cc:294:execute$577 ),
    .I4(\$auto$rename.cc:294:execute$561 ),
    .O(\$auto$rename.cc:294:execute$531 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:257.9-257.53" *)
  MUXF6 _182_ (
    .I0(\$auto$rename.cc:294:execute$530 ),
    .I1(\$auto$rename.cc:294:execute$531 ),
    .O(\$auto$rename.cc:294:execute$488 ),
    .S(\$auto$rename.cc:294:execute$512 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:246.5-249.4|/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd3163336832)
  ) _183_ (
    .I0(\led[9] ),
    .I1(\sw[15] ),
    .I2(\sw[14] ),
    .I3(\$auto$rename.cc:294:execute$562 ),
    .I4(\$auto$rename.cc:294:execute$578 ),
    .O(\$auto$rename.cc:294:execute$532 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:253.5-256.4|/usr/local/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30" *)
  LUT5 #(
    .INIT(32'd3213865859)
  ) _184_ (
    .I0(\led[9] ),
    .I1(\sw[15] ),
    .I2(\sw[14] ),
    .I3(\$auto$rename.cc:294:execute$562 ),
    .I4(\$auto$rename.cc:294:execute$578 ),
    .O(\$auto$rename.cc:294:execute$533 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/lut_map.v:56.26-58.30|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:257.9-257.53" *)
  MUXF6 _185_ (
    .I0(\$auto$rename.cc:294:execute$532 ),
    .I1(\$auto$rename.cc:294:execute$533 ),
    .O(\$auto$rename.cc:294:execute$489 ),
    .S(\$auto$rename.cc:294:execute$513 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/butta/Documents/independent-study/symbiflow-arch-defs/env/conda/envs/symbiflow_arch_def_base/bin/../share/yosys/xilinx/xc7_brams_map.v:296.5-320.4|/home/butta/Documents/independent-study/symbiflow-arch-defs/xc/xc7/techmap/cells_map.v:1270.5-1299.4" *)
  RAMB18E1_VPR #(
    .DOA_REG(1'h0),
    .DOB_REG(1'h0),
    .INITP_00(256'h0000000000000000000000000000000000000000000000000000000000004450),
    .INITP_01(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INITP_02(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INITP_03(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INITP_04(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INITP_05(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INITP_06(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INITP_07(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_00(256'h00000000000000000000000000040002193366cc070f78f07fff2a5555aa0001),
    .INIT_01(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_02(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_03(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_04(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_05(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_06(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_07(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_08(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_09(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_0A(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_0B(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_0C(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_0D(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_0E(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_0F(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_10(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_11(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_12(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_13(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_14(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_15(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_16(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_17(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_18(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_19(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_1A(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_1B(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_1C(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_1D(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_1E(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_1F(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_20(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_21(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_22(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_23(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_24(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_25(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_26(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_27(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_28(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_29(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_2A(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_2B(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_2C(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_2D(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_2E(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_2F(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_30(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_31(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_32(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_33(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_34(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_35(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_36(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_37(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_38(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_39(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_3A(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_3B(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_3C(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_3D(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_3E(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .INIT_3F(256'h0000000000000000000000000000000000000000000000000000000000000000),
    .IN_USE(1'h1),
    .READ_WIDTH_A_1(1'h0),
    .READ_WIDTH_A_18(1'h1),
    .READ_WIDTH_A_2(1'h0),
    .READ_WIDTH_A_4(1'h0),
    .READ_WIDTH_A_9(1'h0),
    .READ_WIDTH_B_1(1'h0),
    .READ_WIDTH_B_18(1'h1),
    .READ_WIDTH_B_2(1'h0),
    .READ_WIDTH_B_4(1'h0),
    .READ_WIDTH_B_9(1'h0),
    .SDP_READ_WIDTH_36(1'h0),
    .SDP_WRITE_WIDTH_36(1'h0),
    .WRITE_MODE_A_NO_CHANGE(1'h0),
    .WRITE_MODE_A_READ_FIRST(1'h1),
    .WRITE_MODE_B_NO_CHANGE(1'h0),
    .WRITE_MODE_B_READ_FIRST(1'h1),
    .WRITE_WIDTH_A_1(1'h0),
    .WRITE_WIDTH_A_18(1'h1),
    .WRITE_WIDTH_A_2(1'h0),
    .WRITE_WIDTH_A_4(1'h0),
    .WRITE_WIDTH_A_9(1'h0),
    .WRITE_WIDTH_B_1(1'h0),
    .WRITE_WIDTH_B_18(1'h1),
    .WRITE_WIDTH_B_2(1'h0),
    .WRITE_WIDTH_B_4(1'h0),
    .WRITE_WIDTH_B_9(1'h0),
    .Y0_READ_WIDTH_A_1(1'h0),
    .Y0_READ_WIDTH_A_18(1'h1),
    .Y1_READ_WIDTH_A_1(1'h0),
    .Y1_READ_WIDTH_A_18(1'h1),
    .ZINIT_A(18'h3ffff),
    .ZINIT_B(18'h3ffff),
    .ZINV_CLKARDCLK(1'h1),
    .ZINV_CLKBWRCLK(1'h1),
    .ZINV_ENARDEN(1'h1),
    .ZINV_ENBWREN(1'h1),
    .ZINV_REGCLKARDRCLK(1'h0),
    .ZINV_REGCLKB(1'h0),
    .ZINV_RSTRAMARSTRAM(1'h0),
    .ZINV_RSTRAMB(1'h0),
    .ZINV_RSTREGARSTREG(1'h0),
    .ZINV_RSTREGB(1'h0),
    .ZSRVAL_A(18'h3ffff),
    .ZSRVAL_B(18'h3ffff)
  ) \ram.ram.0.0.0  (
    .ADDRARDADDR({ \$auto$rename.cc:294:execute$562 , \$auto$rename.cc:294:execute$561 , \$auto$rename.cc:294:execute$560 , \$auto$rename.cc:294:execute$559 , \$auto$rename.cc:294:execute$558 , \$auto$rename.cc:294:execute$557 , \$auto$rename.cc:294:execute$556 , \$auto$rename.cc:294:execute$555 , \$auto$rename.cc:294:execute$554 , \$auto$rename.cc:294:execute$553 , 4'h0 }),
    .ADDRATIEHIGH(2'h3),
    .ADDRBTIEHIGH(2'h3),
    .ADDRBWRADDR({ \$auto$rename.cc:294:execute$562 , \$auto$rename.cc:294:execute$561 , \$auto$rename.cc:294:execute$560 , \$auto$rename.cc:294:execute$559 , \$auto$rename.cc:294:execute$558 , \$auto$rename.cc:294:execute$557 , \$auto$rename.cc:294:execute$556 , \$auto$rename.cc:294:execute$555 , \$auto$rename.cc:294:execute$554 , \$auto$rename.cc:294:execute$553 , 4'h0 }),
    .CLKARDCLK(clk),
    .CLKBWRCLK(clk),
    .DIADI(16'h0000),
    .DIBDI({ 1'h0, \$auto$rename.cc:294:execute$569 , \$auto$rename.cc:294:execute$568 , \$auto$rename.cc:294:execute$567 , \$auto$rename.cc:294:execute$566 , \$auto$rename.cc:294:execute$565 , \$auto$rename.cc:294:execute$564 , \$auto$rename.cc:294:execute$578 , \$auto$rename.cc:294:execute$576 , \$auto$rename.cc:294:execute$575 , \$auto$rename.cc:294:execute$574 , \$auto$rename.cc:294:execute$573 , \$auto$rename.cc:294:execute$572 , \$auto$rename.cc:294:execute$571 , \$auto$rename.cc:294:execute$570 , \$auto$rename.cc:294:execute$563  }),
    .DIPADIP(2'h0),
    .DIPBDIP({ 1'h0, \$auto$rename.cc:294:execute$577  }),
    .DOADO({ \$auto$rename.cc:294:execute$503 , \$auto$rename.cc:294:execute$502 , \$auto$rename.cc:294:execute$501 , \$auto$rename.cc:294:execute$500 , \$auto$rename.cc:294:execute$499 , \$auto$rename.cc:294:execute$498 , \$auto$rename.cc:294:execute$497 , \$auto$rename.cc:294:execute$513 , \$auto$rename.cc:294:execute$511 , \$auto$rename.cc:294:execute$510 , \$auto$rename.cc:294:execute$509 , \$auto$rename.cc:294:execute$508 , \$auto$rename.cc:294:execute$507 , \$auto$rename.cc:294:execute$506 , \$auto$rename.cc:294:execute$505 , \$auto$rename.cc:294:execute$496  }),
    .DOBDO({ \$auto$rename.cc:294:execute$540 , \$auto$rename.cc:294:execute$539 , \$auto$rename.cc:294:execute$538 , \$auto$rename.cc:294:execute$537 , \$auto$rename.cc:294:execute$536 , \$auto$rename.cc:294:execute$535 , \$auto$rename.cc:294:execute$549 , \$auto$rename.cc:294:execute$548 , \$auto$rename.cc:294:execute$547 , \$auto$rename.cc:294:execute$546 , \$auto$rename.cc:294:execute$545 , \$auto$rename.cc:294:execute$544 , \$auto$rename.cc:294:execute$543 , \$auto$rename.cc:294:execute$542 , \$auto$rename.cc:294:execute$541 , \$auto$rename.cc:294:execute$534  }),
    .DOPADOP({ \$auto$rename.cc:294:execute$504 , \$auto$rename.cc:294:execute$512  }),
    .DOPBDOP({ \$auto$rename.cc:294:execute$551 , \$auto$rename.cc:294:execute$550  }),
    .ENARDEN(1'h1),
    .ENBWREN(1'h1),
    .REGCEAREGCE(1'h1),
    .REGCEB(1'h0),
    .REGCLKARDRCLK(1'h1),
    .REGCLKB(1'h1),
    .RSTRAMARSTRAM(1'h1),
    .RSTRAMB(1'h1),
    .RSTREGARSTREG(1'h1),
    .RSTREGB(1'h1),
    .WEA(4'h0),
    .WEBWE({ 4'h0, \$auto$rename.cc:294:execute$579 , \$auto$rename.cc:294:execute$579 , \$auto$rename.cc:294:execute$579 , \$auto$rename.cc:294:execute$579  })
  );
  assign tx = rx;
endmodule
